/**
 * Provisions a complete Marketing Calendar board for a new client.
 *
 *   node scripts/provision-client.mjs --spec path/to/spec.json
 *
 * One spec in, one live board out: creates the D1 database, applies the
 * schema, writes the client's brand into a temporary brand.config.ts,
 * regenerates the home-screen icons, deploys a worker named after the client,
 * sets a generated team password, and links the new board into every existing
 * board's switcher (and every existing board into the new one).
 *
 * Runs the same way from GitHub Actions (the console's Add-client button) and
 * from a laptop (wrangler's own login). The calendar folder is edited in
 * place and always restored — the spec never touches the repo's own brand.
 *
 * Spec shape:
 * {
 *   "name": "Dartee Golf",            // brand name shown in the nav
 *   "slug": "dartee-golf",            // worker + database become <slug>-calendar
 *   "shortName": "Dartee",            // under the phone icon (~11 chars)
 *   "productName": "Marketing Calendar",
 *   "font": "Inter",                  // any Google Fonts family
 *   "colors": { background, surface, primary, primaryText, text, textMuted,
 *               danger, tentative, scrim },   // full palette, hex
 *   "logoSvg": "<svg …>…</svg>",      // single-colour mark; omit for default
 *   "logoTint": true,
 *   "agencyEmails": ["cole@…"],       // who sees cross-board switcher entries
 *   "boards": [{ "label": "Lucky Golf", "url": "https://…", "db": "launch-calendar" }]
 *                                      // existing boards to cross-link
 * }
 *
 * Prints PROVISION_RESULT={json} on the last line: { url, password, dbId }.
 */

import { execFileSync } from "node:child_process";
import { copyFileSync, existsSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const npx = process.platform === "win32" ? "npx.cmd" : "npx";
const npm = process.platform === "win32" ? "npm.cmd" : "npm";

function run(command, args, options = {}) {
  return execFileSync(command, args, {
    cwd: root,
    encoding: "utf8",
    stdio: ["ignore", "pipe", "pipe"],
    shell: process.platform === "win32",
    ...options,
  });
}

const specArg = process.argv.indexOf("--spec");
if (specArg === -1 || !process.argv[specArg + 1]) {
  console.error("Usage: node scripts/provision-client.mjs --spec spec.json");
  process.exit(1);
}
const spec = JSON.parse(readFileSync(process.argv[specArg + 1], "utf8"));

for (const field of ["name", "slug", "colors"]) {
  if (!spec[field]) {
    console.error(`Spec is missing "${field}".`);
    process.exit(1);
  }
}
if (!/^[a-z0-9][a-z0-9-]{1,40}$/.test(spec.slug)) {
  console.error(`Slug "${spec.slug}" must be lowercase letters, digits and dashes.`);
  process.exit(1);
}

const workerName = `${spec.slug}-calendar`;
const REQUIRED_COLORS = [
  "background", "surface", "primary", "primaryText", "text", "textMuted",
  "danger", "tentative", "scrim",
];
for (const key of REQUIRED_COLORS) {
  if (!/^#[0-9a-fA-F]{6}$/.test(spec.colors[key] ?? "")) {
    console.error(`Colour "${key}" must be a 6-digit hex value.`);
    process.exit(1);
  }
}

/** A password the client's team can actually read out loud on a call. */
function generatePassword() {
  const words = [
    "green", "fairway", "launch", "summer", "harbor", "maple", "copper",
    "signal", "meadow", "anchor", "ember", "prairie", "cedar", "atlas",
  ];
  const pick = () => words[Math.floor(Math.random() * words.length)];
  const digits = String(Math.floor(Math.random() * 90) + 10);
  return `${pick()}-${pick()}-${digits}`;
}

/** JSON → the brand.config.ts the build bakes in. */
function brandConfigSource() {
  const config = {
    name: spec.name,
    productName: spec.productName || "Marketing Calendar",
    shortName: spec.shortName || "Calendar",
    logoUrl: "/logo.svg",
    logoTint: spec.logoTint !== false,
    colors: Object.fromEntries(REQUIRED_COLORS.map((key) => [key, spec.colors[key]])),
    font: {
      family: spec.font || "Inter",
      headingWeight: 700,
      bodyWeight: 400,
    },
  };
  return (
    "// Generated by scripts/provision-client.mjs — do not commit.\n" +
    `export const brand = ${JSON.stringify(config, null, 2)};\n\n` +
    "export type Brand = typeof brand;\n"
  );
}

const backups = new Map();
function stash(relative) {
  const path = join(root, relative);
  backups.set(path, readFileSync(path));
}
function restoreAll() {
  for (const [path, content] of backups) writeFileSync(path, content);
}

/**
 * wrangler d1 execute via a temp file, always passed as a RELATIVE path: on
 * Windows the args go through a shell, and this repo's absolute path contains
 * spaces that would tear the command apart.
 */
function d1Run(database, sql, { json: asJson = false } = {}) {
  const relative = `.wrangler/provision-${Date.now()}-${Math.floor(Math.random() * 1e6)}.sql`;
  writeFileSync(join(root, relative), sql);
  try {
    const args = ["wrangler", "d1", "execute", database, "--remote", "-y", `--file=${relative}`];
    if (asJson) args.push("--json");
    return run(npx, args);
  } finally {
    try { writeFileSync(join(root, relative), ""); } catch { /* best effort */ }
  }
}

function d1Execute(database, sql) {
  return d1Run(database, sql);
}

function d1Query(database, sql) {
  const out = d1Run(database, sql, { json: true });
  const parsed = JSON.parse(out.slice(out.indexOf("[")));
  return parsed[0]?.results ?? [];
}

/**
 * Adds entries to one board's switcher list, keeping whatever it already has.
 * Restricted to the agency emails, so client teams never see each other.
 */
function linkIntoBoard(database, entries, agencyEmails) {
  const rows = d1Query(database, `SELECT value FROM settings WHERE key = 'boards'`);
  let current = [];
  try {
    const parsed = JSON.parse(rows[0]?.value ?? "[]");
    if (Array.isArray(parsed)) current = parsed;
  } catch { /* start fresh */ }

  for (const entry of entries) {
    const url = entry.url.endsWith("/") ? entry.url : `${entry.url}/`;
    if (current.some((existing) => existing.url === url)) continue;
    current.push({ label: entry.label, url, emails: agencyEmails });
  }

  const value = JSON.stringify(current).replace(/'/g, "''");
  d1Execute(
    database,
    `INSERT INTO settings (key, value, updated_at) VALUES ('boards', '${value}', '${new Date().toISOString()}')
     ON CONFLICT(key) DO UPDATE SET value = excluded.value, updated_at = excluded.updated_at;`,
  );
}

// --- 1. Database -----------------------------------------------------------

console.log(`Creating database ${workerName}…`);
let dbId;
try {
  const created = run(npx, ["wrangler", "d1", "create", workerName]);
  dbId = created.match(/"?database_id"?[":\s=]+"?([0-9a-f-]{36})/)?.[1];
} catch (error) {
  const message = String(error.stdout ?? "") + String(error.stderr ?? "");
  if (!/already exists/i.test(message)) throw error;
}
if (!dbId) {
  const list = JSON.parse(run(npx, ["wrangler", "d1", "list", "--json"]));
  dbId = list.find((db) => db.name === workerName)?.uuid;
}
if (!dbId) throw new Error("Could not determine the new database id.");
console.log(`Database id: ${dbId}`);

console.log("Applying schema…");
run(npx, ["wrangler", "d1", "execute", workerName, "--remote", "-y", "--file=./db/schema.sql"]);

// --- 2. Brand + config, deploy, restore ------------------------------------

stash("brand.config.ts");
stash("wrangler.jsonc");
stash("public/logo.svg");

let url;
const password = generatePassword();
try {
  writeFileSync(join(root, "brand.config.ts"), brandConfigSource());
  if (spec.logoSvg) writeFileSync(join(root, "public", "logo.svg"), spec.logoSvg);

  const wranglerConfig = backups
    .get(join(root, "wrangler.jsonc"))
    .toString()
    .replace(/"name":\s*"[^"]+"/, `"name": "${workerName}"`)
    .replace(/"database_name":\s*"[^"]+"/, `"database_name": "${workerName}"`)
    .replace(/"database_id":\s*"[^"]+"/, `"database_id": "${dbId}"`)
    // Client boards carry no scheduled trigger of their own — the free plan
    // caps them per account. The board that has one fans out to its siblings
    // (worker-entry.js), so Slack batching still runs everywhere.
    .replace(/"triggers":\s*\{[^}]*\},?/s, "");
  writeFileSync(join(root, "wrangler.jsonc"), wranglerConfig);

  console.log("Rendering home-screen icons…");
  run(npm, ["run", "icons"]);

  console.log("Building and deploying (a few minutes)…");
  const deployOut = run(npm, ["run", "deploy"]);
  url = deployOut.match(/https:\/\/[a-z0-9-]+\.[a-z0-9-]+\.workers\.dev/)?.[0];
  if (!url) throw new Error("Deploy finished but printed no workers.dev address.");
  console.log(`Deployed: ${url}`);

  console.log("Setting the team password…");
  run(npx, ["wrangler", "secret", "put", "APP_PASSWORD", "--name", workerName], {
    input: password,
    stdio: ["pipe", "pipe", "pipe"],
  });

  if (spec.cronSecret) {
    console.log("Setting the shared cron key…");
    run(npx, ["wrangler", "secret", "put", "CRON_SECRET", "--name", workerName], {
      input: spec.cronSecret,
      stdio: ["pipe", "pipe", "pipe"],
    });
  }
} finally {
  restoreAll();
  // The icons belong to the repo's own brand — put those back too.
  if (existsSync(join(root, "public", "icons"))) {
    try { run(npm, ["run", "icons"]); } catch { /* repo icons can be regenerated later */ }
  }
}

// --- 3. Cross-link the switchers -------------------------------------------

const agencyEmails = Array.isArray(spec.agencyEmails) ? spec.agencyEmails : [];
const existing = Array.isArray(spec.boards) ? spec.boards : [];

if (agencyEmails.length > 0) {
  console.log("Linking switchers…");
  for (const board of existing) {
    try {
      linkIntoBoard(board.db, [{ label: spec.name, url }], agencyEmails);
    } catch (error) {
      console.error(`Could not link into ${board.db}: ${error.message}`);
    }
  }
  if (existing.length > 0) {
    linkIntoBoard(
      workerName,
      existing.map((board) => ({ label: board.label, url: board.url })),
      agencyEmails,
    );
  }
} else {
  console.log("No agency emails in the spec — skipping switcher links.");
}

console.log(`\nPROVISION_RESULT=${JSON.stringify({ url, password, dbId, workerName })}`);
