# -*- coding: utf-8 -*-
"""Generate the demo account used for the Shopify App Store submission.

Why this exists: every remaining listing field (screenshots, feature media, the
screencast, and the reviewer's test login) shows the tool in use, and Shopify's own
upload form requires that "any account information displayed is fictional and not data
from a real person". Screenshotting the live tool would publish six real brands'
revenue and margins on a public listing page.

So this writes ONE fabricated brand with internally consistent figures, which the
demo session is pinned to. The numbers are invented but they have to hold together, or
the tool's own diagnostics will flag the demo as broken on camera:

  - revenue is Shopify TOTAL SALES, so netSales already contains shipping AND tax
  - newCustomerSales + rcRevenue sum exactly to netSales
  - product cost holds a steady share of net sales, so judgeCosts() reads "ok"
    rather than "noisy" (a wandering daily margin is what that check exists to catch)
  - shipping COST differs from shipping PRICE, so shippingMode() reads "measured"
    rather than "mirrored" - the demo should show the healthy state
  - contribution margin stays positive every day, so no day looks like wholesale

Isolation is not this file's job alone: the row is written with active = 0 and
brief_enabled = 0 so it can never reach Account Health's account list or the Slack
brief, both of which require active = 1.

Run:  python make-demo-data.py > demo.sql
Then: npx.cmd wrangler d1 execute mobius-account-health --remote --file=demo.sql
"""
import datetime
import json
import math
import random

ACT = 'demo_harborline'
NAME = 'Harborline Supply'
SHOP = 'harborline-supply-demo.myshopify.com'
DAYS = 420
END = datetime.date(2026, 8, 23)          # yesterday; today is 2026-08-24
START = END - datetime.timedelta(days=DAYS - 1)

# Deterministic: regenerating must not silently change what the screenshots showed.
rnd = random.Random(20260824)

# Weekday shape, Monday=0. Quiet Sundays, strong midweek - a believable pattern that
# the rhythm card can actually describe.
WEEKDAY = [1.02, 1.08, 1.06, 1.00, 0.98, 0.94, 0.92]

rows = []          # (date, metric, value)
month_orders = {}  # YYYY-MM -> orders, for the cohort table


def emit(d, metric, value):
    rows.append((d.isoformat(), metric, round(value, 2)))


for i in range(DAYS):
    d = START + datetime.timedelta(days=i)
    t = i / (DAYS - 1.0)

    # Steady growth plus a seasonal lift into Q4.
    trend = 1.0 + 0.42 * t
    doy = d.timetuple().tm_yday
    season = 1.0 + 0.16 * math.sin((doy - 80) / 365.0 * 2 * math.pi)
    peak = 1.55 if (d.month == 11 and 24 <= d.day <= 30) else 1.0

    orders = 54 * trend * season * WEEKDAY[d.weekday()] * peak * rnd.uniform(0.93, 1.07)
    orders = max(12, round(orders))
    aov = 78.0 * rnd.uniform(0.96, 1.04) * (0.94 if peak > 1 else 1.0)

    net_sales = orders * aov                       # Shopify NET SALES (no ship, no tax)
    ship_rev = orders * 6.45 * rnd.uniform(0.97, 1.03)
    tax = net_sales * 0.0082 * rnd.uniform(0.9, 1.1)
    total_sales = net_sales + ship_rev + tax       # what TW calls netSales

    # Costs. Product cost holds a steady share so the cost-health check reads "ok".
    product = net_sales * rnd.uniform(0.330, 0.343)
    ship_cost = orders * 5.05 * rnd.uniform(0.96, 1.04)   # NOT equal to ship_rev
    handling = orders * 0.34
    fees = (net_sales + ship_rev) * 0.029 + orders * 0.30

    sales = total_sales - tax                      # the one revenue definition
    mer = 2.62 * rnd.uniform(0.94, 1.06) * (1.18 if peak > 1 else 1.0)
    ads = sales / mer

    new_share = 0.615 * rnd.uniform(0.95, 1.05)
    new_sales = total_sales * new_share
    rc_sales = total_sales - new_sales             # sums to total_sales exactly
    new_orders = max(1, round(orders * new_share))

    emit(d, 'netSales', total_sales)
    emit(d, 'totalNetTaxes', tax)
    emit(d, 'totalShippingPrice', ship_rev)
    emit(d, 'totalShippingCosts', ship_cost)
    emit(d, 'totalHandlingFees', handling)
    emit(d, 'totalProductCosts', product)
    emit(d, 'totalPaymentGatewayCosts', fees)
    emit(d, 'blendedAds', ads)
    emit(d, 'totalOrders', orders)
    emit(d, 'newCustomersOrders', new_orders)
    emit(d, 'newCustomerSales', new_sales)
    emit(d, 'rcRevenue', rc_sales)

    ym = d.strftime('%Y-%m')
    month_orders[ym] = month_orders.get(ym, 0) + new_orders


def sq(s):
    return "'" + str(s).replace("'", "''") + "'"


out = []
out.append('-- Demo account for the Shopify App Store submission. Fictional data.')
out.append('-- Generated by profit/assets/make-demo-data.py - edit that, not this.')
out.append('')
out.append("DELETE FROM tw_daily WHERE act_id = %s;" % sq(ACT))
out.append("DELETE FROM p_cohorts WHERE act_id = %s;" % sq(ACT))
out.append("DELETE FROM p_plan WHERE act_id = %s;" % sq(ACT))
out.append('')

# Monthly plans for the last few months plus the next one, so the Plan tab and the
# month-to-date pacing both have something to show.
goals = {}
for ym, target in [('2026-06', 176000), ('2026-07', 188000), ('2026-08', 198000),
                   ('2026-09', 212000)]:
    goals[ym] = {'sales': target, 'spend': round(target / 2.65)}
goals_json = json.dumps(goals)

# active = 0 and brief_enabled = 0 are the isolation: Account Health lists and the
# Slack brief both require active = 1, so neither can ever pick this row up.
out.append(
    "INSERT INTO accounts (act_id, name, currency, tz, active, demo, tw_shop, goals_json, "
    "brief_enabled) VALUES (%s, %s, 'USD', 'America/Chicago', 0, 1, %s, %s, 0) "
    "ON CONFLICT(act_id) DO UPDATE SET name = excluded.name, demo = 1, active = 0, "
    "tw_shop = excluded.tw_shop, goals_json = excluded.goals_json, brief_enabled = 0;"
    % (sq(ACT), sq(NAME), sq(SHOP), sq(goals_json))
)
out.append('')

# tw_daily, in chunks so no single statement gets unwieldy.
CH = 200
for i in range(0, len(rows), CH):
    vals = ','.join(
        '(%s,%s,%s,%s)' % (sq(ACT), sq(d), sq(m), v) for d, m, v in rows[i:i + CH]
    )
    out.append('INSERT OR REPLACE INTO tw_daily (act_id, date, metric, value) VALUES %s;' % vals)
out.append('')

# Cohorts: customers grouped by the month they first bought. Older cohorts have had
# longer to come back, so orders per customer rises with age - which is the whole
# point of the card. Anything under 9 months old is excluded from the averages by the
# API, so these young rows exist to be visibly faded, not to move the numbers.
coh = []
months = sorted(month_orders.keys())
for ym in months:
    y, m = map(int, ym.split('-'))
    age = (2026 - y) * 12 + (8 - m)
    customers = max(20, int(month_orders[ym] * 0.86))
    maturity = min(1.0, age / 11.0)
    orders_per = 1.0 + 0.30 * maturity
    repeat_rate = 0.055 + 0.175 * maturity
    first_aov = 74.0 + 6.0 * (1 - maturity)          # newer cohorts arrive slightly bigger
    lifetime_orders = int(round(customers * orders_per))
    lifetime_spend = lifetime_orders * first_aov * 0.99
    coh.append((ym, customers, int(round(customers * repeat_rate)),
                round(lifetime_spend, 2), lifetime_orders))

vals = ','.join(
    "(%s,%s,%d,%d,%s,%d,'2026-08-23')" % (sq(ACT), sq(ym), c, rc, sp, lo)
    for ym, c, rc, sp, lo in coh
)
out.append(
    'INSERT OR REPLACE INTO p_cohorts (act_id, cohort_month, customers, repeat_customers, '
    'lifetime_spend, lifetime_orders, as_of) VALUES %s;' % vals
)

print('\n'.join(out))
