# Hand-authored part of the Viktor import: line mapping, market enums, claims made / open ground,
# competitor names for complaint rows. Everything else is parsed from the docs (parse.py).
# House rule: no em dashes in anything written here.

ACTS = {
    'Party Patch': 'act_1033194534145987',
    'Bonk Golf': 'act_12528825',
    'Dartee Golf': 'act_963898971023823',
    'Grunk Dolfer': 'act_313396960515158',
}

# One entry per Viktor line, in doc order. map = existing p_br_line id, or None to insert a new line.
# upd = new about/products for an EXISTING line only where the existing text is thinner.
LINES = {
 'Party Patch': [
  dict(key='core', map='acd1815908b24573', ref='C',
       upd=dict(products='The Party Patch (Traditional), a clear vitamin patch worn while drinking (now scent-free). 5-pack $19.99, 12-pack $39.99, 25-pack $79.99, 50-pack $159.99. Bought for yourself, then repeated.'),
       awareness='problem', stage='4',
       claims=['"No hangover" / "wake up refreshed"', '"No pills, no powders", "through your skin", "24 hours"', '"Made in USA", "natural"', 'DHM / liver detox mechanisms (The Patch Brand, Vibe, Cheers) and "genetically engineered probiotics" (ZBiotics)', 'Our own past ads: "Own your morning", "Win tomorrow", "Party now. Function tomorrow.", "500,000+"'],
       open=['"It didn\'t used to hit like this": the age-honest angle (C2, C3, C4, C35); 35+ women convert on 352 A', '"For people who barely drink": migraine and low-tolerance drinkers (C6, C7, C8); competitors talk to bingers', 'Honest "7 to a 2" framing: degree claims beat miracle claims (C12, C40); no competitor admits a limit', 'Wearers vs. non-wearers proof: groups run their own "control tests" (P4, P5, P40, P36)', '"Hidden, not medical": "No seeing = no judgement" (C41), answers the "drunk advertisement" objection (C39)', 'Scent-free handled honestly: smell was the #1 objection (C19, C20, C30, C37), but pair it with proof the new one still works (C32 to C34)']),
  dict(key='themes', map=None, ref='P', sort=10,
       name='Party Themes (group and occasion packs)',
       about='The planner or gifter buying for a group: make sure the whole crew makes it to Day 2, and the pack doubles as an on-theme favor. Event-dated (bachelorette, wedding, milestone birthday trip, cruise, holidays). The theme is printed on the packet only; the patch itself is the standard clear one.',
       products='About 50 themed designs (Bride Squad, Bride Tribe, 30th/40th/50th/60th Birthday, Booze Cruise, Ship Faced, Galentine\'s, holidays). 5-pack $19.99, 12-pack $39.99, 25-pack $79.99, 50-pack $159.99.',
       awareness='solution', stage='3',
       claims=['"Perfect wedding and party favors" (Booze Bandage)', '"Bachelorette, Wedding & Party Essential" (Bytox on Amazon)', 'Our own past ads: "Bride Squad Survival Kit", "Wedding Crew Discount Active", "The Bride Deserves a Functional Crew"'],
       open=['"Protect Day 2", framed as a loss (P35, P36)', 'The wearers vs. the non-wearers: group proof content (P4, P5, P40)', '"The favor that isn\'t a waste" (P42, P43)', 'Upfront that the theme is on the packet and the patch stays clear and discreet, which turns the P11 to P14 complaint into a feature (C41)']),
  dict(key='custom', map='2223c03d8030471d', ref='D',
       upd=dict(products='Design Your Own Patch (Zakeke customizer): your logo, text or photo on the packaging only, not on the patch. 25-pack $112.00 to $112.50, 50 $225, 100 $450, 150 $675, 250 $1,125. Ships in 7 to 10 business days.'),
       awareness='solution', stage='2',
       claims=['Booze Bandage: corporate and wedding favors, "the ultimate power move for a company"'],
       open=['"The only swag they\'ll thank you for tomorrow" (D2, D9)', 'Sampling-led B2B: trade-show giveaways turn people into direct buyers (D9, D12)']),
 ],
 'Bonk Golf': [
  dict(key='hats', map='1c8ae2e739554a9d', ref='',
       awareness='problem', stage='4',
       claims=['Magnetic brim or bill plus tee holder (Holen, BRIMZ, Piss Missile, NJF, Pins & Aces magnet)', 'No more fumbling / digging through pockets (Holen, and our own 203B, 225, 226)', 'Sweat and water resistant, breathable (everyone)', 'Free matching ball marker (Pins & Aces, with lifetime replacement)', '"A hat that actually does something" (Piss Missile, and our own 243A)', 'Premium, "For those who notice." (Melin); "golf hat of the year" (BRIMZ)'],
       open=['The complete matched set: hat, marker, divot tool, tees and towel as one system ("Others offer a feature. BONK offers an ecosystem.")', 'Fit range for real heads: XL snapbacks, PF 2.0 S/M to 2XL, Youth, Southpaw ("Finally an extra large hat that is actually XL!!")', 'Lefties: Southpaw hats exist nowhere else in the ad library (#southpawsmatter)', 'Real humans answer: customer-service praise in dozens of reviews, nobody advertises it', 'Worn-hard everyday hat (PF 2.0): yard work to gym to course, against Melin\'s price', 'Honest magnet: a demo of the marker staying put through a full swing answers the #1 functional objection']),
  dict(key='gifts', map=None, ref='', sort=10,
       name='Gifts and Bundles',
       about='Bought by someone else, usually a wife, girlfriend, mom or aunt: a gift he will actually use and brag about, not another golf-themed guess. The complete matched set in one box lets a non-golfer buy with confidence.',
       products='Ultimate BONK Bundle $59.95, Performer Bundle $100 (hat, marker, divot tool, magnetic towel, 10 tees), Lifestyle Bundle $79.95, 250 Bundle $67.39, Breakfast Ball and Pandorg Bundles $59.95, Family BONK Bundle $93.64, Youth Snapbacks $38.95 to $42.95.',
       awareness='unaware', stage='3',
       claims=['Golf-gift ads are common (Pins & Aces sells a huge gift catalog)', 'Bundle savings claims must match the site: old ads said "$30" saved, the site says $22.90'],
       open=['The complete setup in one box, from real people who will get it there on time (Christmas rescue stories in reviews)', '"It\'s time to retire his old golf cap" gift frame (235 A/B/C)']),
  dict(key='women', map=None, ref='', sort=11,
       name="Women's Open Backs and Visors",
       about='She wants a golf hat that fits her head and her hair and looks cute, with the marker and tees built in because her golf clothes have no real pockets.',
       products='Unstructured Open Backs (3 ponytail positions) and Visors with the magnet and tee slot, $42.95; matching markers (pink panda, flower).',
       awareness='solution', stage='2',
       claims=['Almost nothing women-specific in the ad library; Curves and Clubs is style-led ("Life is too short to wear boring golf hats.")'],
       open=['Built for your hair, not just your head (only our 211B and 267C tried it)', 'Pockets optional: the marker and tees live on the hat', 'Non-floral performance colorways ("not all ladies like flowers and girly things.")']),
  dict(key='drops', map=None, ref='', sort=12,
       name='Limited and Identity Drops',
       about='Wear who you are (patriot, first responder, collector, the funny guy with the "breakfast ball") and get it before it is gone. The collectible marker lives on the bill, so it is displayed and used every round.',
       products='250 Collection (Snapback, PF 2.0 $49.95, Dad Cap, Open Back, Southpaw; $45.95 to $49.95), Hero ball markers (Blue Line, Red Line, Stars & Stripes) $19.95, Breakfast Ball and Pandorg Snapbacks $45.95.',
       awareness='product', stage='3',
       claims=['Patriotic golf gear is everywhere (Pins & Aces "Independence Eagle", "Statue of Liberty" hats)', '"Limited" scarcity is common'],
       open=['The marker you collect, on the hat you wear', 'First-responder pride (Hero markers) is in nobody\'s ads', 'A sturdier patriotic hat: Pins & Aces\' patriotic hats get "flimsy" and "chipping paint" reviews']),
 ],
 'Dartee Golf': [
  dict(key='belts', map='a2b8fcbea42c4262', ref='',
       awareness='solution', stage='4',
       claims=['"No holes / perfect fit every time / micro-adjust" (Nexbelt, Groove, Gator Golf, and our own 256-3 at 1.00x)', 'Hidden or magnetic ball marker in the buckle (Nexbelt flip-open, Groove magnetic, Gator Golf interchangeable)', '"#1 belt in golf" (our own 247 B, $4,762 at 1.07x, one of the worst big spenders)', '"Most comfortable golf belt" / stretch (Groove)', '"Limited quantities, may not restock" (Back9Lab, Nexbelt), generic scarcity', 'Lifetime or near-lifetime guarantees (Groove "94-year", Nexbelt, Dartee "replaced for life")'],
       open=['The whole setup on your hip: marker, tee and glove in one belt; competitors do the marker only', 'Exotic-leather luxury look at a non-luxury price ("equal to that of a Roger Ximenez or Patrick Gibbons without the $3xx-$5xx price point")', 'The compliment moment: "get people asking about my belt", "conversation starters every round"', 'Collecting and rotation: repeat buyers own 3 to 6 belts; nobody frames golf belts as a collection with drops', 'A gift he will actually use, plus the unboxing ("Felt like I was opening a luxury present.")', 'Service from the founder: reviews name Justin and same-day buckle replacements', 'Pace of play, "don\'t be that guy" ("the dreaded mark it with your tee"); tested only briefly (368)']),
  dict(key='creator', map=None, ref='', sort=10,
       name='Creator and limited drops',
       about='To own the belt "your guy" wears, before it is gone: fandom, scarcity and collecting (Josh Kelley, Chazzy), not just function. The full Dartee utility belt plus a creator-designed colorway and collector box, in a limited run.',
       products='Josh Kelley Signature: Low Taper Fade $99.00 (sold out), Up & Down Collection (Josh Kelley + Chazzy, 2 belts in a collector box) $200, Azaleas in August Traditions Collection $119.99, limited colorways (Purple Reign).',
       awareness='most', stage='2',
       claims=['"Limited edition / while supplies last" (Nexbelt America 250, Back9Lab)'],
       open=['"Designed with [creator]", with the creator\'s own reason for each detail', 'Numbered collector box', '"Only X% of our list gets access"', '"Sold out in X", using the real sell-out time of the last drop (unknown, get it from Justin and James)']),
  dict(key='accessories', map=None, ref='', sort=11,
       name='Accessories (markers, hats, glove, tees)',
       about='Make the setup mine and complete the look. Add-ons and bundle builders, bought by people who already own the belt or are adding to a belt order. Markers get swapped to match an outfit or collected.',
       products='Ball markers $9.99 (Azalea Gold set $24.95, Mystery marker), hats $29.99 (7 colorways), Golf Glove $24.95, Dar-Tees $9.99, Traditions DarTees 25-pack $15.00.',
       awareness='most', stage='2',
       claims=['A marker that "sticks to your magnetic buckle" (Groove)', 'Hats and gloves are a commodity category (stage 5 on their own)'],
       open=['"A marker for every belt in your rotation"', 'Mystery-marker drops', 'Markers matched to each collection ("Build a pack" is already on the site)']),
 ],
 'Grunk Dolfer': [
  dict(key='polos', map='gd_line_apparel', ref='P',
       upd=dict(about='The loud, comfy shirt that gets them noticed: be the guy people ask about, even when the golf is bad, in a shirt that fits a real body. Polos are the core; hoodies, tees, button-downs and quarter-zips are bought for the same reason.',
                products='43 golf polos $69.95 (Member Drinko $79.95), sizes S to 5XL, 90% polyester / 10% spandex, stiff collar, relaxed "dadbod approved" fit; hoodies $89.95, tees $49.95, button-downs $69.95, kids polos $39.95.'),
       awareness='solution', stage='4',
       claims=['Bold, loud prints that stand out (Yatta "Boring Polos? Never Heard of \'Em.", Bad Birdie)', '4-way stretch, moisture-wicking, breathable (every brand, Grunk included)', '"The funniest golf polos on the internet" (Bogey Bros)', 'Hidden joke that only shows up close (Bogey Bros "up close you\'ll sssspot the hidden butts!")', 'Partner-permission humor (Bogey Bros "Would you let your man wear this polo?"; our own "negative reviews from Wifes" ad)', 'Fit as the #1 reason (Yatta, on price at $39.95)', 'Review-count social proof (Yatta "6,000+ 5 Star Reviews", Pins & Aces "Voted #1")'],
       open=['Real-body fit, proven: relaxed cut up to 5XL for "rugged sized guys" (P9) and tall torsos (P23); fix sizing consistency first (P34 to P37)', 'Does not fade after 2 years (P20)', 'Course-to-bar and travel: "So easy to pack. No wrinkles." (P41), fine in 99 degree heat (P42)', 'Community and live shopping: Nick on the phone, Whatnot shows, golf-show booths', 'The compliment receipt: "At least a dozen people asked me where i got it." beats generic "turn heads" copy']),
  dict(key='hats', map=None, ref='H', sort=10,
       name='Hats',
       about='Wear the joke (that looks legit from a distance) and get a hat that finally fits and does not sweat-stain. Bought for the joke and the gag-gift moment; rebought because they fit big heads. Often the entry product (free with 2 polos).',
       products='38 hats at $39.95, all snapback: joke hats (Tittees, Donde Esta La Cart Girl, Golf Lessons, The Athlete, Smashters/Masters parody) and Grunk logo / ChunkMan hats; sweat resistant, perforated, "GOLF IS A DRINKING SPORT" lining.',
       awareness='product', stage='3',
       claims=['Joke and parody hats are everywhere (cart girls, Titleist parodies): Titties Golf Co $40, Dayzzed "Where\'s The Cart Girl" $29.99, Bogey Bros hats about $35', '"Funny golf hats" is a crowded search'],
       open=['Function inside the joke: no sweat rings (H14), fits big heads (H13, H22), holds its shape, washes clean', 'Group and team packs with custom embroidery (the H1 friction)']),
  dict(key='accessories', map=None, ref='A', sort=11,
       name='Drinking accessories and gifts',
       about='Keep a beer within reach on the cart without spilling it, and hand out something funny to the crew. On-cart utility and cheap, funny gifts for the foursome.',
       products='Magnetic koozies $9.95, coolers $29.95 to $124.95, growlers $44.95, ball markers $11.95 to $14.95, towels $16.95 to $29.95, headcovers $39.95 to $49.95, divot tools $15.95 to $29.95, Den Caddy $299.95.',
       awareness='problem', stage='2',
       claims=['"Magnetic" koozies are a commodity (Toadfish Sqoozie, Range Brand Golf)', 'Premium headcovers (Pins & Aces "Voted #1 Premium Golf Headcovers & Apparel")'],
       open=['The live proof-of-hold demo ("drove off with it still on the rail and it didn\'t move", A6)', 'Stealth-cooler humor (A13)', 'Fits the long zipper of a cart bag (A14)', 'The group-gift pack for the foursome']),
  dict(key='club', map=None, ref='C', sort=12,
       name='The Drinking Club (membership)',
       about='Be in the club: first crack at drops, the live-show crew, and deal math that makes the habit pay for itself. Bought to belong and to save on buying they would do anyway.',
       products='Drinking Club membership $24.95/month or $299.95/year (Member Polo included): 30% off, free shipping, $10/month credit, private Whatnot shows, member-only drops.',
       awareness='most', stage='2',
       claims=['No golf-apparel competitor in our set runs a paid membership like this (not exhaustively checked)'],
       open=['Almost everything: the "Clerb" language customers already use (C22)', 'The greens-fee price anchor ("Half the price of a single greens fee", C6)', 'The wife-stopped-asking line (C9)', 'Member-only drops']),
 ],
}

# Which competitor a complaint row belongs to (by the row's own source text or Competitor field).
COMP_OF = {
 'Party Patch': {'K1': 'PatchAid', 'K2': 'PatchAid', 'K3': 'PatchAid', 'K4': 'PatchAid', 'K5': 'The Patch Brand', 'K6': 'The Patch Brand',
                 'K7': 'ZBiotics', 'K8': 'ZBiotics', 'K9': 'ZBiotics', 'K12': 'Cheap Amazon', 'K13': 'Vibe'},
 'Dartee Golf': {str(i): ('Groove' if i <= 7 else 'Nexbelt') for i in range(1, 14)},
}
# Competitor quotes that are really our own buyers' failed solutions (no competitor row exists for them).
COMP_TO_VOC = {'Party Patch': {'K10', 'K11'}}
# Competitor quotes that are praise, not complaints (kept on the row as praise).
COMP_PRAISE = {'Party Patch': {'K13'}}
