"""Shared seed writer for a brand's creator link (Ambassadors), 2026-10-06 rebuild.

A brand seed (seed_amb_<slug>.py) builds a SPEC dict and calls write(SPEC, out_path).
The SQL it writes REPLACES the brand's sections and angles and is run ONCE:
  npx wrangler d1 execute mobius-account-health --remote --file migrations/seed_amb_<slug>.sql

What it keeps: the brand row's slug, live flag, submit link, logo and PDF text (only the
fields in SPEC['brand'] are overwritten); the pinned Hot section; and any existing proof
(tagged Meta ads, uploads, posts, inspiration) whose OLD angle title is named in a new
angle's `keep_from`, which is re-pointed at the new angle before the old angles go.
Everything else on the old page is deleted. R2 objects behind deleted uploads are NOT
removed here (delete those angles from the tab first if you care).

Needs LUCIDE_NODES = path to lucide-static@1.46.0/icon-nodes.json (curl it from jsDelivr).
Rules: no sales numbers on the public link, no em dashes, never invent a stat or a claim.
"""
import json, os, secrets

NODES = json.load(open(os.environ['LUCIDE_NODES'], encoding='utf-8'))
OPEN, MID, CLOSE = 'Open · 0 to 3s', 'Middle', 'Close'


def svg(name):
    return ''.join('<%s%s/>' % (t, ''.join(' %s="%s"' % (k, v) for k, v in a.items())) for t, a in NODES[name])


def q(v):
    if v is None:
        return 'NULL'
    if isinstance(v, bool):
        return '1' if v else '0'
    if isinstance(v, (int, float)):
        return str(v)
    return "'" + str(v).replace("'", "''") + "'"


def J(v):
    return q(json.dumps(v, ensure_ascii=False))


rid = lambda: secrets.token_hex(8)


def check(spec):
    """Loud failures beat a half-written page."""
    bad = []
    text = json.dumps(spec, ensure_ascii=False)
    if '—' in text or '–' in text:
        bad.append('em or en dash found')
    keys = [s['key'] for s in spec['sections']]
    if len(keys) != len(set(keys)):
        bad.append('duplicate section keys')
    if len([s for s in spec['sections'] if s.get('enabled', 1)]) > 6:
        bad.append('more than 6 enabled sections (Cole: 5 or 6 max)')
    hot = [a for a in spec['angles'] if a.get('hot')]
    if not 3 <= len(hot) <= 6:
        bad.append('hot angles should be 3 to 6, got %d' % len(hot))
    titles = [a['title'] for a in spec['angles']]
    if len(titles) != len(set(titles)):
        bad.append('duplicate angle titles')
    for a in spec['angles']:
        if a['sec'] not in keys:
            bad.append('angle %r names unknown section %r' % (a['title'], a['sec']))
        for f in ('argument', 'who', 'format', 'visual_hook', 'rehook'):
            if not a.get(f):
                bad.append('angle %r is missing %s' % (a['title'], f))
        if len(a.get('openers') or []) < 3:
            bad.append('angle %r needs 3 openers' % a['title'])
        if len(a.get('shots') or []) < 3:
            bad.append('angle %r needs 3 shots' % a['title'])
        if not (a.get('ads') or a.get('keep_from') or a.get('inspo')):
            bad.append('angle %r has no proof and no inspiration' % a['title'])
    fmts = {a['format'] for a in spec['angles']}
    if len(fmts) > 16:
        bad.append('%d formats; keep it to 16 or the pill row is unusable' % len(fmts))
    if bad:
        raise SystemExit('SPEC problems:\n  ' + '\n  '.join(bad))


def write(spec, out_path):
    check(spec)
    act = spec['act_id']
    b = spec['brand']
    # No BEGIN/COMMIT: D1 refuses SQL transactions, and wrangler runs a --file as one atomic batch anyway.
    out = ['-- Generated by amb_seed_lib.write for %s on the 2026-10-06 rebuild. Run ONCE.' % spec['slug']]

    # 0. A brand with no page yet (Ice & Gold, 2026-10-06): make the row and the pinned Hot
    #    section first, switched OFF, so the rest of the seed is one code path.
    if spec.get('create'):
        out.append("INSERT OR IGNORE INTO p_amb_brand (act_id, slug, live, display_name, submit_platform, submit_label) VALUES (%s, %s, 0, %s, 'TRYBE', 'Film this on TRYBE');"
                   % (q(act), q(spec['slug']), q(b.get('display_name') or spec['slug'])))
        hot0 = next((s for s in spec['sections'] if s.get('pinned')), None) or dict(name='Hot right now', line='What we are pushing hardest this week', icon='flame', color='#C2410C')
        out.append("INSERT INTO p_amb_section (id, act_id, name, line, icon, icon_svg, color, enabled, pinned, sort) "
                   "SELECT %s, %s, %s, %s, %s, %s, %s, 1, 1, 0 WHERE NOT EXISTS (SELECT 1 FROM p_amb_section WHERE act_id=%s AND pinned=1);"
                   % (q(rid()), q(act), q(hot0['name']), q(hot0.get('line')), q(hot0['icon']), q(svg(hot0['icon'])), q(hot0['color']), q(act)))

    # 1. Brand copy. Slug, live, submit link, logo, pdf are untouched unless given.
    cols = []
    for k in ('display_name', 'intro', 'about', 'audience', 'accent', 'logo_url', 'submit_label', 'show_inspo', 'submit_url', 'submit_platform'):
        if k in b:
            cols.append('%s=%s' % (k, q(b[k])))
    for k, col in (('avoid', 'avoid_json'), ('rules', 'rules_json'), ('season', 'season_json'), ('guide', 'guide_json'), ('pdf', 'pdf_json')):
        if k in b:
            cols.append('%s=%s' % (col, J(b[k])))
    cols.append("updated_at=datetime('now')")
    out.append('UPDATE p_amb_brand SET %s WHERE act_id=%s;' % (', '.join(cols), q(act)))

    # 2. Sections. The pinned Hot section is kept as it is (renamed if asked).
    sec_ids = {}
    hot = next((s for s in spec['sections'] if s.get('pinned')), None)
    if hot:
        out.append("UPDATE p_amb_section SET name=%s, line=%s, icon=%s, icon_svg=%s, color=%s WHERE act_id=%s AND pinned=1;"
                   % (q(hot['name']), q(hot.get('line')), q(hot['icon']), q(svg(hot['icon'])), q(hot['color']), q(act)))
    out.append('DELETE FROM p_amb_section WHERE act_id=%s AND pinned=0;' % q(act))
    sort = 1
    for s in spec['sections']:
        if s.get('pinned'):
            continue
        sid = rid()
        sec_ids[s['key']] = sid
        out.append('INSERT INTO p_amb_section (id, act_id, name, line, icon, icon_svg, color, enabled, pinned, sort) VALUES (%s);'
                   % ', '.join(q(x) for x in (sid, act, s['name'], s.get('line'), s['icon'], svg(s['icon']), s['color'], 1 if s.get('enabled', 1) else 0, 0, sort)))
        sort += 1

    # 3. Angles.
    ang_ids = []
    hot_sort = 1
    for i, a in enumerate(spec['angles'], start=1):
        aid = rid()
        ang_ids.append(aid)
        shots = [dict(label=l, text=t) for l, t in a['shots']]
        inspo = [dict(brand=x[0], what=x[1], url=(x[2] if len(x) > 2 else None)) for x in (a.get('inspo') or [])]
        out.append('INSERT INTO p_amb_angle (id, act_id, section_id, hot, hot_sort, sort, status, title, argument, who, products, format, lever, '
                   'openers_json, shots_json, on_screen, do_text, dont_text, trend, visual_hook, rehook, why, inspo_json) VALUES (%s);'
                   % ', '.join([q(aid), q(act), q(sec_ids[a['sec']]), q(1 if a.get('hot') else 0), q(hot_sort if a.get('hot') else 0), q(i),
                                q(a.get('status', 'live')), q(a['title']), q(a['argument']), q(a['who']), q(a.get('products')), q(a['format']),
                                q(a.get('lever')), J(a['openers']), J(shots), q(a.get('on_screen')), q(a.get('do')), q(a.get('dont')),
                                q(a.get('trend')), q(a['visual_hook']), q(a['rehook']), q(a.get('why')), J(inspo)]))
        if a.get('hot'):
            hot_sort += 1
        # Proof that survives from the old page: re-point it before the old angles go.
        for old in (a.get('keep_from') or []):
            out.append('UPDATE p_amb_proof SET angle_id=%s WHERE act_id=%s AND angle_id IN (SELECT id FROM p_amb_angle WHERE act_id=%s AND title=%s);'
                       % (q(aid), q(act), q(act), q(old)))
        # New Meta proof. Only ads the account actually has (the join guards it).
        for k, ad in enumerate(a.get('ads') or [], start=1):
            out.append("INSERT INTO p_amb_proof (id, act_id, angle_id, kind, ad_id, shown, sort) "
                       "SELECT %s, %s, %s, 'meta', %s, 1, %s WHERE EXISTS (SELECT 1 FROM ads WHERE act_id=%s AND ad_id=%s) "
                       "AND NOT EXISTS (SELECT 1 FROM p_amb_proof WHERE angle_id=%s AND ad_id=%s);"
                       % (q(rid()), q(act), q(aid), q(ad), q(k), q(act), q(ad), q(aid), q(ad)))
        for k, (who, what, url) in enumerate(a.get('inspo_links') or [], start=1):
            out.append("INSERT INTO p_amb_proof (id, act_id, angle_id, kind, url, who, note, shown, sort) VALUES (%s);"
                       % ', '.join(q(x) for x in (rid(), act, aid, 'inspo', url, who, what, 1, 100 + k)))

    # 4. Everything old goes.
    keep = ', '.join(q(x) for x in ang_ids)
    out.append('DELETE FROM p_amb_proof WHERE act_id=%s AND angle_id NOT IN (%s);' % (q(act), keep))
    out.append('DELETE FROM p_amb_angle WHERE act_id=%s AND id NOT IN (%s);' % (q(act), keep))
    open(out_path, 'w', encoding='utf-8').write('\n'.join(out) + '\n')
    print('wrote', out_path, ':', len(spec['sections']), 'sections,', len(spec['angles']), 'angles,',
          sum(1 for a in spec['angles'] if a.get('hot')), 'hot')
