"""Dartee Golf creator link, rebuilt 2026-10-06 from docs/research-2026-10-06/dartee.md.

  LUCIDE_NODES=<path>/icon-nodes.json python migrations/seed_amb_dartee.py
  npx wrangler d1 execute mobius-account-health --remote --file migrations/seed_amb_dartee.sql   (ONCE)

Replaces every section and angle on the live Dartee page. Keeps the brand row (slug, live, TRYBE
link, logo, PDF) and re-points the existing tagged Meta ads onto the new angles by old title.
Voice: Dartee is cocky, funny and golf-insider; short lines; a golfer talking to his phone.
Open with Cole: Tire Tracks vs Skid Mark, stretch vs woven, the free glove promo, Black Friday.
"""
import os, sys
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from amb_seed_lib import write, OPEN, MID, CLOSE

ACT = 'act_963898971023823'
HERE = os.path.dirname(os.path.abspath(__file__))

# Drawn season shape from the September seed (0-100 per ISO week, 25 = a normal week).
CUSTOM = {1: 14, 2: 14, 3: 19, 4: 22, 5: 32, 6: 32, 7: 28, 8: 28, 9: 28, 10: 36, 11: 34, 12: 36,
          13: 30, 14: 36, 15: 60, 16: 30, 17: 22, 18: 20, 19: 23, 20: 23, 21: 30, 22: 30, 23: 36,
          24: 42, 25: 40, 26: 26, 27: 24, 28: 26, 29: 26, 30: 25, 31: 25, 32: 26, 33: 28, 34: 32,
          35: 26, 36: 30, 37: 30, 38: 28, 39: 25, 40: 23, 41: 23, 42: 25, 43: 26, 44: 27, 45: 30,
          46: 40, 47: 48, 48: 100, 49: 85, 50: 76, 51: 72, 52: 45, 53: 16}

BRAND = dict(
    display_name='Dartee Golf',
    intro=("Dartee is the belt that holds your marker, your tees and your glove, so your pockets stay empty. "
           "We want videos that look like a real round with your buddies, not a product demo. "
           "Pick one idea, do the first second the way it says, and submit it on TRYBE like always."),
    about=("A golf belt with a magnetic buckle that holds your ball marker, plus a tee holder and a glove holder "
           "that slide anywhere on the strap. Ratchet, no holes, clicks every 1/8 inch. You cut it once and it fits "
           "up to 46 inches. New this fall: the Muni line (The Last Loop, Beach Club, Weekend Warrior, Tire Tracks) at $79.99, "
           "plus 50 Shades of Gator, Bone Dry and Purple Reign. Gator and ostrich belts are embossed leather at $99.99."),
    audience=("Guys who play most weekends and like being the one with the good gear. From November it is also the wives, "
              "girlfriends and kids shopping for the golfer who already has everything."),
    accent='#0F7F73',
    avoid=[
        dict(title='Holding the belt up and naming its features',
             why='Most of what we get. It sells the least of anything we run. Use the belt in a real round instead.'),
        dict(title='A buckle close-up on a table with "a ball marker on the buckle?"',
             why='We have plenty. Show the marker coming off on a real green, with the sound up.'),
        dict(title='Talking to the camera while nothing happens',
             why='Your hands have to be doing something in the first second: cutting, clipping, marking, dropping the old belt.'),
        dict(title='Reading the product page ("premium", "dialed", "flow state")',
             why='Say one thing the belt does and show the rest. Nobody stops scrolling for a spec list.'),
        dict(title='A hat as the star',
             why='Hat videos do not sell for us. The belt is the hero.'),
        dict(title='Score promises and fake transformations',
             why='The fastest way to look like an infomercial. A joke about your handicap is fine. A claim is not.'),
    ],
    rules=[
        'You can say: "the #1 belt in golf", "patented magnetic buckle", "fits any waist up to 46 inches", "clicks every 1/8 inch", "lifetime warranty on the buckle and ratchet", "30-day money-back guarantee".',
        "Don't quote a number of reviews, stars or customers. It never sounds natural in a video.",
        'Gator, croc and ostrich belts are embossed leather. Never say real alligator, crocodile or ostrich.',
        'The Muni belts: say braided. We are confirming whether to say stretch, so leave that word out for now.',
        'The fourth Muni belt is called Tire Tracks on the site today. Use the name the site shows.',
        'Never say the belt makes you play better. A joke that is obviously a joke ("3 strokes minimum") is fine.',
        "Only mention an offer that is live on the site the day you post. Don't quote a free shipping amount.",
        'Cutting the strap: measure with the sizing card first, then cut once.',
        'Show the belt worn in at least one shot, with the marker in the buckle. Film vertical, sound on.',
        'Only film people who agreed to be in your video. If there is alcohol on screen, everyone is 21 or older.',
    ],
    season=dict(
        title='Fall golf, then gift season', until='Nov 23',
        line=("The last good rounds of the year, scrambles and buddy trips, and the new Muni belts. Gift shopping starts "
              "in early November, so film your gift videos NOW so they are live by Nov 1. Black Friday week is the biggest week we have."),
        next='Black Friday and Christmas gifting, from Nov 24',
        highlight=['10-06', '11-23'], show_chart=True, color='#0F7F73', cap=None,
        mode='custom', custom={str(k): v for k, v in CUSTOM.items()},
    ),
    guide=[
        dict(title='Your hands do something in the first second', text='Scissors on the strap, an old belt in the bin, a marker snapping onto the buckle. Then you can talk. Our best ad opens on a box lid coming off with the whole kit visible.'),
        dict(title='Let the belt make its noise', text="The click of the ratchet and the snap of the marker are your hook. Anson's number one ad is a guy saying \"once I put that on I heard the click\". Ours is louder."),
        dict(title='Say the thing people already think', text='"$100 for a golf belt?" and "you definitely don\'t need another belt" were our best creator-style ads. Say the objection out loud, then answer it.'),
        dict(title='Give them one thing to wait for', text='A count that climbs, a buddy who has not noticed yet, a price that comes down. If the viewer is waiting for one beat, they stay. The wife filming "let\'s see how long it takes him to notice" ran 192 days for another brand.'),
        dict(title='Change the picture at 3 seconds', text='Cut to a new place, a new person or a new angle before you have finished your first sentence. Old belt, then "then I found this", then the new one.'),
        dict(title='Use it, do not describe it', text='Mark the ball. Pull a tee. Clip the glove. Two seconds each. If you catch yourself listing features, stop and go do one.'),
        dict(title='Real round, real buddies', text='Film on the course with the group you actually play with. The questions they ask on camera are better than any line we write.'),
        dict(title='End on the belt being worn', text='Pockets turned out, marker on the buckle, walking to the next tee. Then the submit. No wrap-up speech.'),
    ],
)

SECTIONS = [
    dict(key='hot', name='Hot right now', line='The ideas we want most this week. Start here.', icon='flame', color='#DC2626', pinned=1),
    dict(key='muni', name='The Muni', line='Four new braided belts, $79.99, named for the public course. Film by Oct 20.', icon='trees', color='#1D4ED8'),
    dict(key='gift', name='Gifts (film them now)', line='Wives, kids and buddies shopping for the golfer who has everything. Live Nov 1 to Dec 20, so film in October.', icon='gift', color='#15803D'),
    dict(key='holes', name='Holes are stupid', line='Cut once, click every 1/8 inch, and the old belt is the villain.', icon='scissors', color='#BE123C'),
    dict(key='notice', name='The belt people notice', line='Gator, ostrich, new drops, the compliment on the first tee.', icon='gem', color='#0F766E'),
    dict(key='round', name='On the course this fall', line='Scrambles, trips, twilight nines and a real round where the belt does its job.', icon='flag', color='#B45309'),
]


def A(sec, title, fmt, argument, who, visual_hook, rehook, openers, shots, on_screen=None, do=None, dont=None,
      why=None, inspo=(), products='Any Dartee belt', hot=0, ads=(), keep_from=(), lever=None, trend=None):
    return dict(sec=sec, title=title, format=fmt, argument=argument, who=who, visual_hook=visual_hook, rehook=rehook,
                openers=list(openers), shots=list(shots), on_screen=on_screen, do=do, dont=dont, why=why,
                inspo=list(inspo), products=products, hot=hot, ads=list(ads), keep_from=list(keep_from), lever=lever, trend=trend)


ANGLES = [
    # ---------------- The Muni ----------------
    A('muni', 'Four belts, four kinds of golfer', 'Fit check',
      'The Muni line has four belts and each one is named for a kind of golfer. Say the name, show the belt, let them pick.',
      'The public-course regular who buys gear with a story behind it.',
      'Four Muni belts fanned on the hood of the car or the cart seat. One hand slides each one into frame.',
      'Each name gets its one-line story from the site, snap cut per belt. By belt three they are picking theirs.',
      ["Dartee named a belt after the guy whose Saturday tee time is the only appointment he's made on time all week.",
       'Four new belts, four kinds of golfer. Which one are you?',
       "If you can still see the flag you can still play. That's the rule, and that's the belt."],
      [(OPEN, 'The four belts fanned out. Hand slides each into frame as you say the first line.'),
       (MID, 'Put one on at a time, one line each: The Last Loop (first one out, last one in), Weekend Warrior (the Saturday appointment), Beach Club (the one everyone bought first), Tire Tracks (the cart path on 14).'),
       (CLOSE, 'Wearing your pick on the first tee. Ask which one they are.')],
      on_screen='Which Muni are you?', hot=1, products='The Muni: The Last Loop, Beach Club, Weekend Warrior, Tire Tracks',
      why='Anson launched its new line by holding it to the lens and naming each colour; Pins and Aces fit checks name every piece on the course. A named line gives people a reason to film this week.',
      inspo=[('Anson Belt', 'Hold the new line to the lens, name each one, say it just came out.', 'https://app.tryatria.com/ad/m1102646692210777'),
             ('Pins and Aces', 'A fit check on the course where you touch each piece as you name it.', 'https://app.tryatria.com/ad/m2302755733814212')],
      ads=['120246878327530741', '120246878414970741'],
      do='Use the names and stories exactly as the product pages have them.', dont='Call it Skid Mark. The site says Tire Tracks now.'),
    A('muni', 'I bought a belt called Tire Tracks', 'Reaction',
      'The name is the joke and your buddies finish it for you.',
      'Friend groups who give each other grief.',
      'Belt held up to the lens with the name visible on the tag or box. "Tire Tracks."',
      'A buddy asks why. Cut to the cart taking the corner slow and the tyre marks on the path.',
      ['My belt is called Tire Tracks and my group will not let it go.',
       'Guess what this belt is named after.',
       'Dartee named this one after the cart path on 14 and honestly I feel seen.'],
      [(OPEN, 'The belt and the name, held up. One line.'),
       (MID, 'The buddy reaction, one take, no script. Then the cart corner, slow, tyre marks on the path.'),
       (CLOSE, 'The other three names, one line each, then back on the belt.')],
      on_screen='Tire Tracks. Yes, really.', hot=1, products='Tire Tracks (Muni)',
      why='A funny name said three times is a rehook on its own. Groove ran a 15-second ad that just repeats "best belt in the world" and it sits at rank 3.',
      inspo=[('Bogey Bros', 'The "let\'s see how long it takes him to realize" beat, here applied to a buddy reading the name.', 'https://app.tryatria.com/ad/m1859794814679897'),
             ('Groove Life', 'Repeat the funny thing three times and let it carry the video.', 'https://app.tryatria.com/ad/m957958250525755')],
      do='Real reaction. Do not tell the buddy the name first.', dont='Drive fast for the joke.'),
    A('muni', 'Office at 9, nine holes at 5', 'Day in the life',
      'One belt that looks right at the desk and on the first tee the same day.',
      'The guy who plays after work in the same trousers he wore to the office.',
      'Office chair, belt in frame, the time on your phone screen. Cut straight to the car park.',
      'Same belt, three places in ten seconds: desk, car, tee box. The marker comes off only once, on the first green.',
      ['I wore one belt from my 9am to my 5:30 tee time.',
       'Nobody at work knows this belt holds a ball marker.',
       'Office at nine. Nine holes at five. One belt.'],
      [(OPEN, 'At the desk, belt in frame, time on screen. Say the line.'),
       (MID, 'Walk out, bag in the car, first tee, pop the marker off at the first green.'),
       (CLOSE, 'Sunset on the ninth. "Still on."')],
      on_screen='9 to 5, then 9 holes', products='The Muni (any)',
      why='The desk-to-twilight-nine golfer is who the apparel brands say they are dressing in 2026. Nobody has made the belt version.',
      inspo=[('Groove Life', 'Their copy sells "comfortable from desk to dinner". Make it desk to first tee.', 'https://app.tryatria.com/ad/m1009061838517746')],
      do='Show the marker only once, on the green.', dont='Film the office part for more than three seconds.'),
    A('muni', 'A belt you forget you are wearing', 'Swing test',
      'A braided strap moves with the swing. You set it once and stop thinking about it.',
      'Golfers who find a stiff leather belt bulky when they bend and turn.',
      'Slow-motion driver swing from behind, belt dead centre of the frame, no talking yet.',
      'Real speed, three bends in a row: tee it up, read a putt, climb out of a bunker. Count them on screen.',
      ["I didn't notice this belt once in 18 holes, and that's the whole point.",
       'Slow it down and watch the belt. Nothing moves.',
       'A belt that bends when you bend.'],
      [(OPEN, 'The slow-mo swing from behind.'),
       (MID, 'The three bends at real speed, 1, 2, 3 on screen.'),
       (CLOSE, 'The ratchet setting on hole 1 and hole 18. Same click.')],
      on_screen='Set it once. Forgot it by hole 2.', products='The Muni (any)',
      why='Anson\'s creator videos all land on "it fits exactly where it should, every single time". A test you can see beats a claim you have to trust.',
      inspo=[('Anson Belt', 'A creator saying the belt fits the same every time, then proving it.', 'https://app.tryatria.com/ad/m1980515675946741')],
      ads=['120246878414970741'],
      do='Set it to fit, not tight, and leave it.', dont='Say it fixes anything about the swing. And skip the word stretch for now.'),
    A('muni', 'Someone asked which Muni to get', 'Reply to a comment',
      'Beach Club is the one people bought first. Answer the question on camera with one reason per belt.',
      'The guy who has the Muni page open and cannot pick.',
      'A comment on screen: "which Muni should I get?" You hold up Beach Club.',
      '"Real answer:" then one reason per belt, ten seconds, the belt in your hand changing each time.',
      ["Someone asked which Muni to get. Real answer: the one that's already the bestseller.",
       "You asked which one. Here's mine and why.",
       'Beach Club sold first and I think I know why.'],
      [(OPEN, 'The comment on screen, Beach Club held up.'),
       (MID, 'Beach Club on in daylight, the braid up close. The other three in one hand, one reason each.'),
       (CLOSE, '"Cut it once, it fits." Walk off.')],
      on_screen='Which Muni? Real answer:', products='Beach Club (Muni)',
      why='The reply-to-a-comment shape makes it feel like an answer, not an ad. SlideBelts used it for "which colour" and it was their best idea.',
      inspo=[('SlideBelts', '"Someone asked which color to get. Real answer:" as the whole format.', 'https://app.tryatria.com/ad/m1303615761571131')],
      do='Use a real question from your own comments if you have one.', dont='Quote a review count.'),

    # ---------------- Gifts ----------------
    A('gift', "Let's see how long it takes him to notice", 'Reaction',
      'She gives him the belt and the whole video waits for the beat where he finds the marker in the buckle.',
      'Partners who film each other. The golf-widow audience.',
      'Her to camera holding the box, him not in frame yet. "Let\'s see how long it takes him to notice."',
      'He says "nice belt", puts it on, keeps talking, then finds the marker. "Wait a second."',
      ["Y'all, I just bought my husband a golf belt. Let's see how long it takes him to notice what the buckle does.",
       "He thinks it's just a belt.",
       'Golf widow here. I got him something for his Wednesday league.'],
      [(OPEN, 'Her setup line to camera, box in hand.'),
       (MID, 'Hand it over. Hold on his face. Let him talk.'),
       (CLOSE, 'His real line when the marker comes off. Cut there.')],
      on_screen="Let's see how long it takes him", hot=1, products='Any Muni or gator belt, in the box',
      why='The best gift video in golf right now is a wife with a phone doing exactly this for a polo brand: 192 days running, rank 1 of 329 ads. The viewer waits for one beat, so they stay.',
      inspo=[('Bogey Bros', 'The exact format, word for word: "Let\'s see how long it takes him to realize it."', 'https://app.tryatria.com/ad/m1859794814679897')],
      do='One continuous take. The wait is the video.', dont='Tell him beforehand.'),
    A('gift', "The gift he won't buy himself", 'Voiceover',
      'Most golfers never spend a hundred dollars on a belt, which is exactly why it is the gift he wears every round.',
      'Wives, girlfriends, adult kids.',
      'The Dartee box on the kitchen counter, her hands only, lid coming off so the whole kit shows.',
      'His face when the marker comes off the buckle. Then him on the course that weekend.',
      ["He'll never spend a hundred dollars on a belt. So I did.",
       'The golf gift he would never buy himself.',
       'What I got the golfer who has everything.'],
      [(OPEN, 'The box on the counter, lid off, every piece visible.'),
       (MID, 'He opens it. Camera on his face, not the belt.'),
       (CLOSE, 'Him on the course that weekend. "He hasn\'t taken it off."')],
      on_screen="The gift he won't buy himself", products='Gator or ostrich belt in the box',
      why='"A gift you\'ll actually use, not another gadget collecting dust in a drawer" is the line the best belt gift ad runs on. Ours already works as a static.',
      inspo=[('Buckley Belts', 'The gift-you-actually-use line, as a voiceover over the box.', 'https://app.tryatria.com/ad/m1731415471213048')],
      ads=['120232222230200741'], keep_from=["The gift he won't buy himself"],
      do='Keep the camera on his face.', dont='Show the price in the first second. This one is about the reaction.'),
    A('gift', "I don't know his waist size. Didn't matter.", 'Demo',
      'You cannot get the size wrong, because you cut it once. Every relative who bought the wrong glove size will get this.',
      'Gift buyers afraid of sizing.',
      'Her holding the belt next to a pair of his trousers. "I had no idea what size he wears."',
      'The sizing card, the scissors, the cut, the click. Four quick beats.',
      ["I don't know his waist size. Didn't matter.",
       "The only golf gift you can't get the size wrong on.",
       'Someone bought my husband a large glove. He is not a large. This belt fixes that problem.'],
      [(OPEN, 'The belt next to his trousers, the line.'),
       (MID, 'Measure with the card, cut, buckle on.'),
       (CLOSE, 'A few clicks tighter, a few looser. "Up to 46 inches."')],
      on_screen='No size? No problem.',
      why='The number one complaint about golf gifts on the forums is the wrong size. Cut-to-fit answers it in four beats.',
      inspo=[('Anson Belt', 'The creator cutting the belt and saying "cut the belt, reapply the buckle and boom".', 'https://app.tryatria.com/ad/m1622172212779618')],
      do='Measure on camera before cutting.', dont='Say it fits any size. It fits up to 46 inches.'),
    A('gift', 'There is nothing golf related he needs', 'Talking head',
      'He has every club and ball already. The belt is the one thing he uses every round and does not own.',
      'Partners of serious golfers.',
      'Her in his golf closet or the garage, pointing at the pile of gear.',
      '"Then I noticed his belt." Cut to his old belt, holes and all.',
      ['There is nothing golf related he needs. I checked.',
       "He has every club. He has one belt and it's from his wedding.",
       "I'm not buying him another ball retriever and a mug."],
      [(OPEN, 'The gear pile, her pointing.'),
       (MID, 'The old belt, then the Dartee box.'),
       (CLOSE, 'Him wearing it. Pockets empty.')],
      on_screen='He has everything. Except this.',
      why='"There is nothing golf related he needs nor wants" is a real line from a golf wife, and the junk-gift drawer is a real thing. Naming it buys the next ten seconds.',
      inspo=[('Buckley Belts', 'A belt sold as the gift that is not another gadget.', 'https://app.tryatria.com/ad/m1731415471213048')],
      ads=['120232222230200741'],
      do='Be funny about his gear pile.', dont='Make him look dumb. He is the hero.'),
    A('gift', 'Stocking stuffers that clip onto his belt', 'Flat lay',
      'Small gifts under $25 that all attach to the belt he already has.',
      'Buyers who already gave the belt, or want something small.',
      'A stocking on the mantle. A hand pulls out a marker, a tee pack, a glove.',
      'Each one clips onto the belt in a second: marker to buckle, tees to holder, glove to clip.',
      ['Golf stocking stuffers, and they all clip onto his belt.',
       "Three small golf gifts he'll actually use.",
       "Custom markers are the easiest golf gift to get right. Here's why."],
      [(OPEN, 'The stocking, the hand, the three items.'),
       (MID, 'Each item onto the belt, snap, slide, clip.'),
       (CLOSE, 'The loaded belt, worn.')],
      on_screen='Stocking stuffers that stay on the belt', products='Ball markers ($9.99), Dar-Tees, the Dartee glove',
      why='One small product, one job, two seconds each. The Pins and Aces hat ad does exactly that with a magnet and runs on it.',
      inspo=[('Pins and Aces', 'Hold the small thing to the lens, then turn it to show the one job it does.', 'https://app.tryatria.com/ad/m1763143554895344')],
      do='Say each price as it appears.', dont='Make the hat the hero.'),
    A('gift', 'Black Friday, the whole foursome', 'Flat lay',
      'One order covers your dad, your brother and your two buddies, and the site gives you a better price at two and three belts.',
      'The guy who buys for his group.',
      'Four boxes on the table, a name written on each.',
      'One line per name on why that colour. The viewer wants to hear all four.',
      ['Black Friday plan: one belt for everyone in my foursome.',
       'Every golfer on my list. One order.',
       "Dad gets the gator. My brother gets the one named Tire Tracks. Don't ask."],
      [(OPEN, 'The four boxes, the four names.'),
       (MID, 'The four reasons, one belt in hand each time.'),
       (CLOSE, 'Say the Black Friday offer exactly as the site shows it that day.')],
      on_screen='The whole foursome', products='Any belts, 2 or more',
      why='Our two-for-one offer video was the best return in the account in September. The buddy shape works with or without the offer.',
      inspo=[('Buckley Belts', 'Belts sold as a 3-pack for gifting.', 'https://app.tryatria.com/ad/m1731415471213048')],
      ads=['120246488431680741'],
      do='Read the offer off the site on the day.', dont='Invent a discount. The Black Friday offer is not set yet.'),
    A('gift', 'The gift that left the drawer', 'Voiceover',
      'Every novelty golf gift ends up in a drawer. The belt is the one that gets used every round.',
      'Gift buyers burned by joke gifts.',
      'A drawer of unused golf gifts pulled open: ball stamper, novelty headcover, joke book.',
      'Close the drawer. Cut to the belt on the course three weekends in a row, date on screen each time.',
      ['Every golf gift he got last year is in this drawer.',
       "The ball stamper didn't work. The headcover fell off. The joke book wasn't funny.",
       'This is the one golf gift that left the drawer.'],
      [(OPEN, 'The drawer, the junk.'),
       (MID, 'Three weekends, three dates, same belt.'),
       (CLOSE, 'The belt on, pockets empty.')],
      on_screen='The gift that earns bag space',
      why='Golfers on the forums list the worst presents by name: the ball stamper, the emoji headcover, the joke book. Dartee\'s own blog uses "earns bag space".',
      inspo=[('Buckley Belts', '"A gift you\'ll actually use" as the whole pitch.', 'https://app.tryatria.com/ad/m1731415471213048')],
      ads=['120232222230200741'],
      do='Use real junk gifts from your own house.', dont="Name another brand's product."),

    # ---------------- Holes are stupid ----------------
    A('holes', "Belt companies think we're idiots", 'Talking head',
      'Holes are a bad system everybody accepted. The ratchet fixes it, and the buckle holds your marker on top.',
      'Anyone wearing an old leather belt on the course.',
      'You, to camera, holding up an old belt with a row of stretched or homemade holes.',
      '"Then I found this." Hard cut to the Dartee: click, click, click, marker snaps on.',
      ["Belt companies think we're idiots. Here's a few holes, good luck.",
       'One hole too tight, one hole too loose. How did we all agree to this?',
       'I punched a new hole in my belt in a car park once. Never again.'],
      [(OPEN, 'The old belt held up, the holes to the lens, the rant starts.'),
       (MID, 'The cut to the Dartee. Three clicks. The marker snap.'),
       (CLOSE, '"None of this is revolutionary. It\'s how a golf belt should have worked."')],
      on_screen="Here's a few holes. Good luck.", hot=1,
      why='Anson relaunched its whole account in September and the creator rants about holes are its best new format. The "then I found this" cut is the beat that holds people.',
      inspo=[('Anson Belt', 'The whole shape: the rant, the holes, "then I found this".', 'https://app.tryatria.com/ad/m1980515675946741'),
             ('Anson Belt', '"Holes in my belt get all stretched out and the whole thing starts looking like a sloppy mess."', 'https://app.tryatria.com/ad/m1730602779068185')],
      ads=['120238662506390741'], keep_from=['Ditch the dad belt'],
      do='One take, no music. Keep it a rant.', dont="Copy Anson's lines word for word. Keep the beat, change the words."),
    A('holes', "No, I didn't just ruin a hundred-dollar belt", 'Demo',
      'You cut the strap once and the ratchet covers every eighth of an inch after that, so the belt changes with you.',
      'Guys whose weight goes up and down.',
      'Scissors on the strap, mid-cut, before anyone talks.',
      '"No, I didn\'t just ruin it." Then the sizing card, the buckle, the clicks.',
      ["No, I didn't just ruin a hundred-dollar belt.",
       'I lost 20 pounds and my belt had four homemade holes. Not this one.',
       "Measure, cut once, click. Just don't put the weight back on."],
      [(OPEN, 'The cut.'),
       (MID, 'The card, the buckle going on, the clicks.'),
       (CLOSE, 'The joke line, deadpan.')],
      on_screen='Cut once. Clicks every 1/8 inch.',
      why='A cold open on scissors is a pattern interrupt that costs nothing, and the weight joke is the rehook Anson\'s creator closes on.',
      inspo=[('Anson Belt', 'The weight-loss story and the joke: "just make sure you don\'t put the weight back on".', 'https://app.tryatria.com/ad/m1622172212779618')],
      do='Measure with the card on camera.', dont='Cut without measuring. And do not promise a free replacement if it is cut too short.'),
    A('holes', 'Same belt since 8th grade', 'Side by side',
      'Talk to the guy who has never once thought about his belt.',
      'The golfer whose belt came with his first suit.',
      'Close-up of a cracked, curled old belt tip. Tilt up to your face.',
      'Side by side at the hip: old belt left, Dartee right, with the checklist ticking on screen.',
      ["You've been wearing the same belt since 8th grade. On the golf course.",
       "If your belt only holds up your pants, it's doing one job. This one does four.",
       'Your belt came with your prom suit. Admit it.'],
      [(OPEN, 'The old belt tip, up to your face.'),
       (MID, 'The checklist: holds pants, marker, tees, glove, no holes.'),
       (CLOSE, 'Old belt in the drawer.')],
      on_screen='Your belt vs a golf belt',
      why='Naming the viewer ("you\'ve been wearing the same belt since 8th grade") works better than naming the product. Groove runs it in ten seconds.',
      inspo=[('Groove Life', '"Guys you\'ve been wearing the same belt since 8th grade."', 'https://app.tryatria.com/ad/m1009061838517746')],
      ads=['120237391091280741'], keep_from=['Your belt only holds up your pants'],
      do='Use your actual old belt.', dont='Explain the magnet. Show it.'),
    A('holes', "You definitely don't need another belt", 'Pattern interrupt',
      'You do not need more belts. You need one that does the job on the course.',
      'Guys with a drawer of belts.',
      'Do something surprising with the old belt in the first second: bin, lake, hand it to the dog. Ours used a toilet.',
      '"You don\'t need another belt. You need a better one." Cut to the Dartee on, marker off the buckle on a green.',
      ["You definitely don't need another belt.",
       'I own eleven belts. Zero of them are golf belts.',
       'This is what I think of my old golf belt.'],
      [(OPEN, 'The stunt with the old belt.'),
       (MID, 'The Dartee on, marker off the buckle on a real green.'),
       (CLOSE, 'Pockets turned out, empty.')],
      on_screen='Pockets optional.',
      why='Nobody else in the belt category does a physical pattern interrupt. Ours still runs at 2.7x a year on.',
      ads=['120240009827450741', '120240009817870741'], keep_from=["You don't need another belt, you need a better one"],
      do='Find your own stunt.', dont='Reuse the toilet.'),

    # ---------------- The belt people notice ----------------
    A('notice', '$100 for a golf belt?', 'Price reveal',
      'Say the price first, then open the box and count what you get.',
      'Guys who think a belt should cost twenty bucks.',
      'Text on screen "$100 for a golf belt?" over a closed box. Your eyebrows up.',
      'Box opened flat, every piece named in one breath: belt, buckle, marker, tee holder, glove holder, sizing card.',
      ['A hundred dollars for a golf belt? Hear me out.',
       "I wasn't ready to pay this for a belt. Then I opened it.",
       'My wife asked why I spent a hundred bucks on a belt. This is the answer.'],
      [(OPEN, 'The price on screen, the closed box.'),
       (MID, 'The box flat, the one-breath count.'),
       (CLOSE, 'Worn on the course. "Now it makes sense."')],
      on_screen='$100 for a golf belt?', products='Gator or ostrich belt ($99.99)',
      why='Our best cost-per-sale ad ever says the price objection out loud first. The TikTok Shop creators do the same with bags: "I really wasn\'t ready to pay that kind of money".',
      inspo=[('Pins and Aces', 'The creator who says the price first, then why it was worth it.', 'https://app.tryatria.com/ad/m1067339445915203')],
      ads=['120239237680840741', '120237392010370741'], keep_from=['$100 for a golf belt?', 'The whole kit in one second'],
      do='Say the real price of the belt in your hand.', dont='Skip the box. The count is the proof.'),
    A('notice', '50 Shades of Gator, in daylight', 'Texture reveal',
      'New embossed colours just dropped. The texture is the hook and the name is the rehook.',
      'The drop collector.',
      'Slow push into the embossed scales in sunlight. No face yet.',
      'Pull back, say the name, say "embossed", say it just came out.',
      ["This one's called 50 Shades of Gator and I'm not explaining the name.",
       'New gator just dropped. Look at it in the sun.',
       'Bone Dry. New. Already on my belt.'],
      [(OPEN, 'The texture, tight, in the sun.'),
       (MID, 'The name, the box, the matching marker.'),
       (CLOSE, 'On the first tee. Someone notices.')],
      on_screen='New: 50 Shades of Gator', products='50 Shades of Gator, Bone Dry, Purple Reign (new)',
      why='Anson launched its ostrich line by holding it to the lens in daylight and naming it. Texture is a visual hook on its own.',
      inspo=[('Anson Belt', 'The founder holds the new embossed line to the lens, names the colour, says it just came out.', 'https://app.tryatria.com/ad/m1102646692210777')],
      ads=['120246116810010741', '120245845649450741'], keep_from=['Compliments before the first tee', 'The drop you missed last time'],
      do='Film texture outdoors.', dont='Say real alligator, crocodile or ostrich. It is embossed leather.'),
    A('notice', 'White belt. Guess my handicap.', 'Fit check',
      'Fashion people say the white belt is over, which is exactly why the joke still lands.',
      'Guys who get the white-belt handicap joke.',
      'Tilt up from white shoes to a white belt on the first tee.',
      'A buddy hands over a bill before the round. Then your real handicap on screen.',
      ["The fashion guys say the white belt's best days are behind it. My handicap agrees.",
       'White belt. Guess my handicap.',
       'When I wear the white belt my buddies just hand me the money.'],
      [(OPEN, 'The tilt, shoes to belt.'),
       (MID, 'The reaction, the bill.'),
       (CLOSE, 'The real number.')],
      on_screen='White belt. Guess my handicap.', products='Storm Trooper White, Albino Gator',
      why='Self-deprecation disarms the ad read. "Shoot a hundred and still get compliments" is the line Pins and Aces runs on.',
      inspo=[('Pins and Aces', '"Name a golf brand where you can shoot a hundred and still get compliments."', 'https://app.tryatria.com/ad/m2302755733814212')],
      do='Let the joke land on you.', dont='Say the belt helps your score.'),
    A('notice', 'Counting how many times my group asks about my belt', 'Running count',
      'Wear it one round and count how many times the group asks where you got it.',
      'The guy who likes being the one with the good gear.',
      'Hole 1, a buddy points at the belt. A big "1" lands on screen.',
      'The count climbs with each cut. The viewer waits for the final number.',
      ['Counting how many times my group asks about my belt today.',
       'I got asked about this belt four times in one round.',
       "Your buddies are going to ask. Here's proof."],
      [(OPEN, 'The first point, the 1 on screen.'),
       (MID, 'Marker off the buckle, glove clip, tee from the holder, each with a new ask and a new number.'),
       (CLOSE, 'The final count. "They always want to know where."')],
      on_screen='Times asked about my belt: 4', products='Gator, ostrich, any',
      why='A number that climbs is the simplest retention device there is. The compliment is also the thing our reviews say most.',
      inspo=[('Pins and Aces', 'Compliments as the pitch, said by a creator who admits he is not good.', 'https://app.tryatria.com/ad/m2302755733814212')],
      ads=['120245960128970741', '120246116810010741'],
      do='Let the real questions happen.', dont='Script the buddies. It shows.'),
    A('notice', "Did I mention it's the #1 belt in golf", 'Skit',
      'Say the claim, then make fun of saying it, so it never sounds like an ad.',
      'Golfers allergic to ad reads.',
      'You, deadpan to camera on the cart: "Did I mention this is the number one belt in golf?"',
      'You say it again on the green, again at the bar. Each time the marker or a tee is doing something.',
      ['Did I mention this is the number one belt in golf?',
       "It's the number one belt in golf. I'm going to keep saying it.",
       "The number one belt in golf. Sorry. I can't stop."],
      [(OPEN, 'The cart, the deadpan line.'),
       (MID, 'Three repeats, three uses of the belt.'),
       (CLOSE, '"Fine, I\'ll stop." Then one more.')],
      on_screen='#1 belt in golf (again)',
      why='Groove runs a 15-second ad that repeats "best belt in the world" three times and mocks itself for it. It sits at rank 3 of 72.',
      inspo=[('Groove Life', '"Did I mention the groove belt is the best belt in the world? I can\'t stop doing this."', 'https://app.tryatria.com/ad/m957958250525755')],
      ads=['120239960847110741'],
      do='Keep it under 20 seconds.', dont='Add a review count or a star rating.'),

    # ---------------- On the course this fall ----------------
    A('round', '18 holes. Not touching my pockets once.', 'On-course POV',
      'The video the category does not have: a real round, start to finish, the belt doing its three jobs without anyone explaining them.',
      'Anyone seeing Dartee for the first time.',
      'Hole 1 tee box. Set the ratchet, show the marker in the buckle. No words yet.',
      'An on-screen counter: holes played, times the pocket was touched (zero). It ticks all round.',
      ["18 holes. I'm not touching my pockets once.",
       "I'm going to play a full round and never explain this belt.",
       'Watch the belt, not me.'],
      [(OPEN, 'Hole 1, the setting, the marker.'),
       (MID, 'Marker off and on, tee from the holder, glove clipped after a shot, a bunker, a crouch to read a putt.'),
       (CLOSE, 'Hole 18, same ratchet setting, marker still there.')],
      on_screen='Hole 1 / Hole 18. Pockets touched: 0', hot=1,
      why='Sunday Golf\'s plain first-outing video has run for a year. Nobody has made the belt version. The slot is open.',
      inspo=[('Sunday Golf', 'A plain "first time out with it" video that never stopped running.', 'https://app.tryatria.com/ad/m1432948334462951')],
      ads=['120237392010370741', '120246517338760741'],
      do='Real swings, real greens. Set it to fit, not tight.', dont='Over-tighten it. That is how it slips.'),
    A('round', 'Four balls, one marker. Mine.', 'On-course POV',
      'In a scramble every ball gets marked and you are the one with a marker ready while everybody else pats pockets.',
      'The charity-outing and member-guest regular.',
      'Four balls on the green. Three guys patting their pockets.',
      'Marker off the buckle, mark, snap back. Then again for the next ball, faster.',
      ['Scramble rule: always putt after the guy with the Dartee belt.',
       'Four balls, one marker. Mine.',
       'Watch what happens when four guys need a marker at once.'],
      [(OPEN, 'The green, the four balls, the patting.'),
       (MID, 'The two marks, snap and snap.'),
       (CLOSE, 'Team photo with the flag.')],
      on_screen='The guy with the marker is the MVP',
      why='The hand on each piece as it is used, not described, is the shape the best WITB creators use.',
      inspo=[('Pins and Aces', 'Hand on each feature as it is used.', 'https://app.tryatria.com/ad/m1651267819953460')],
      ads=['120242460444050741', '120245501801680741'], keep_from=['Never borrow a marker again'],
      do='Film a real outing. The carts lined up sell it.', dont='Explain the magnet. Let it snap.'),
    A('round', 'Stop asking your buddy for a marker', 'On-course POV',
      'The marker lives on the buckle so you never dig for it while the group waits.',
      'Golfers who dig for a marker every green.',
      'Eye-line POV on the green. Your hand goes to the buckle, not the pocket.',
      'Mark, putt, snap it back, all in one shot with the sound up.',
      ['Stop asking your buddy for a ball marker.',
       'Mark, putt, snap it back. Done.',
       "Standing in my buddy's line digging for a marker. Not anymore."],
      [(OPEN, 'The POV, hand to the buckle.'),
       (MID, 'The mark and the putt.'),
       (CLOSE, 'Snap, walk off.')],
      on_screen='Marker on the buckle',
      why='Anson\'s number one ad opens on the click. The marker snap is Dartee\'s version and it is louder.',
      inspo=[('Anson Belt', 'The click as the hook: "once I put that on I heard the click".', 'https://app.tryatria.com/ad/m2028969921084508')],
      ads=['120242460444050741'],
      do='Film on a real green from your eye line.', dont='Film the buckle on a table. We have those.'),
    A('round', 'Where does your glove go between shots?', 'Side by side',
      'Gloves fall out of back pockets and get left in carts. On the belt it stays put and dries out.',
      'Anyone who has lost a glove mid-round.',
      'A glove flops out of your back pocket as you walk off the green and lands on the fringe.',
      'Same walk, glove clipped on the belt, nothing falls. Then the forum line on screen.',
      ["My glove used to live in my back pocket. Here's where it lives now.",
       'I lost two gloves in one round. Never again.',
       'Where does your glove go between shots?'],
      [(OPEN, 'The drop.'),
       (MID, 'Glove off after a shot, clipped on in one move.'),
       (CLOSE, 'Hole 18, still there.')],
      on_screen='"It\'s always one thing." / Back pocket vs belt',
      why='"I\'ll realize that my glove is still in my back pocket. It\'s always one thing." is a real golfer\'s line. Show it, then fix it.',
      inspo=[('Pins and Aces', 'Turn the product to show the magnet doing its job.', 'https://app.tryatria.com/ad/m1763143554895344')],
      do='Use a real lost glove if you have one.', dont='Over-explain the clip.'),
    A('round', "If you keep tees in your front pocket, you've been stabbed today", 'Skit',
      'Tees in a pocket jab you all day. Tees on the belt never do.',
      'Every golfer who keeps tees in a front pocket.',
      'Hand into the pocket, a big flinch, out comes a broken tee.',
      'Empty the pocket onto the cart seat: tees, a coin, lint, a pencil. Then the holder with two tees.',
      ["If you keep tees in your front pocket, you've been stabbed by one today.",
       "Aren't you worried it'll puncture your valuables?",
       'Stabbed by a tee for the last time.'],
      [(OPEN, 'The flinch.'),
       (MID, 'The pocket dump.'),
       (CLOSE, 'Tee out of the holder without looking, next box.')],
      on_screen='Tees go on the belt',
      why='The flinch is a visual hook with no product in it, and the pocket dump is a reveal. Both are things people have done.',
      inspo=[('Anson Belt', 'A pain said in plain words first, the product second.', 'https://app.tryatria.com/ad/m1980515675946741')],
      do='Make the flinch real.', dont='Turn it into a feature list afterwards.'),
    A('round', 'Packing for four rounds. One belt.', 'Flat lay',
      'On a trip you pack four outfits and one belt, because it holds the marker, tees and glove for every round.',
      'The buddy-trip organiser.',
      'Suitcase open on the bed, four outfits stacked, the belt dropped on top last.',
      'Load the belt on camera: marker in, two tees in the holder, glove clipped. Everything else into the bag.',
      ['Packing for four rounds in three days. One belt.',
       'The one thing I pack first for a golf trip.',
       "Four outfits, one belt, and I'm not touching my pockets all weekend."],
      [(OPEN, 'The suitcase, the stack, the belt on top.'),
       (MID, 'The load.'),
       (CLOSE, 'First tee at the destination, course name on screen.')],
      on_screen='4 rounds. 1 belt.',
      why='A packing video is a flat lay with a reason, and the load is a demo nobody has to explain.',
      inspo=[('Sunday Golf', 'One product, one real trip, said plainly.', 'https://app.tryatria.com/ad/m1432948334462951')],
      do='Show the tee sheet or the course sign.', dont='Mention a free-shipping amount.'),
    A('round', 'If you can still see the flag, you can still play', 'Day in the life',
      'The last nine of the year, named for the belt, filmed at sunset.',
      'Twilight-rate golfers squeezing in the last good weeks.',
      'Low sun, long shadows, walking off the cart with the belt in frame.',
      '"If you can still see the flag, you can still play." said on the 7th tee as it gets dark.',
      ['If you can still see the flag, you can still play. Those are the rules.',
       'Last loop of the year. Wearing the belt named for it.',
       'First one out, last one in.'],
      [(OPEN, 'Sunset, the walk off the cart.'),
       (MID, 'Marker off on a dark green, phone torch on the ball.'),
       (CLOSE, 'The clubhouse lights.')],
      on_screen='The Last Loop', products='The Last Loop (Muni)',
      why='The belt has a name and a story on its own product page. Reading it on the 7th tee at dusk is the whole video.',
      inspo=[('Sunday Golf', 'One product, one outing, no spec list, 576 days.', 'https://app.tryatria.com/ad/m581226258294725')],
      do="Use the belt's own name story from the product page.", dont='Add a spec list over the sunset.'),
    A('round', 'Gave my buddy this belt on the first tee. Told him nothing.', 'Reaction',
      'Hand a Dartee to a buddy with no explanation and film him working it out.',
      'Buddies or a starter who has never seen one.',
      'A belt handed over on the tee. He turns it over in his hands.',
      'The moment he finds the marker in the buckle. "Oh, that\'s actually smart."',
      ['Gave my buddy this belt on the first tee. Told him nothing.',
       "First time he's seen it. No script.",
       "Let's see how long it takes him to find the marker."],
      [(OPEN, 'The handoff.'),
       (MID, 'Him finding the marker, then the holders.'),
       (CLOSE, 'His verdict after one hole.')],
      on_screen='First time wearing it',
      why='The wait for the realisation is the same beat as the wife gift video, with a buddy. Unscripted reactions are the one thing that never reads as an ad.',
      inspo=[('Bogey Bros', 'The wait for "Wait a second."', 'https://app.tryatria.com/ad/m1859794814679897')],
      do='Let him talk.', dont='Feed him lines.'),
    A('round', "What's on my belt", 'On-course POV',
      'What\'s in the bag, moved to the belt: one piece at a time, each one used, not described.',
      'Golfers who watch WITB videos.',
      'Tight on the hip. "What\'s on my belt." Hand touches the buckle.',
      'Each piece gets two seconds and one use: marker (mark), tees (tee up), glove (clip), ratchet (click).',
      ["Forget what's in the bag. What's on my belt.",
       'Everything I need for 18 holes is on my hip.',
       "I might suck at golf but my belt doesn't."],
      [(OPEN, 'Hip height, the line, the hand on the buckle.'),
       (MID, 'The four uses, two seconds each.'),
       (CLOSE, 'Pull out to the full fit on the tee.')],
      on_screen="What's on my belt",
      why='The WITB creator at Pins and Aces opens with "i might suck at golf but this bag doesn\'t" and touches each pocket. Same shape, smaller product.',
      inspo=[('Pins and Aces', 'Hand on each feature, self-deprecating opener.', 'https://app.tryatria.com/ad/m1651267819953460')],
      ads=['120246517338760741'],
      do='Name it, use it, move on.', dont='Read the product page.'),
]

SPEC = dict(act_id=ACT, slug='dartee', brand=BRAND, sections=SECTIONS, angles=ANGLES)

if __name__ == '__main__':
    write(SPEC, os.path.join(HERE, 'seed_amb_dartee.sql'))
