"""One-time seed: Dartee Golf's creator link (Ambassadors), 2026-09-17.

Writes seed_dartee.sql, which is run ONCE against the shared D1:
  npx wrangler d1 execute mobius-account-health --remote --file migrations/seed_dartee.sql
Needs LUCIDE_NODES = path to lucide-static@1.46.0/icon-nodes.json.
Sources: docs/angles-dartee.md (darteegolf.com and its reviews, our Meta ads since May 2026,
competitor ads in Atria and the Meta library, r/golf and The Sand Trap, the season shape from
tw_daily) and Cole's calls on 2026-09-17 (BOGO has ended, "#1 belt in golf" and "patented buckle"
are fine, no review count on camera, Muni leads Hot right now).
The link is seeded OFF (live = 0) for Cole's review. It replaces a blank row made on the tab
the same day (slug dartee-golf, 2 default sections, no angles); its TRYBE link is kept.
Re-running it replaces Dartee's sections, angles and proof, so do not run it
again once the team has edited the page.
"""
import json, os, secrets

ACT = 'act_963898971023823'
HERE = os.path.dirname(os.path.abspath(__file__))
NODES = json.load(open(os.environ['LUCIDE_NODES'], encoding='utf-8'))

def svg(name):
    return ''.join('<%s%s/>' % (t, ''.join(' %s="%s"' % (k, v) for k, v in a.items())) for t, a in NODES[name])

def q(v):
    if v is None:
        return 'NULL'
    if isinstance(v, (int, float)):
        return str(v)
    return "'" + str(v).replace("'", "''") + "'"

rid = lambda: secrets.token_hex(8)
OPEN, MID, CLOSE = 'Open · 0 to 3s', 'Middle', 'Close'

# Drawn season shape, 0-100 per ISO week (25 = a normal week). Real sales were not used:
# Black Friday week ran about 6x a normal week and flattens everything else, and fall 2025
# was before the account scaled, with a stock dip in September. Shape from tw_daily netSales,
# Jun 2025 to Sep 2026: Masters week 2.4x, Father's Day weeks 1.5x to 1.7x, December about 3x.
CUSTOM = {1: 14, 2: 14, 3: 19, 4: 22, 5: 32, 6: 32, 7: 28, 8: 28, 9: 28, 10: 36, 11: 34, 12: 36,
          13: 30, 14: 36, 15: 60, 16: 30, 17: 22, 18: 20, 19: 23, 20: 23, 21: 30, 22: 30, 23: 36,
          24: 42, 25: 40, 26: 26, 27: 24, 28: 26, 29: 26, 30: 25, 31: 25, 32: 26, 33: 28, 34: 32,
          35: 26, 36: 30, 37: 30, 38: 28, 39: 25, 40: 23, 41: 23, 42: 25, 43: 26, 44: 27, 45: 30,
          46: 40, 47: 48, 48: 100, 49: 85, 50: 76, 51: 72, 52: 45, 53: 16}

brand = dict(
    slug='dartee', live=0, display_name='Dartee Golf', accent='#0E7C5A', logo_url=None,
    intro=("Dartee makes the golf belt that holds your ball marker, tees and glove, so your pockets stay empty. "
           "We want videos that look like a real round with your buddies: the first tee, the green, the cart, the 19th hole. "
           "Pick an idea below, film it your way, and submit it on TRYBE like always."),
    about=("A leather or woven golf belt with a patented magnetic buckle that holds your ball marker, "
           "detachable tee and glove holders, and a ratchet that adjusts every 1/8 inch. You cut it once and it fits "
           "any waist up to 46 inches. New this fall: the Muni collection, four woven belts. Also gator, ostrich, "
           "braided and Rain Check belts, plus markers, tees and gloves."),
    audience=("Guys who play most weekends and want to look the part: they care about their gear, their fit and "
              "what their buddies notice on the first tee. From November we also talk to the wives, girlfriends "
              "and kids shopping for the golfer who has everything."),
    submit_platform='TRYBE',
    # Already set on the tab before this seed (2026-09-17); kept.
    submit_url='https://jointrybe.com/creator/brands/f0afb846-3df4-44ac-b53e-80158e90b793', submit_label='Film this on TRYBE',
    avoid=[
        dict(title='Holding the belt up to the camera and naming its features',
             why='Most of what we get looks like this, in a store, a yard or a kitchen, and it sells the least of anything we run. Take us onto the course instead.'),
        dict(title='A buckle close-up with "a ball marker on the buckle?" and nothing else',
             why='We have plenty. Show the marker coming off the buckle on a real green.'),
        dict(title='Unboxing on a desk with no reason',
             why='An unboxing only works when every piece of the kit shows in the first second, or when it is a gift.'),
        dict(title='Dark, moody close-ups of the buckle',
             why='Our studio already makes these. We need real rounds, real buddies and real reactions from you.'),
        dict(title='Reading the product page ("premium materials", "dialed", "flow state")',
             why='Say one thing the belt does and show the rest. Nobody stops scrolling for a spec list.'),
        dict(title='A hat as the star of the video',
             why='Hat videos do not sell for us. Keep the belt the hero.'),
    ],
    rules=[
        'You can say: "the #1 belt in golf", "patented magnetic buckle", "fits any waist up to 46 inches", "adjusts every 1/8 inch", "lifetime warranty on the buckle and ratchet", "30-day money-back guarantee".',
        'Don\'t quote a number of reviews, stars or customers, or anything like "one sold every 42 seconds".',
        'Gator, croc and ostrich belts are textured leather. Never say real alligator, crocodile or ostrich skin.',
        'Never say the belt makes you play better. A joke that is obviously a joke ("3 strokes minimum") is fine.',
        'The woven Muni belts: say woven, not stretch (only Beach Club says stretch weave).',
        "Only mention an offer that is live on the site the day you post. Don't quote a free shipping amount.",
        'Show the belt worn in at least one shot, with a marker in the buckle.',
        'Cutting the strap: measure with the sizing card first. A strap cut too short is not covered by the warranty.',
        'Film vertical, sound on, and show the belt or the course in the first two seconds.',
        'Only film people who agreed to be in your video, on a course that allows filming. If there is alcohol on screen, everyone is 21 or older.',
    ],
    season=dict(
        title='Fall golf and gift season', until='Nov 23',
        line=("Buddy trips, scrambles and the last good rounds of the year, and gift shopping starts in early November. "
              "We are pushing the new Muni woven belts right now. Film your gift videos this month so they are ready "
              "for Black Friday."),
        next='Black Friday and Christmas gifting, from Nov 24',
        highlight=['09-15', '11-23'], show_chart=True, color='#0E7C5A', cap=None,
        mode='custom', custom={str(k): v for k, v in CUSTOM.items()},
    ),
    pdf=dict(
        line1='Dartee creators,',
        line2="here's what to film.",
        intro=("Our creator hub has every idea we want right now: this week's hot picks, the new Muni belts, "
               "gift season, openers you can say word for word, and real videos that worked. "
               "It updates on its own, so check it before you shoot."),
        cta='Your creator hub',
        note='Opens right on your phone. No login, no app.',
        steps=['Open the hub and pick an idea',
               'Film it on the course, starting with the opener',
               "Submit on TRYBE with the idea's name"],
    ),
    show_inspo=1,
)

SECTIONS = [
    dict(key='hot', name='Hot right now', line='What we are pushing hardest this week', icon='flame', color='#DC2626', pinned=1),
    dict(key='muni', name='The Muni', line='Four new woven belts, $79.99, named for the public course.', icon='trees', color='#1D4ED8'),
    dict(key='fall', name='Fall golf and buddy trips', line='Trips, scrambles and the last good rounds of the year. Until Nov 23.', icon='leaf', color='#B45309'),
    dict(key='gift', name='Gifts and Black Friday', line='Wives, kids and buddies shopping for the golfer who has everything. Nov 1 to Dec 20.', icon='gift', color='#15803D'),
    dict(key='util', name='The utility belt', line='Marker, tees and glove, used in a real round.', icon='magnet', color='#7C3AED'),
    dict(key='look', name='Look the part', line='Gator, ostrich, white belts and limited drops. The belt people notice.', icon='gem', color='#0F766E'),
    dict(key='ditch', name='Ditch the old belt', line='Holes, bad fit and a belt that only holds up your pants.', icon='scissors', color='#BE123C'),
    dict(key='ev', name='Always works', line='Ideas that sell any month of the year.', icon='sparkles', color='#334155'),
    dict(key='spring', name="Masters to Father's Day", line="Masters week and Father's Day, our two spring peaks. Switch on in March.", icon='flag', color='#166534', enabled=0),
]

def A(sec, title, fmt, argument, who, openers, shots, on_screen=None, do=None, dont=None, lever=None,
      products='Any Dartee belt', hot=0, trend=None, ads=()):
    return dict(sec=sec, title=title, format=fmt, argument=argument, who=who, openers=openers,
                shots=[dict(label=l, text=t) for l, t in shots], on_screen=on_screen, do=do, dont=dont,
                lever=lever, products=products, hot=hot, trend=trend, ads=list(ads))

MUNI = 'Muni belts (The Last Loop, Beach Club, Weekend Warrior, Skid Mark)'

ANGLES = [
    # ---------------- The Muni (new, all hot) ----------------
    A('muni', 'Built for the muni', 'On-course POV',
      "You don't need a country club membership to look like you have one. The Muni is the $79.99 belt built for the public course.",
      'The public course regular who plays twilight nines and still wants to look sharp.',
      ["You don't need a membership to look like you have one.",
       'Muni golfer, country club belt.',
       'The last nine before dark, and I still look better than the guys at the club.'],
      [(OPEN, 'Walking off the cart at a public course, the clubhouse or starter hut behind you. Tilt down to the woven belt.'),
       (MID, 'Play a few holes: pop the marker off the buckle on the green, grab a tee from the holder on the next box.'),
       (CLOSE, 'Sunset on the last hole. Say which Muni you are wearing and that it is $79.99.')],
      on_screen='Muni golfer. Country club belt.',
      do='Film at a real public course. Say the belt name (The Last Loop is named for the last nine before dark).',
      dont='Make fun of country clubs or anyone at one. We are proud of the muni, not bitter.',
      lever='Identity', products=MUNI, hot=1),
    A('muni', 'The belt that swings with you', 'Test',
      "A light woven strap you forget you are wearing, so all you feel is the swing.",
      'Golfers who find a thick leather belt stiff or bulky in the swing.',
      ["I didn't realize how much my old belt bugged me until I swung in this one.",
       'Slow motion. Watch the belt. Nothing moves.',
       'A golf belt you forget you have on.'],
      [(OPEN, 'Slow-motion driver swing from the side, belt and buckle in frame.'),
       (MID, 'Real speed: bend to tee up, crouch to read a putt, climb out of a bunker. The belt stays put.'),
       (CLOSE, 'Close-up of the woven strap and buckle, then you walking off the tee.')],
      on_screen='18 holes. Never touched it.',
      do='Crouch and read a putt on camera. That is where a bad belt shows.',
      dont='Call the belt stretchy unless you are wearing Beach Club. Say woven.',
      lever='Relief', products=MUNI, hot=1),
    A('muni', 'One Muni for every polo', 'Transition',
      'Four woven colours cover every golf outfit you own, so you never think about the belt again.',
      'The guy who plans his golf fit the night before.',
      ['Four polos, four Muni belts. Which is the best fit?',
       'Rate my golf fits this week, one to ten.',
       'The belt that goes with every polo I own.'],
      [(OPEN, 'Mirror or locker room. Snap or jump transition through four outfits, a different Muni with each.'),
       (MID, 'Each outfit gets one second on the first tee: navy with The Last Loop, khaki with Beach Club, baby blue with Weekend Warrior, black with Skid Mark.'),
       (CLOSE, 'Ask the viewer to pick the best fit in the comments.')],
      on_screen='Fit check: which Muni wins?',
      do='Put the belt name on screen for each look.',
      dont='Let the outfit cover the belt. Tuck the shirt in.',
      lever='Identity', products=MUNI, hot=1, trend='Any fit check or outfit transition trend.'),
    A('muni', 'I bought a belt called Skid Mark', 'Reaction',
      "Every Muni belt has a name and a story golfers get, and your buddies will not stop talking about it.",
      'Friend groups who give each other grief on the course.',
      ['I bought a golf belt called Skid Mark.',
       'Guess what this belt is called.',
       'My buddies asked what my belt is called and I had to tell them.'],
      [(OPEN, 'First tee. A buddy asks about the belt. You say the name. Get the real reaction.'),
       (MID, 'Explain the story: Skid Mark is for the tire tracks when you skid the cart round the corner of 14. Quick cut of the cart turning (slowly, safely).'),
       (CLOSE, 'The other names, one line each: The Last Loop, Beach Club, Weekend Warrior. Ask which one they would be.')],
      on_screen='Which Muni golfer are you?',
      do='Keep the reaction real. One take, no script for your buddy.',
      dont='Drive the cart recklessly. A slow turn sells the joke.',
      lever='Humor', products=MUNI, hot=1),

    # ---------------- Fall golf and buddy trips ----------------
    A('fall', "Where'd you get that belt?", 'On-course POV',
      'Wear it once and the whole group notices.',
      'The guy who likes being the one with the good gear in his foursome.',
      ["I wore this belt one round and got asked about it four times.",
       "Counting how many times my buddies ask about my belt.",
       "Your whole group is going to ask about this belt."],
      [(OPEN, 'Hole 1: a buddy points at the belt. Counter on screen: 1.'),
       (MID, 'Quick cuts through the round as the count goes up: a marker off the buckle, a glove clipped on, a tee from the holder.'),
       (CLOSE, 'At the 19th hole a buddy asks where to get one. Final count on screen.')],
      on_screen='Times asked about my belt: 4',
      do='Keep a running count on screen. Let the real questions happen.',
      dont='Fake it with a script. It shows.',
      lever='Status', hot=1),
    A('fall', 'One belt, four rounds', 'Flat lay',
      'For a golf trip you pack one belt, because it holds everything and goes with everything.',
      'Guys packing for a buddy trip: Myrtle, Scottsdale, Pinehurst, anywhere.',
      ['Packing for a four round golf trip. One belt.',
       'Golf trip packing list, and the one thing that saves me the most room.',
       "Four rounds in three days. Here's the only belt I'm bringing."],
      [(OPEN, 'Suitcase open on the bed. Four outfits laid out, one Dartee belt on top.'),
       (MID, 'Load the belt: marker in the buckle, tees in the holder, glove clipped on. Everything else goes in the bag.'),
       (CLOSE, 'Arriving at the course on the trip, belt on.')],
      on_screen='4 rounds. 1 belt.',
      do='Show the destination or the tee sheet so it feels like a real trip.',
      lever='Relief'),
    A('fall', 'One for you, one for your homie', 'Skit',
      'The best golf gear gets bought in pairs, because your buddy is going to want one the second he sees yours.',
      'Two buddies who play together every weekend.',
      ['I bought my buddy the same belt so he would stop stealing my marker.',
       'One for you. One for your homie.',
       "My golf partner kept borrowing my tees. So I fixed it."],
      [(OPEN, 'On the green, your buddy pats his pockets for a marker and grabs the one off your belt.'),
       (MID, 'Next round: you hand him his own Dartee. He puts it on at the car.'),
       (CLOSE, 'Both of you on the first tee, matching belts.')],
      on_screen='One for you. One for your homie.',
      do='Only mention a two-belt deal if it is live on the site that day.',
      dont='Say anything is free.',
      lever='Belonging'),
    A('fall', 'Scramble day, you have the marker', 'On-course POV',
      'In a scramble every ball gets marked, and you are the one who always has one ready.',
      'The guy who plays scrambles, charity outings and member-guests every fall.',
      ['Four balls on the green, one marker. Mine.',
       'Scramble rule: always stand next to the guy with the Dartee belt.',
       'Every scramble team needs one guy with this belt.'],
      [(OPEN, 'Scramble green, four balls down. Your teammates dig through pockets.'),
       (MID, 'You pull the marker off the buckle, mark, and snap it back in. Then again for the next ball.'),
       (CLOSE, 'Team photo at the outing, belt in frame.')],
      on_screen='The guy with the marker is the MVP.',
      do='Film a real outing if you can: the flag, the carts lined up, the team.',
      lever='Belonging'),

    # ---------------- Gifts and Black Friday ----------------
    A('gift', "The gift he won't buy himself", 'Voiceover',
      "Most golfers won't spend on a nice belt for themselves, which is exactly why it is the gift he will wear every round.",
      'Wives and girlfriends shopping for a golfer.',
      ["The golf gift he would never buy himself.",
       "He'll never spend on a nice belt. So I did.",
       'What I got the golfer who has everything.'],
      [(OPEN, 'Voiceover over a wrapped Dartee box on the counter.'),
       (MID, 'He opens it. Show the whole kit: belt, buckle, marker, tee and glove holders.'),
       (CLOSE, 'Him wearing it on the course that weekend. "He hasn\'t taken it off."')],
      on_screen='The gift he would never buy himself',
      do='Film his real reaction. Keep the camera on his face.',
      lever='Gifting', products='Any Dartee belt (the gator and ostrich belts look best in the box)',
      ads=['120232222230200741']),
    A('gift', 'Clueless wife, perfect gift', 'Talking head',
      "You don't have to know anything about golf to get this one right.",
      'Wives, girlfriends and kids who know nothing about golf gear.',
      ["I know nothing about golf. Here's what I got him.",
       'Clueless golf wife here. I nailed the gift.',
       "I can't tell a driver from a putter, and he loved this."],
      [(OPEN, 'Her to camera, holding the box: "I know nothing about golf."'),
       (MID, 'What sold her, in her words: it holds his marker, his tees and his glove, and she did not need his size.'),
       (CLOSE, 'His reaction, then him on the course with it.')],
      on_screen='Golf gift for people who know nothing about golf',
      do='Let her be funny about not knowing golf. That is the hook.',
      dont='Make him look dumb. He is the hero of the gift.',
      lever='Gifting'),
    A('gift', 'No waist size needed', 'Demo',
      "You don't need to know his waist size, because you cut the belt to fit once and it adjusts every 1/8 inch.",
      "Gift buyers who don't know his size, or are worried it won't fit.",
      ["Buying a belt as a gift? You don't need his size.",
       "I didn't know his waist size. Didn't matter.",
       'The only belt you can buy without knowing his size.'],
      [(OPEN, 'Hold up the belt: "I had no idea what size he wears."'),
       (MID, 'Show the sizing card, measure against his waist, cut once, snap on the buckle.'),
       (CLOSE, 'Ratchet it tight with a few clicks. Fits up to 46 inches.')],
      on_screen='No size? No problem.',
      do='Measure before you cut, on camera.',
      dont='Say it fits any size. It fits up to 46 inches.',
      lever='Relief'),
    A('gift', 'He opens it', 'Reaction',
      'A Dartee box feels like a luxury present before he even sees the belt.',
      'Anyone filming a golfer opening a gift: birthday, anniversary, Christmas.',
      ['Surprised my husband with a golf belt that does everything.',
       "My dad's reaction to his golf gift.",
       'Watch his face when he sees what the buckle does.'],
      [(OPEN, 'He unwraps the box. Hold on his face.'),
       (MID, 'He finds the marker in the buckle and pops it off. Real reaction.'),
       (CLOSE, 'Him putting it on right away.')],
      on_screen="His reaction when he found the marker",
      do='One continuous take for the opening. Real beats polished.',
      lever='Gifting'),
    A('gift', 'Stocking stuffers for the golfer', 'Flat lay',
      'Markers, tees and a glove that all clip onto his belt make the easy stocking stuffers he will actually use.',
      'Gift buyers who already got the belt, or want something small.',
      ['Golf stocking stuffers under $25.',
       'Stocking stuffers for the golfer, and they all clip onto his belt.',
       'The small golf gifts that actually get used.'],
      [(OPEN, 'Stocking on the mantle. Pull out the items one at a time.'),
       (MID, 'Ball markers ($9.99), Dar-Tees ($9.99), the Dartee glove ($24.95). Show each one clipping onto the belt.'),
       (CLOSE, 'Everything laid out next to the belt.')],
      on_screen='Golf stocking stuffers under $25',
      do='Say the price of each item as it appears.',
      lever='Gifting', products='Ball markers, Dar-Tees, Dartee golf glove'),
    A('gift', 'Black Friday, cover the foursome', 'Voiceover',
      "Black Friday is the one time to get the whole group sorted, because everyone in your foursome is getting one anyway.",
      'The guy who buys for his golf buddies, his dad and his brother.',
      ['Black Friday plan: one belt for everyone in my foursome.',
       'Every golfer on my list, done in one order.',
       "The Black Friday deal I've been waiting for all year."],
      [(OPEN, 'Four belt boxes on a table, a name tag on each.'),
       (MID, 'One line on why each person gets their colour.'),
       (CLOSE, 'Say the Black Friday offer exactly as the site shows it.')],
      on_screen='Black Friday: the whole foursome',
      dont="Make up a discount. Only say the offer that is live on darteegolf.com the day you post.",
      lever='Value', products='Belts, gift packs'),

    # ---------------- The utility belt ----------------
    A('util', 'Batman on the golf course', 'Reveal',
      "It's a utility belt for golf: everything you need is on your hip, right where you reach for it.",
      'Gear guys who love a good gadget.',
      ['I feel like Batman on the golf course.',
       'The golf utility belt.',
       'Every golfer needs a utility belt.'],
      [(OPEN, 'Hero pose on the first tee. Pull a tee from the holder like a gadget.'),
       (MID, 'Quick cuts: marker off the buckle on the green, glove clipped off and on.'),
       (CLOSE, 'Walk off, cape optional.')],
      on_screen='Golf utility belt',
      do='Play the joke straight and fast. Quick cuts, big sound.',
      dont='Use any Batman logo or movie music. Just say the word.',
      lever='Identity', trend='Any superhero or gadget reveal trend with original audio.'),
    A('util', "What's on my belt", "What's on my belt",
      "Everything a golfer used to dig through his pockets for lives on one belt.",
      'Golfers who watch What\'s in the bag videos.',
      ["What's on my belt.",
       "Forget what's in the bag. Here's what's on my belt.",
       'Everything I need for 18 holes, on one belt.'],
      [(OPEN, 'Tight shot at hip level: "What\'s on my belt."'),
       (MID, 'One piece at a time, a few seconds each: the buckle, the marker, the tee holder with two tees, the glove holder, the ratchet.'),
       (CLOSE, 'Zoom out to the full outfit on the tee box.')],
      on_screen="What's on my belt",
      do='Keep each piece short. Name it, show it used, move on.',
      lever='Proof'),
    A('util', 'Stop getting stabbed by tees', 'Skit',
      'Tees in your pocket poke you all round. Tees on your belt never do.',
      'Every golfer who has reached into a pocket and got jabbed.',
      ['If you keep tees in your pocket, this is for you.',
       'Stabbed by a tee for the last time.',
       'POV: you reach in your pocket for a ball marker.'],
      [(OPEN, 'Reach into your pocket and get jabbed. Big reaction.'),
       (MID, 'Empty the pocket: loose tees, a broken tee, lint, a coin. Then the belt with tees clipped in.'),
       (CLOSE, 'Grab a tee from the holder on the tee box without looking.')],
      on_screen='Tees go on the belt, not in your pocket',
      lever='Relief'),
    A('util', 'The glove never hits the ground', 'Side by side',
      "Your glove falls out of your back pocket and gets lost. On the belt it stays put and dries out.",
      'Golfers who have lost a glove mid round or put one through the wash.',
      ['I lost two gloves in one round. Never again.',
       "Where does your glove go between shots?",
       'My glove used to live in my back pocket. Look at it now.'],
      [(OPEN, 'Split screen: left, a glove flopping out of a back pocket and falling on the fairway. Right, the glove clipped on the belt.'),
       (MID, 'Take the glove off after a shot and clip it on in one move.'),
       (CLOSE, 'Hole 18: the glove is still there.')],
      on_screen='Back pocket vs belt',
      do='Show a real lost glove if you have one. Everybody does.',
      lever='Loss'),
    A('util', 'Never borrow a marker again', 'On-course POV',
      'Your marker is always on your buckle, so you never dig for it or hold up the group.',
      'Golfers who dig for a marker every green or keep borrowing one.',
      ["Stop asking your buddy for a ball marker.",
       'Mark, putt, snap it back. Done.',
       "Standing in my buddy's line digging for a marker. Not anymore."],
      [(OPEN, 'Over-the-shoulder POV on the green. Hand goes to the buckle.'),
       (MID, 'Marker off, mark the ball, pick it up. Snap the marker back on the buckle.'),
       (CLOSE, 'Hole the putt. Walk off.')],
      on_screen='Marker on the buckle',
      do='Film on a real green, from your eye line. We have enough buckle close-ups.',
      dont='Film the buckle alone on a table.',
      lever='Relief', ads=['120242460444050741', '120245501801680741']),
    A('util', '18 holes, never touched it', 'Test',
      'The ratchet stays where you set it and the marker stays in the buckle, from the first swing to the last.',
      'Skeptics who think a magnet or a ratchet will slip.',
      ['18 holes. I never touched my belt once.',
       'Testing if this magnetic marker falls off in a full round.',
       'Does a ratchet belt slip when you swing hard? Let\'s find out.'],
      [(OPEN, 'Show the setting on the ratchet and the marker in the buckle on hole 1.'),
       (MID, 'Montage of hard swings, bunker shots, bending down, riding the cart.'),
       (CLOSE, 'Hole 18: same setting, marker still there.')],
      on_screen='Hole 1 vs hole 18',
      do='Hit real swings. The test only works if it is real.',
      dont='Over-tighten it. Set it to fit and leave it.',
      lever='Proof'),

    # ---------------- Look the part ----------------
    A('look', '$100 for a golf belt?', 'Unboxing',
      "It sounds like a lot for a belt until you see everything that comes with it.",
      'Guys who think a golf belt should cost $20.',
      ['$100 for a golf belt?',
       "My wife asked why I spent $100 on a belt. Here's why.",
       "I thought $100 for a belt was crazy. Then I opened it."],
      [(OPEN, 'Text on screen: $100 for a golf belt? Open the box.'),
       (MID, 'Show everything: the textured leather, the buckle, the marker, the tee and glove holders, the ratchet. One line each.'),
       (CLOSE, 'Wearing it on the course. "Now it makes sense."')],
      on_screen='$100 for a golf belt?',
      do='Say the real price of the belt you are holding.',
      lever='Value', products='Greenside Gator or Sand Trapped Ostrich belts ($99.99)',
      ads=['120239237680840741']),
    A('look', 'Compliments before the first tee', 'Close-up',
      'The gator and ostrich belts get noticed before you hit a shot.',
      'The guy who likes a detail people ask about.',
      ['This belt gets more compliments than my swing.',
       'Compliments before the first tee shot.',
       "Three people asked about my belt before I'd hit a ball."],
      [(OPEN, 'Slow push-in on the gator or ostrich texture in daylight.'),
       (MID, 'Parking lot to the range to the first tee. Someone points at the belt.'),
       (CLOSE, 'Say the colour name: Albino Gator, Midnight Black Caiman, Volcanic Ash.')],
      on_screen='Compliments before the first tee',
      do='Film the texture in daylight, not in a dark room.',
      dont='Say real alligator or ostrich. It is textured leather.',
      lever='Status', products='Greenside Gator, Sand Trapped Ostrich', ads=['120246116810010741']),
    A('look', 'The white belt handicap', 'Joke',
      'A white belt says you mean business, and your buddies know it.',
      'Guys who get the golf joke about white belts and low handicaps.',
      ['I wear a white belt. Guess my handicap.',
       'When I wear the white belt, my buddies just hand me the money.',
       'White belt energy.'],
      [(OPEN, 'First tee. Slow reveal up from your shoes to the white belt.'),
       (MID, 'Your buddies react. One pays you before the round starts.'),
       (CLOSE, 'Then the real handicap on screen. Keep it funny.')],
      on_screen='White belt. Guess my handicap.',
      do='Let the joke land on you, not your buddies.',
      lever='Humor', products='Albino Gator and other white belts in stock', trend='Guess my handicap.'),
    A('look', 'The drop you missed last time', 'Unboxing',
      'Limited drops and favourite colours sell out, so when one comes back you move fast.',
      'Collectors who own more than one Dartee belt.',
      ["I missed this drop last time. Not again.",
       "They're back, and I got mine.",
       'The Dartee belt that sold out on me twice.'],
      [(OPEN, 'Phone screen showing the restock or new drop, then the box arriving.'),
       (MID, 'Unbox fast: the belt and the matching marker.'),
       (CLOSE, 'Next to your other Dartee belts. Which one today?')],
      on_screen='Back in stock',
      do='Film only a drop or colour that is actually in stock right now.',
      dont='Say how many are left unless the site says it.',
      lever='Scarcity', products='Current drops and restocks', ads=['120245845649450741']),

    # ---------------- Ditch the old belt ----------------
    A('ditch', 'Your belt only holds up your pants', 'Side by side',
      'Your old belt does one job. This one holds your marker, your tees and your glove too.',
      'Guys who wear the same old leather belt to the course.',
      ['If your belt only holds up your pants, it is time.',
       'My old belt vs my golf belt.',
       'One belt does one thing. One does four.'],
      [(OPEN, 'Split screen: old belt on the left, Dartee on the right.'),
       (MID, 'Checklist on screen as you show each: holds pants (both), holds marker, holds tees, holds glove, no holes.'),
       (CLOSE, 'Toss the old one in a drawer.')],
      on_screen='Your belt vs a golf belt',
      lever='Loss', ads=['120237391091280741', '120237391091310741']),
    A('ditch', "You don't need another belt, you need a better one", 'Pattern interrupt',
      "You don't need more belts. You need one that does the job on the course.",
      'Guys with a drawer full of belts who think they are covered.',
      ["You definitely don't need another belt.",
       'I own eleven belts. None of them are golf belts.',
       'This is what I think of my old golf belt.'],
      [(OPEN, 'Do something surprising with the old belt: toss it in the bin, drop it off the cart, hand it to the dog.'),
       (MID, "Then: \"You don't need another belt. You need a better one.\" Show the Dartee on."),
       (CLOSE, 'Marker off the buckle on the green.')],
      on_screen="You don't need another belt.",
      do='Make the first second weird enough to stop the scroll.',
      dont='Copy our toilet version. Find your own surprise.',
      lever='Humor', ads=['120240009827450741', '120240009817870741']),
    A('ditch', 'Cut it once, fits all season', 'Demo',
      'You cut the strap once and the ratchet takes care of the rest, even when your waist changes.',
      'Guys who punched new holes in their belt or whose weight goes up and down.',
      ["No, I didn't just ruin this belt.",
       'I cut my new belt in half. On purpose.',
       'Punching new holes in your belt? Stop.'],
      [(OPEN, 'Scissors cutting the strap. Pause. "No, I didn\'t just ruin it."'),
       (MID, 'Measure with the sizing card, cut, slide the buckle on.'),
       (CLOSE, 'Ratchet a few clicks looser and tighter: every 1/8 inch, no holes.')],
      on_screen='No holes. Every 1/8 inch.',
      do='Measure with the sizing card before you cut, and show it.',
      dont='Cut without measuring. A strap cut too short is not covered.',
      lever='Proof'),
    A('ditch', 'Ditch the dad belt', 'Transition',
      'The belt from your office closet makes a sharp golf outfit look like a work day.',
      'Younger golfers and dads who want to dress better on the course.',
      ['Ditch the dad belt.',
       'Your golf fit is ruined by one thing.',
       'Golf fit glow up, starting with the belt.'],
      [(OPEN, 'Full fit with a shiny office belt. "Something\'s off."'),
       (MID, 'Snap transition to the same fit with a Dartee.'),
       (CLOSE, 'Walk to the first tee.')],
      on_screen='Glow up',
      lever='Identity', ads=['120238662506390741'], trend='Any glow up or before and after transition.'),

    # ---------------- Always works ----------------
    A('ev', 'The whole kit in one second', 'Unboxing',
      'Open the box and you see everything at once: belt, buckle, marker, tee holder, glove holder.',
      'Anyone seeing Dartee for the first time.',
      ["Everything that comes with a Dartee belt.",
       "This isn't just a belt.",
       'Open the box. Count the pieces.'],
      [(OPEN, 'Box already open, shot from above, every piece visible in the first second.'),
       (MID, 'Name each piece as you take it out and put the belt together.'),
       (CLOSE, 'Wear it. Marker on the buckle.')],
      on_screen='Everything in the box',
      do='Start with the box open. Never spend the first seconds on the lid.',
      lever='Value', ads=['120237392010370741']),
    A('ev', '3 strokes minimum', 'Joke',
      "It won't fix your slice, but you'll look like you know what you're doing.",
      'Golfers who love a gear joke.',
      ['How many strokes will a golf belt save me?',
       '3 strokes minimum. Trust me.',
       'Is this a game improvement belt or a players belt?'],
      [(OPEN, 'Deadpan to camera: "How many strokes will this belt save me?"'),
       (MID, 'Rip a drive into the trees. Pause.'),
       (CLOSE, '"It didn\'t fix my slice. But I look good, and my marker is right here."')],
      on_screen='Game improvement belt?',
      do='Keep it deadpan. The joke is on you.',
      dont='Say it actually helps your score.',
      lever='Humor'),
    A('ev', 'First try reaction', 'Reaction',
      'Anyone who tries it for the first time gets it in one hole.',
      "Buddies or a course staffer who have never seen a Dartee.",
      ['I gave my buddy this belt on the first tee. No explanation.',
       "My friend had never seen this belt. Here's his first hole.",
       "Not planned. First time he's worn it."],
      [(OPEN, 'Hand the belt to a buddy on the first tee. No explanation.'),
       (MID, 'Film him figuring it out: the marker pops off, the tee holder, the glove clip.'),
       (CLOSE, 'His honest verdict after the hole.')],
      on_screen='First time wearing it',
      do='Let him react in his own words. Unscripted wins.',
      dont='Feed him lines.',
      lever='Proof'),
    A('ev', 'Why is there a glove on your belt?', 'Skit',
      "It looks different, and once you explain it, everyone wants one.",
      'Couples who golf together or golfers with a partner at home.',
      ['"Why is there a glove hanging off your belt?"',
       '"Babe, why does your belt have a magnet?"',
       'My wife asked me to explain my golf belt.'],
      [(OPEN, 'Partner at home: "Why is there a glove on your belt?"'),
       (MID, 'You explain it like a salesman: glove holder, tee holder, marker in the buckle.'),
       (CLOSE, 'Partner: "Okay, that is actually smart." Or she takes it.')],
      on_screen='Explaining my golf belt to my wife',
      lever='Humor'),

    # ---------------- Masters to Father's Day (off until March) ----------------
    A('spring', 'Masters week, dress the part', 'Transition',
      'Masters week is when every golfer wants to look like he belongs at Augusta.',
      'Golfers hosting or going to a Masters watch party, or playing that weekend.',
      ['Masters week fit check.',
       'Dressing like I got a tee time at Augusta.',
       'Masters Sunday, and the belt matches the green.'],
      [(OPEN, 'Watch party or TV on in the background. Fit check.'),
       (MID, 'The belt close up. A green or gold one if it is in stock.'),
       (CLOSE, 'Out to the course that weekend.')],
      on_screen='Masters week fit check',
      dont="Use the Masters logo or say Augusta National is involved.",
      lever='Identity', products='Green and gold belts in stock'),
    A('spring', "The Father's Day gift he wears every round", 'Reaction',
      "Dad has enough mugs. This is the Father's Day gift he'll wear every time he plays.",
      "Kids and wives shopping for Father's Day.",
      ["The Father's Day gift my dad actually uses.",
       "Dad's got enough golf balls.",
       "Father's Day, sorted."],
      [(OPEN, 'Dad opens it. Camera on his face.'),
       (MID, 'He finds the marker in the buckle.'),
       (CLOSE, 'Playing a round together, both wearing Dartee.')],
      on_screen="Father's Day, sorted",
      lever='Gifting'),
]

sql = ["-- Dartee creator link seed (see seed_dartee.py)",
       f"DELETE FROM p_amb_proof WHERE act_id = {q(ACT)};",
       f"DELETE FROM p_amb_angle WHERE act_id = {q(ACT)};",
       f"DELETE FROM p_amb_section WHERE act_id = {q(ACT)};",
       f"DELETE FROM p_amb_brand WHERE act_id = {q(ACT)};"]
b = brand
sql.append(
    "INSERT INTO p_amb_brand (act_id, slug, live, display_name, intro, about, audience, accent, logo_url, "
    "submit_platform, submit_url, submit_label, avoid_json, rules_json, season_json, show_inspo, pdf_json) VALUES (" +
    ', '.join(q(x) for x in [ACT, b['slug'], b['live'], b['display_name'], b['intro'], b['about'], b['audience'],
                             b['accent'], b['logo_url'], b['submit_platform'], b['submit_url'], b['submit_label'],
                             json.dumps(b['avoid']), json.dumps(b['rules']), json.dumps(b['season']), b['show_inspo'],
                             json.dumps(b['pdf'])]) + ");")
sec_id = {}
for i, s in enumerate(SECTIONS):
    sid = rid(); sec_id[s['key']] = sid
    sql.append("INSERT INTO p_amb_section (id, act_id, name, line, icon, icon_svg, color, enabled, pinned, sort) VALUES (" +
               ', '.join(q(x) for x in [sid, ACT, s['name'], s['line'], s['icon'], svg(s['icon']), s['color'],
                                        s.get('enabled', 1), s.get('pinned', 0), i]) + ");")
hot_n = 0
sort_by_sec = {}
for a in ANGLES:
    aid = rid()
    sort_by_sec[a['sec']] = sort_by_sec.get(a['sec'], 0) + 1
    if a['hot']:
        hot_n += 1
    sql.append("INSERT INTO p_amb_angle (id, act_id, section_id, hot, hot_sort, sort, status, title, argument, who, products, "
               "format, lever, openers_json, shots_json, on_screen, do_text, dont_text, trend) VALUES (" +
               ', '.join(q(x) for x in [aid, ACT, sec_id[a['sec']], a['hot'], hot_n if a['hot'] else 0, sort_by_sec[a['sec']],
                                        'live', a['title'], a['argument'], a['who'], a['products'], a['format'], a['lever'],
                                        json.dumps(a['openers']), json.dumps(a['shots']), a['on_screen'], a['do'], a['dont'],
                                        a['trend']]) + ");")
    for k, ad in enumerate(a['ads']):
        sql.append("INSERT INTO p_amb_proof (id, act_id, angle_id, kind, ad_id, shown, sort) VALUES (" +
                   ', '.join(q(x) for x in [rid(), ACT, aid, 'meta', ad, 1, k + 1]) + ");")

open(os.path.join(HERE, 'seed_dartee.sql'), 'w', encoding='utf-8').write('\n'.join(sql) + '\n')
print(len(ANGLES), 'angles,', len(SECTIONS), 'sections,', sum(len(a['ads']) for a in ANGLES), 'tagged ads')
