"""Ice & Gold creator link, built from nothing on 2026-10-06 from docs/research-2026-10-06/ice-and-gold.md.

  LUCIDE_NODES=<path>/icon-nodes.json python migrations/seed_amb_ice_and_gold.py
  npx wrangler d1 execute mobius-account-health --remote --file migrations/seed_amb_ice_and_gold.sql   (ONCE)

Creates the brand row (slug ice-and-gold, switched OFF: no TRYBE campaign link yet, Cole flips it live
from the Ambassadors tab) and the whole page. Owner rules: never "gold plated", never "real gold" or
"solid gold"; say 18K gold-filled or gold PVD. Site is on a 20% sale on 2026-10-06, so no prices are
hard-coded anywhere; creators read the price off the site the day they post.
Open with Cole: Pick Any 4 for $150 (not visible on the site), 14 vs 30 day money-back, waterproof vs
sweat proof, the gold-filled vs PVD split per piece, Adeola's handle, the free gift at $250.
"""
import os, sys
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from amb_seed_lib import write, OPEN, MID, CLOSE

ACT = 'act_952386692927446'
HERE = os.path.dirname(os.path.abspath(__file__))

BRAND = dict(
    display_name='Ice & Gold',
    accent='#C9A84C',
    logo_url='https://iceandgold.com/cdn/shop/files/WhatsApp_Image_2026-07-21_at_7.56.24_PM_1.png?v=1785321904&width=360',
    submit_platform='TRYBE', submit_label='Film this on TRYBE',
    intro=("Ice & Gold is everyday gold jewelry from Atlanta, started by Fela, a mom of four whose mother sold gold in Nigeria. "
           "It is 18K gold-filled and gold PVD, so it does not tarnish, does not turn your skin green, and you never have to take it off. "
           "The videos that sell it are people wearing it in real light, not product spins. Pick an idea, do the first second the way "
           "it says, and submit it on TRYBE."),
    about=("Sets for the party and the wedding (Water Drop Set, Gold Link Set, Spiral Set, Lariat Heart Set, Studded Herringbone & Hoop Set), "
           "earrings and chains you never take off (Gold Link Earrings, Mixed Metal Link Earrings, Twisted Herringbone, Screw-On Gem Bracelet), "
           "letter pendants and the Africa pendant, and a men's line of clean Cuban, rope and Figaro chains, the Lion coin and the Compass. "
           "Free US shipping on every order, 1-year warranty, free gift over $250. Prices are on the site; read them off it the day you post."),
    audience=("Denise, 35, makes content, buys earrings or a necklace she will wear every day. Lola, 50, parties, weddings and church, buys the set. "
              "Babs, 41, wants to look good and buys the men's chain, or his wife buys it for him. Most of our customers are Nigerian-American and "
              "Black women in and around Atlanta, and six in ten come back, so talk to the woman who already owns one piece too."),
    avoid=[
        dict(title='The piece on marble with a voiceover and no person',
             why='Both of our agency statics lost. Every creator try-on beat them. If nobody is wearing it, we cannot use it.'),
        dict(title='A plain try-on of the Compass pendant',
             why='It ran and sold nothing. The pendant sells on what it means to the man you give it to, not on a spin.'),
        dict(title='A haul of six pieces with no hero',
             why='Our best creator video was one pair of earrings on one ear. Give people one thing to buy.'),
        dict(title='"Real gold" tests: vinegar, magnet, acid',
             why='Ice & Gold is gold-filled and gold PVD, not solid gold. Prove tarnish and sweat, never purity.'),
        dict(title='Luxury-ad words: elevate, timeless elegance, main character energy, treat yourself',
             why='It reads as copy. The best jewelry ads right now talk like a person: "Uh, excuse me, this is our best seller."'),
        dict(title='Pulling the herringbone over your head on camera',
             why='Herringbone chains kink. Clasp it, lay it flat, show it on.'),
    ],
    rules=[
        'Say "18K gold-filled" or "gold PVD". Never "gold plated", never "real gold", never "solid gold".',
        'Say "tarnish free", "sweat proof", "hypoallergenic", "won\'t turn your skin green". Say "water resistant", not "waterproof", until we confirm.',
        'Say "designed in Atlanta". Not "made in Atlanta".',
        'Free US shipping on every order. 1-year warranty. Free gift when you spend over $250.',
        'Money-back window: say nothing until we confirm the number of days.',
        'Name the piece and read its price off the site the day you post. Prices change with sales.',
        'Code Gold15 is 15% off and anyone can say it. Code Adeola is hers; only she uses it.',
        'Film in daylight by a window or outside. Gold on skin, never gold on a table.',
        'Only film people who agreed to be in your video. Kids: faces out unless the parent says yes.',
    ],
    season=dict(
        title='Black Friday and Christmas build', until='Nov 20',
        line=("Film the proof videos and the gift videos now so they are live by Nov 10. Black Friday week and the December weddings "
              "and parties are the biggest weeks of the year for us. Valentine's follows in January."),
        next='Black Friday and Cyber Monday from Nov 27, Christmas last ship date in December, Valentine\'s from Jan 15',
        highlight=['10-06', '12-20'], show_chart=False, color='#C9A84C',
    ),
    guide=[
        dict(title='Be wearing it before you say a word', text='Face in frame, piece catching the light, mid-sentence. The best jewelry ad in the category opens on the founder already holding the chain: "Uh, excuse me."'),
        dict(title='Water, sweat or a pillow in the first second', text='The shower head, the gym mirror, the bed. Everyone has had a necklace turn on them, so showing it survive is the hook. No claim beats a picture of water on gold.'),
        dict(title='Say the embarrassing thing out loud', text='"Has a necklace ever turned your neck green?" A street-interview ad built on that one question has run four months for another brand. Then show the fix.'),
        dict(title='Give them a day counter', text='Day 1, Day 4, Day 7 on screen. A number that climbs is the simplest reason to keep watching, and it is the proof.'),
        dict(title='Change the picture every 3 seconds', text='Bathroom, car, church door, party. Same earrings in every cut. If you have been talking for 8 seconds without moving, cut.'),
        dict(title='Name the piece. Then the price, from the site', text='"This is the Water Drop Set." Say it, show it, put it on screen. A piece with no name cannot be bought.'),
        dict(title='Let the other person react', text='She opens the box and goes quiet, then puts it on. He feels the weight of the chain. The pause is the ad. Do not script it.'),
        dict(title='End on it being worn, and who it is for', text='"If you have the earrings, this is the necklace." Then the code. No "link in bio", no wrap-up speech.'),
    ],
)

SECTIONS = [
    dict(key='hot', name='Hot right now', line='The ideas we want most this week. Start here.', icon='flame', color='#C2410C', pinned=1),
    dict(key='proof', name='Does it turn green?', line='The proof videos: shower, gym, sleep, the old chain that turned. Our claims, shown.', icon='droplets', color='#0F766E'),
    dict(key='gift', name='Black Friday and Christmas gifts', line='Film now, live Nov 1 to Dec 20. Sets, the chain for him, the box, the letter.', icon='gift', color='#15803D'),
    dict(key='occasion', name='The set for the occasion', line='Owambe, weddings, church, birthday dinners, Detty December. Lola and her daughters.', icon='party-popper', color='#DB2777'),
    dict(key='daily', name='Never take it off', line='Everyday gold: the stack, the letter, the bracelet you wash your hands in.', icon='sun', color='#B45309'),
    dict(key='his', name='His chain', line='Cuban, rope and Figaro chains, the Lion and the Compass. For him, or for her to give him.', icon='link', color='#1D4ED8'),
]


def A(sec, title, fmt, argument, who, visual_hook, rehook, openers, shots, on_screen=None, do=None, dont=None,
      why=None, inspo=(), products=None, hot=0, ads=(), keep_from=(), lever=None, trend=None):
    return dict(sec=sec, title=title, format=fmt, argument=argument, who=who, visual_hook=visual_hook, rehook=rehook,
                openers=list(openers), shots=list(shots), on_screen=on_screen, do=do, dont=dont, why=why,
                inspo=list(inspo), products=products, hot=hot, ads=list(ads), keep_from=list(keep_from), lever=lever, trend=trend)


AT = 'https://app.tryatria.com/ad/'

ANGLES = [
    # ---------------- Does it turn green? ----------------
    A('proof', 'Day one of not taking this necklace off', 'Day counter',
      'Wear one piece into the shower, the gym and to bed for a week and show it under the same light at the end.',
      'Anyone who has had a cheap necklace turn on them. This one travels to every audience.',
      'Water running over the necklace on your neck under the shower head, phone propped on the shelf. No face needed yet.',
      'Cut to the gym mirror, then the pillow, with a day counter on screen: Day 1, Day 4, Day 7.',
      ['Day one of not taking this necklace off.',
       "I'm about to do the thing you're not supposed to do with gold jewelry.",
       "It's been a week in the shower with this. Look."],
      [(OPEN, 'Water hitting the piece, the shelf shot.'),
       (MID, 'Gym and sleep with the counter climbing.'),
       (CLOSE, 'The piece on a white towel in daylight. Say the colour has not moved.')],
      on_screen='Day 7. Shower, gym, sleep. / Tarnish free. Sweat proof.', hot=1, products='Twisted Herringbone, Gold Link Earrings, any chain',
      why='The top creator videos in jewelry right now are all this: one person, one piece, a list of abuses, a reveal. It is also the shape that converts for us.',
      inspo=[('Oak & Luna', '"I work out in this, I shower in this, I jump in the ocean in this." The abuse list.', AT + 'm1417233863835377'),
             ('JAXXON', '"Three months later, no fading, no green neck." The time stamp as the payoff.', AT + 'm1362619162625683')],
      ads=['120246058389690658'],
      do='Same piece, same spot, day 1 and day 7. Say gold-filled or gold PVD.', dont='Say waterproof. Say sweat proof and tarnish free. No vinegar or magnet tests.'),
    A('proof', 'This is what a $15 necklace did to my neck', 'Talking to camera',
      'Show the green line an old necklace left and say why this one will not.',
      'Men and women who have bought a cheap chain. Everyone.',
      'You pull a dull old chain out of a drawer or your bag and hold it against your neck.',
      '"Do you know why it does that?" One word: copper. Then the Ice & Gold piece goes on.',
      ['Has a necklace ever turned your neck green? Mine did this.',
       'This is what a fifteen-dollar necklace did to me.',
       'Why does jewelry turn you green? One word.'],
      [(OPEN, 'The old chain in hand, against the neck.'),
       (MID, 'The copper answer, then the new piece going on, close on the skin.'),
       (CLOSE, 'A week later, same spot, no line.')],
      on_screen='Why it turns green: copper. / 18K gold-filled. Won\'t turn your skin green.', hot=1,
      why='A street-interview ad built on "has it ever turned your neck green?" has run four months for Craftd. It is the one memory every buyer has.',
      inspo=[('Craftd', 'The exchange: "Has it ever turned your neck green before?" "Yeah." "Do you know why?" "Uh, copper?"', AT + 'm1073914602481069'),
             ('JAXXON', '"Never wear a chain like this unless you want your skin to turn green."', AT + 'm1541606723604426')],
      do='Keep the old chain anonymous.', dont='Name a competitor brand.'),
    A('proof', 'Same earrings. Gym, shower, brunch.', 'Montage',
      'One pair worn through a workout, a shower and brunch, no changes.',
      'Denise. Works for a man with a chain too.',
      'Mid-rep in the gym, the Gold Link Earrings clearly visible, sweat on the skin.',
      'Hard cut to the same earrings at the brunch table, same angle. Text: same pair.',
      ['Same earrings, three places, no taking them off.',
       'I used to take my jewelry off for the gym. Not anymore.',
       'Watch these go from the gym to brunch.'],
      [(OPEN, 'The gym mirror, the rep.'),
       (MID, 'Shower steam, earrings in.'),
       (CLOSE, 'Brunch table, the water glass as the light.')],
      on_screen='Sweat proof. Hypoallergenic. Still on.', products='Gold Link Earrings, Mixed Metal Link Earrings',
      why='"You get your pump and you got your chain on" is how the men\'s chain brands prove it; nobody films it for earrings.',
      inspo=[('Craftd', 'The gym as the proof setting.', AT + 'm1073914602481069'),
             ('JAXXON', '"The gym, the club, the shower, it stays looking brand new."', AT + 'm1541606723604426')],
      ads=['120246058389690658'],
      do='Identical pair in every cut.', dont='Stack other brands into it.'),
    A('proof', "Nobody tells you this when you buy gold jewelry", 'Talking to camera',
      'Why gold-filled and gold PVD last and thin layers do not, with two pieces in hand.',
      'The sceptic who has been burned. Our "how to buy gold jewelry" ad is our best explainer.',
      'Two chains side by side on a dark cloth, your fingers rubbing the cheap one.',
      '"The difference is how much gold is actually on it." Text on screen puts it in plain words.',
      ['Nobody tells you this when you buy gold jewelry.',
       "There are three kinds of gold jewelry and only two are worth your money.",
       "Here's how I check if a chain will last."],
      [(OPEN, 'The two chains, the rub.'),
       (MID, 'Close on the clasp and the link finish of the Ice & Gold piece.'),
       (CLOSE, 'The Ice & Gold piece on you.')],
      on_screen='Gold-filled: a thick layer of gold bonded to the metal. / Gold PVD: gold bonded to steel, made for daily wear.',
      why='Our own explainer ad is one of the best things in the account. The category brands run "don\'t get ripped off" comparisons for the same reason.',
      inspo=[('Craftd', 'The "don\'t get ripped off" price and quality comparison.', None)],
      ads=['120241168770620658'],
      do='Use the words on the product pages: 18K gold-filled, tarnish-resistant, hypoallergenic.', dont='Say "gold plated" even about the cheap one. Say "the thin stuff".'),
    A('proof', 'Day 30. Let me show you the clasp first.', 'Day counter',
      'Commit on camera to 30 days and post the check-in as the ad.',
      'Denise and Babs. The "I have been burned" buyer.',
      'The piece held to camera with a hand-written "Day 30" note or the phone date visible.',
      'Flash back to day 1 (same shirt if you can), then back to today.',
      ["Thirty days ago I said if this tarnished I'm done with gold jewelry.",
       "I didn't take this off for a month. Here's the honest result.",
       'Day 30. Let me show you the clasp first.'],
      [(OPEN, 'Day 30 note, piece in hand.'),
       (MID, 'The month in five cuts.'),
       (CLOSE, 'The clasp and the back of the pendant in daylight. That is where cheap pieces fail.')],
      on_screen='Day 1 / Day 30 / No fade. No green.',
      why='JAXXON runs a 30-day test format and a two-month press test on a rival ended "still tarnish-free". A dated test is proof you can picture.',
      inspo=[('JAXXON', '"If this chain tarnishes in 30 days I\'m done with chains forever."', None)],
      ads=['120246847628540658'],
      do='Show the back of the pendant and the clasp.', dont='Fake the date.'),
    A('proof', 'Every necklace that turned on me', 'Talking to camera',
      'Dump the drawer of dead jewelry on the table and say why you stopped buying it.',
      'Women 30 to 55 with a drawer like this. Lola.',
      'A drawer or pouch tipped out on the table: dull chains, green-tinged hoops.',
      'One Ice & Gold piece placed on top of the pile. The contrast does the work.',
      ['This is every necklace that turned on me.',
       "Twelve years of jewelry that didn't last. One that did.",
       'If your jewelry drawer looks like this, keep watching.'],
      [(OPEN, 'The tip-out.'),
       (MID, 'The single Ice & Gold piece on top.'),
       (CLOSE, 'The piece on you.')],
      on_screen='All of this: a few months each. / This one: a year and counting.',
      why='"Unless you like wasting money" is the line the men\'s brands open on. Counting the money wasted out loud lands.',
      inspo=[('JAXXON', 'The "never buy a chain like this unless you like wasting money" opener.', AT + 'm1541606723604426')],
      do='Count the money wasted out loud.', dont='Show brand logos on the dead pieces.'),

    # ---------------- Gifts ----------------
    A('gift', 'He opened it, went quiet, and put it on', 'Reaction',
      'She buys the Cuban for his birthday or Christmas, checks it first, films him opening it.',
      'The woman who buys for Babs. She is the buyer; he is the wearer.',
      'Her hands opening his box before he gets home, the chain lifted out and weighed in her palm.',
      '"He has no say in this." Then the handover and his pause.',
      ["It's his birthday and he has no say in what he's getting.",
       'I checked it before he got home. The weight surprised me.',
       "He opened it, didn't say anything, and put it on. Still on."],
      [(OPEN, 'Her hands, the chain, the weight.'),
       (MID, 'The handover. Hold on his face.'),
       (CLOSE, 'Him wearing it at dinner, then at the gym a week later.')],
      on_screen='12mm Diamond Clasp Cuban. 1-year warranty. Ships free.', hot=1, products='12mm Diamond Clasp Cuban, 10mm Miami Cuban set',
      why='The cleanest gifting script in jewelry is a wife doing exactly this for JAXXON. We have the chain at a lower price.',
      inspo=[('JAXXON', 'The whole script: checked it early, engraved clasp, "went quiet for a second, and just put it on", three months later no green.', AT + 'm1362619162625683')],
      do='Let her say the weight and shine felt more expensive than the price.', dont='Let him do the talking. The buyer is her.'),
    A('gift', 'Four gifts, one order', 'Flat lay',
      'Four pieces on the table, one for each woman on your list, and the bundle price if it is live.',
      'Lola and Denise buying for a list.',
      'Four Ice & Gold boxes lined up, your hand sliding them into frame one by one.',
      'Each box gets a name: Mom, Auntie, Tola, me. The fourth is for you.',
      ["I'm buying jewelry for four women and only one of them is me.",
       'Mom gets the Water Drop set. Here is why.',
       'Every woman in my family is getting gold this year.'],
      [(OPEN, 'Four boxes, four names.'),
       (MID, 'Each piece out of its box, on your hand or ear, one line each.'),
       (CLOSE, 'The pile wrapped, "and this one\'s mine".')],
      on_screen='Four women. One order. Free US shipping.', products='Water Drop Set, Gold Link Earrings, Spiral Set, Screw-On Gem Bracelet',
      why='Set and gift-with-purchase offers are running at GLD, Craftd and Olivia & Pearl right now; the list-of-people shape makes a set video feel like a story.',
      inspo=[('Olivia & Pearl', 'Gift pitch with the sold-out-last-year urgency and a free bracelet over a spend.', AT + 'm2154889298715714')],
      ads=['120241282267840658'],
      do='Say who each one is for. If Pick Any 4 for $150 is live that day, say it exactly as the site does.', dont='Say "treat yourself". Say "and this one\'s mine".'),
    A('gift', 'My mom hasn\'t bought herself jewelry in ten years. Watch.', 'Reaction',
      'The real reaction when a mother or sister opens the box, filmed by the giver.',
      "Lola's daughters, and husbands buying for Lola.",
      'Hands holding the box out to someone, the recipient not yet in frame.',
      'The lid lifts, the pause, then she puts it on without being asked.',
      ["My mom hasn't bought herself jewelry in ten years. Watch.",
       'I got her the set she kept screenshotting.',
       "She didn't say anything for a second. Then she put it on."],
      [(OPEN, 'The box handover.'),
       (MID, 'The pause on her face.'),
       (CLOSE, 'The piece on her, smiling.')],
      on_screen='The Water Drop Set. Ships free in the US.', products='Water Drop Set, Gold Link Set, Lariat Heart Set',
      why='"My niece went bonkers over the earrings" is how real reviews talk. The quiet-then-puts-it-on beat is the payoff everyone waits for.',
      inspo=[('JAXXON', 'The giver tells it: "He opened it, went quiet for a second, and just put it on."', AT + 'm1362619162625683')],
      ads=['120241282267840658'],
      do='Camera on her hands and face, not the giver.', dont='Script the reaction.'),
    A('gift', 'This is what shows up at your door', 'Unboxing',
      'A slow unboxing with the sound on, because the reviews praise the box as much as the piece.',
      'Everyone. Gifting and self-gifting.',
      'The outer box sliding open on a table, fingernails on the lid, no talking for two seconds.',
      'The inner case opens and the piece is lifted out and placed on your wrist or neck.',
      ['The packaging was as impressive as the necklace itself. That is a real review.',
       'Okay, this is what shows up at your door.',
       "If you're gifting this, you don't need to wrap it."],
      [(OPEN, 'The outer box, sound on.'),
       (MID, 'The inner case, the lift.'),
       (CLOSE, 'The piece on skin.')],
      on_screen='"The packaging was as impressive as the necklace itself." Zaylee, verified review.',
      why='"It came in the most gorgeous case" and "the packaging was as impressive as the necklace" are our customers\' words. A box opening is a first second with no claim in it.',
      inspo=[('JAXXON', 'Box opening as the first second: "oh we got ourselves a real thick boy".', AT + 'm1690346978705251')],
      do='Keep the sound real.', dont='Add a voiceover over the quiet part.'),
    A('gift', 'Send this to him', 'Talking to camera',
      'A video made to be forwarded: this is what I want, the name and the price are on screen.',
      'Denise and Lola. He receives it.',
      'You look straight into camera, piece already on: "Send this to your man."',
      'You hold up your phone with the product page, name and price, so he cannot get it wrong.',
      ["Send this to your man. He'll know what to do.",
       "If you're seeing this, she sent it on purpose.",
       "This is the Lariat Heart Set. The price is on screen. You're welcome."],
      [(OPEN, 'Face, piece on, the line.'),
       (MID, 'The phone, the product page.'),
       (CLOSE, 'Close on the piece. The code.')],
      on_screen='Lariat Heart Set. Free shipping. 1-year warranty. Code GOLD15.', products='Lariat Heart Set, Spiral Set',
      why='"You need to send them this link" is a shape Ana Luisa runs because it turns the viewer into the buyer\'s messenger.',
      inspo=[('Ana Luisa', 'The "send them this link" direct address.', None)],
      do='Exact product name on screen.', dont='Make the man the joke.'),
    A('gift', 'Here is how I got the free gift', 'Screen record',
      'Build a cart past $250 on camera and show the free gift line appear.',
      'The set buyer. Anyone doing one big order for several people.',
      'You wearing the Gold Link Set, holding up the phone with the cart open.',
      'The total ticks past $250 and the free gift line appears.',
      ['Here is how I got a free gift from Ice and Gold.',
       'Two sets, one free gift, done.',
       'Let me show you the cart trick.'],
      [(OPEN, 'The set on, the phone up.'),
       (MID, 'The cart climbing, the gift line.'),
       (CLOSE, 'The gift when it arrives, if you have it.')],
      on_screen='Free gift over $250. Free US shipping.', products='Gold Link Set, Water Drop Set',
      why='A cart that crosses a line is a count that changes, and the gift is the reveal.',
      inspo=[('Olivia & Pearl', '"Free bracelet on orders over" as the reason to add one more.', AT + 'm2154889298715714')],
      do='Confirm what the free gift is before filming.', dont='Show checkout with personal details.'),
    A('gift', 'I wear his letter. He wears mine.', 'Talking to camera',
      'The Letter Pendant with Cuban Chain is unisex. A couple wears each other\'s letters, or a mom wears her kids\'.',
      "Couples for Christmas and Valentine's. Mothers. Denise year-round.",
      'Two letter pendants on the table spelling your initials, or three for three kids.',
      'The letters go on two different necks, same chain.',
      ['I wear his letter. He wears mine.',
       'Three kids, three letters, one chain.',
       'The pendant comes off, so you can swap the letter.'],
      [(OPEN, 'The letters on the table.'),
       (MID, 'On him and on her.'),
       (CLOSE, 'Close on the removable pendant.')],
      on_screen='Gold Letter Pendant with Cuban Chain. A to Z. Unisex.', products='Gold Letter Pendant with Cuban Chain, Initial Pave Pendant',
      why='Our Letter Pendant creator ad is one of our best. Letter medallions are the best sellers at Melinda Maria for the same reason: a letter is about a person.',
      inspo=[('Melinda Maria', 'Letter medallions as "the perfect gift for you or for somebody that you love".', AT + 'm971922298946421'),
             ('Oak & Luna', '"The three boys\' initials on it. I have not taken it off since."', AT + 'm1417233863835377')],
      ads=['120246011992660658'],
      do='Say the pendant is removable; it is on the product page.', dont='Film one letter with no person attached to it.'),

    # ---------------- The set for the occasion ----------------
    A('occasion', 'Owambe Saturday. The gold has to match the gele.', 'Get ready with me',
      'Getting ready for a Nigerian wedding or party, gele on, the matching earrings and necklace last.',
      'Lola and her daughters. Nigerian-American and the wider West African diaspora, then any wedding guest.',
      'The gele being tied, or the aso ebi fabric laid out with the Ice & Gold box on top.',
      'Earrings go in with the gele already on, camera pulls back to the full look. A second cut at the party.',
      ['Owambe this Saturday and the jewelry has to match the gele.',
       'The aso ebi came. Now the gold.',
       'Every auntie is going to ask where I got this set.'],
      [(OPEN, 'Fabric and box, or the gele going on.'),
       (MID, 'Earrings in, necklace clasped, the pull back.'),
       (CLOSE, 'The full look at the door, then the party.')],
      on_screen='Water Drop Set. Earrings and necklace. / Tarnish free, sweat proof. It is going to be a long night.', hot=1, products='Water Drop Set, Gold Link Set, Spiral Set',
      why='Adeola\'s August set videos are the best ads in our account. December is wedding and Detty December season for our core customer.',
      inspo=[('Mejuri', '"It\'s a lot of weddings" as the reason to buy a set.', None)],
      ads=['120246418727900658', '120246329340620658', '120238437717380658'],
      do='Speak the way you talk, English and Yoruba or Igbo mixed if that is you.', dont='Explain owambe to the viewer. The pictures do it.'),
    A('occasion', 'Sunday. Sixty seconds. One set.', 'Get ready with me',
      'Sunday morning, the fastest way to look done is one set.',
      'Lola and church-going women 30 to 60.',
      'You in the mirror, hat or hair done, holding the earrings up.',
      'The phone time on screen. The necklace clasp done in one try.',
      ['Sunday. Sixty seconds. One set.',
       "I don't have time to pick jewelry on a Sunday, so I don't.",
       'Church fit. The gold is doing all the work.'],
      [(OPEN, 'The mirror, the earrings up.'),
       (MID, 'The clasp, the time.'),
       (CLOSE, 'The full look leaving the house.')],
      on_screen='Studded Herringbone & Hoop Set. Hypoallergenic. Lightweight.', products='Studded Herringbone & Hoop Set, Gold Twisted Herringbone Set',
      why='"You take a t-shirt and jeans and you put this on" is the founder line that runs at Melinda Maria. Speed is the pitch.',
      inspo=[('Melinda Maria', 'One piece, one outfit it fixes, said in a sentence.', AT + 'm1347251910609008')],
      do='Lay the herringbone flat on the table and clasp it.', dont='Pull it over your head.'),
    A('occasion', 'Same set. Sunday and Monday.', 'Side by side',
      'The set from church or the party to the office the next day.',
      'Lola and Denise. The "bought it for an occasion, wear it daily" buyer.',
      'Split or hard cut: the party look and the office look, same earrings.',
      'The day on screen flips from Sun to Mon while the earrings stay.',
      ['Same set. Sunday and Monday.',
       "I bought this for a wedding. I've worn it to work every day since.",
       "Party earrings that don't look like party earrings at the office."],
      [(OPEN, 'The party look.'),
       (MID, 'The office look, same angle.'),
       (CLOSE, 'Close on the earrings in both lights.')],
      on_screen='Gold Link Set. Necklace, bracelet, earrings.', products='Gold Link Set',
      why='The Gold Link Set is our best-selling set and the one Adeola wears in the ads that worked.',
      inspo=[('Melinda Maria', '"Is it a tennis? Is it a chain? It\'s both." One piece, two lives.', AT + 'm1705123507348587')],
      ads=['120238437717380658'],
      do='Keep the earrings identical and visible in both.', dont='Change hair and makeup so much the piece gets lost.'),
    A('occasion', 'My mom sold gold in Nigeria. This is what I learned from her.', 'Founder',
      'Fela tells the Lola story holding a piece: her mother sold gold in Nigeria and this is the collection in her memory.',
      'The core customer, and anyone who inherited a mother\'s jewelry.',
      'Fela holding an old photo or an older gold piece next to a new Ice & Gold piece.',
      '"She sold gold to the creme de la creme in Lagos." Then this piece, in hand, and what it costs.',
      ['My mom sold gold in Nigeria. This is what I learned from her.',
       'The first gold I ever wore was hers.',
       'I named a whole customer after my mother. Here is why.'],
      [(OPEN, 'The old piece and the new, in Fela\'s hands.'),
       (MID, 'The story, piece held the whole time.'),
       (CLOSE, 'The piece on Fela.')],
      on_screen='Fela, founder. Designed in Atlanta.',
      why='The owner\'s own benchmark, Melinda Maria, is the founder on camera holding one piece. Our founder video already works; the mother story is the missing piece.',
      inspo=[('Melinda Maria', 'The founder trunk show: "Uh, excuse me. This is our best selling collection of all time."', AT + 'm1347251910609008')],
      ads=['120247211799640658'],
      do='Under 40 seconds, piece in hand the whole time.', dont='Tell the business story with no product in hand.'),
    A('occasion', "It's my birthday and I bought myself the set", 'Get ready with me',
      'Getting ready for a birthday dinner where the set is the gift to herself.',
      'Denise and Lola, 30 to 50.',
      'You in a robe holding the box, the dinner outfit hanging behind you.',
      'The necklace goes on, then the full look with the bag and shoes, then the restaurant.',
      ["It's my birthday and I bought myself the set.",
       "Thirty-five and I finally bought gold I don't have to take off.",
       'Birthday dinner. The jewelry came first.'],
      [(OPEN, 'Robe and box.'),
       (MID, 'The clasp, the full look.'),
       (CLOSE, 'The dinner table.')],
      on_screen='Spiral Set. Free gift over $250.', products='Spiral Set, Lariat Heart Set',
      why='Our showcase-with-a-person ad is the best return in the account. A set shown as one look sells the set.',
      inspo=[('Melinda Maria', 'Self-gift framing without the phrase "treat yourself".', None)],
      ads=['120241282267840658'],
      do='Show the full set as one look.', dont='Say "main character energy".'),
    A('occasion', 'Detty December. Party to the first day back.', 'Montage',
      'The same set from the December parties to the first day back at work in January.',
      'The core customer home for Detty December, and anyone with a December calendar.',
      'A December calendar with the parties written in, your hand tapping each one.',
      'Each party is one cut, same set every time, then the office on Jan 2.',
      ['Four parties in December. One set.',
       'Detty December is here and the gold is coming with me.',
       'Party to the first day back. Never took it off.'],
      [(OPEN, 'The calendar, the taps.'),
       (MID, 'The parties, one cut each, same set.'),
       (CLOSE, 'Jan 2, the desk, the set still on.')],
      on_screen='One set. The whole of December.', products='Gold Link Set, Water Drop Set',
      why='December is wedding and party season for our core customer on top of Christmas; a count of parties is a reason to keep watching.',
      inspo=[('Mejuri', 'The many-weddings calendar as the problem a set solves.', None)],
      ads=['120246176282680658'],
      do='Real parties, real dates.', dont='Explain Detty December.'),

    # ---------------- Never take it off ----------------
    A('daily', 'The three things I never take off', 'Talking to camera',
      'The three pieces you wear every day, in the order you put them on, with one rule: they never come off.',
      'Denise, the everyday buyer.',
      'You already wearing all three, tapping each one on camera: earring, necklace, bracelet.',
      '"The necklace has been on since August." A quick flash of an older clip proves it.',
      ['The three things I never take off.',
       'This necklace has been on since August. Ask anyone.',
       'Everyday gold that survives me.'],
      [(OPEN, 'Tap, tap, tap.'),
       (MID, 'The clasp, close.'),
       (CLOSE, 'Sleeping or showering with it on.')],
      on_screen='Twisted Herringbone. Gold Link Earrings. Screw-On Gem Bracelet.', hot=1, products='Gold Twisted Herringbone, Gold Link Earrings, Screw-On Gem Bracelet',
      why='The one big-brand creator video rising in jewelry right now is "this is all I want to wear because of the compliments". Ours should be three named pieces.',
      inspo=[('Ana Luisa', '"They\'ve truly become my whole personality... because of the compliments that I get."', AT + 'm1871996997130595'),
             ('Craftd', '"You shouldn\'t have to take it off."', AT + 'm1051057737595285')],
      ads=['120246847628540658', '120246058389690658'],
      do='Name every piece on screen.', dont='Stack other brands into it.'),
    A('daily', 'Gold and silver on the same ear. Yes, you can.', 'Stack with me',
      'Build an ear or wrist stack with the Mixed Metal earrings as the anchor, because mixed metal is the permission right now.',
      'Denise and anyone watching fashion TikTok.',
      'An empty ear, then the first earring goes in at second zero.',
      'Each added piece changes the count on screen: 1, 2, 3. The last one is the mixed metal.',
      ['Gold and silver on the same ear. Yes, you can.',
       'Stack with me, mixed metal edition.',
       'Three pieces, one ear.'],
      [(OPEN, 'The empty ear, the first earring in.'),
       (MID, 'The count climbing, wrist stack too.'),
       (CLOSE, 'Full face, hair tucked.')],
      on_screen='Mixed Metal Link Earrings. Gold Link Earrings.', products='Mixed Metal Link Earrings, Mixed Metal Ball Earrings, Criss-Cross Mixed Metal Earrings',
      why='Our best creator ad ever is one pair of Mixed Metal Link Earrings on one ear.',
      inspo=[('Mejuri', 'The in-store stacking video, one piece at a time.', AT + 'm1047355604839586')],
      ads=['120246847628540658'],
      do='Film the ear in daylight by a window.', dont='Let the stack hide the hero piece.'),
    A('daily', 'Guess what this cost. Wrong.', 'Guess the price',
      'Show the piece, let them guess, then reveal the price from the site.',
      'The "it looks real" buyer. Everyone.',
      'The piece filling the frame, your hand turning it in the light, no price visible.',
      'Three wrong guesses on screen, then the real one.',
      ['Guess what this cost. Wrong.',
       "People think this is the expensive one. It isn't.",
       "Looks like fine jewelry. Isn't priced like it."],
      [(OPEN, 'The piece in hand, the light.'),
       (MID, 'The guesses.'),
       (CLOSE, 'The piece on you, the price on screen.')],
      on_screen='18K gold-filled. 1-year warranty.',
      why='Melinda Maria titles an ad "Guess the Price?" and a creator there says "luxury is a feeling, not a price tag". A guess is an open loop.',
      inspo=[('Melinda Maria', '"I found the most expensive looking necklace all the celebs are wearing."', AT + 'm975099272002734'),
             ('Melinda Maria', 'The "Guess the Price?" title.', AT + 'm971922298946421')],
      do='Give the real price inside 10 seconds, read off the site.', dont='Say real gold or solid gold.'),
    A('daily', 'I wash my hands in this and it does not care', 'Try-on close-up',
      'The Screw-On Gem Bracelet styled the way people style the famous screw bracelet, with the screw as the close-up.',
      'Denise and Lola. Dupe-aware shoppers.',
      'Your wrist with the bracelet, fingers turning the screw head.',
      'Stacked with a watch, then straight under the tap.',
      ['The screw bracelet look. Without the four-figure price.',
       'You know the one. This is mine.',
       "I wash my hands in this and it doesn't care."],
      [(OPEN, 'The screw, close.'),
       (MID, 'Wrist with the watch.'),
       (CLOSE, 'Under the tap.')],
      on_screen='Screw-On Gem Bracelet. Tarnish free. Hypoallergenic.', products='Screw-On Gem Bracelet',
      why='The dupe trend runs on the viewer naming the famous brand in the comments. We never say it.',
      inspo=[('Melinda Maria', 'A tennis piece as the layering secret weapon.', AT + 'm1705123507348587')],
      do='Let the comments name the famous brand.', dont='Say Cartier or dupe, on camera or on screen.'),
    A('daily', 'Four kids. Twins. This necklace is still on.', 'Founder',
      'Fela shows what she wears on a school-run day and why it has to survive four kids.',
      "Mothers 30 to 45. The core customer's daughters.",
      "A toddler's hand grabbing the necklace, or the car seat buckle with the bracelet in frame.",
      '"Mom of four, including twins." Then the piece surviving the day.',
      ['Four kids. Twins. This necklace is still on.',
       'Mom jewelry has one rule: it survives the toddler.',
       "I make jewelry for women who don't have time to take it off."],
      [(OPEN, 'The grab.'),
       (MID, 'The kitchen, the car.'),
       (CLOSE, 'The piece at the end of the day.')],
      on_screen='Fela, founder, mom of 4. Sweat proof. Kid proof, unofficially.',
      why='A mother-angle jewelry ad is rising this month for Tini Lux; our founder is a mom of four and already on camera.',
      inspo=[('Tini Lux', 'The sensitive-ears pain aimed at mothers.', AT + 'm1607002081161098')],
      ads=['120247211799640658'],
      do="Keep kids' faces out if Fela prefers.", dont='Make it a brand monologue.'),
    A('daily', "I don't have to explain this one", 'Talking to camera',
      'The Africa pendant as the piece that says it without saying it.',
      'The core customer and the wider diaspora. Men and women.',
      'The pendant on your chest, your hand resting on it, a flag or family photo soft behind you.',
      '"My dad asked where I got it. Then asked for one."',
      ["I don't have to explain this one.",
       "Where I'm from, on a chain.",
       'My dad saw it and asked for one. So now we match.'],
      [(OPEN, 'Pendant on the chest, hand on it.'),
       (MID, 'The pendant in hand.'),
       (CLOSE, 'Two people wearing it.')],
      on_screen='Africa Pendant and Chain. Gold-filled. Tarnish free.', products='Africa Pendant and Chain',
      why='A creator at JAXXON tied a medallion to being Italian and it is their best creator ad. Heritage on a chain needs no explaining.',
      inspo=[('JAXXON', 'The creator tying the medallion to his own heritage.', AT + 'm1690346978705251')],
      do='Say your specific country.', dont='Make it a history lesson.'),

    # ---------------- His chain ----------------
    A('his', "If you've never worn a chain, start here", 'Talking to camera',
      'The one chain to start with: the 6mm Cuban, not the biggest, not the most expensive.',
      'Babs and younger men. GQ readers.',
      "A man's hand holding the 6mm Cuban against a plain t-shirt at the collarbone.",
      '"Don\'t buy the biggest." A 12mm held up next to it for contrast.',
      ["If you've never worn a chain, start here.",
       "Don't buy the biggest one. Buy the one you'll wear every day.",
       'One chain changes a plain t-shirt. This one.'],
      [(OPEN, 'Hand, chain, t-shirt.'),
       (MID, 'Chain on, t-shirt, then an open collar.'),
       (CLOSE, 'The 12mm beside it: "later".')],
      on_screen='6mm Gold Cuban. Tarnish free. Sweat proof.', products='6mm Gold Cuban Link Chain',
      why='JAXXON\'s number two ad right now is "don\'t buy the biggest, don\'t buy the most expensive, get something clean". Our office Cuban video is the seed.',
      inspo=[('JAXXON', '"Don\'t overthink it. Don\'t buy the biggest, don\'t buy the most expensive."', AT + 'm1395239659365715')],
      ads=['120244930393670658'],
      do='Two outfits in 15 seconds.', dont='Use "iced out" language. The men\'s line is clean gold.'),
    A('his', 'Do you like chains on men? Be honest.', 'Street interview',
      'A woman asks women whether they like a chain on a man, then shows the Ice & Gold Cuban.',
      'Men who need permission. Women who buy for them.',
      'You with a mic walking up to a group of women, first question before any logo.',
      'You pull the chain out of your bag and hand it over. Their faces when they feel the weight.',
      ['Do you like chains on men? Be honest.',
       'Quick question for the ladies: chain or no chain?',
       'I asked ten women the same question.'],
      [(OPEN, 'The question.'),
       (MID, 'The chain in their hands.'),
       (CLOSE, 'A man trying it on at the end.')],
      on_screen="6mm Cuban. Won't turn his neck green.", products='6mm Gold Cuban Link Chain, 10mm Miami Cuban',
      why='Craftd runs "do you like chains on men?" to women because the woman buys the man\'s chain.',
      inspo=[('Craftd', 'The street interview outside a gym, question first, brand later.', AT + 'm1073914602481069')],
      do='Unscripted answers.', dont='Use a made-up statistic like "73% more dates".'),
    A('his', 'Lion or compass. Depends what he is going through.', 'Talking to camera',
      'The Lion coin and the Compass told as a gift choice: lion for the man starting something, compass for the man leaving home.',
      'Women gifting men. Men choosing their own.',
      'Two pendants on the table, your finger moving from one to the other.',
      '"I gave the lion to my brother when he..." The personal story.',
      ['Lion or compass. Depends what he is going through.',
       'The pendant you give says something. Choose it on purpose.',
       'My brother got the compass when he moved to Houston.'],
      [(OPEN, 'The two pendants.'),
       (MID, 'One on a chain on a man.'),
       (CLOSE, 'The box.')],
      on_screen='Gold Lion Coin Pendant. Compass Pendant.', products='Gold Lion Coin Pendant, Compass Pendant with Chain',
      why='Our Lion coin creator video sold; our Compass try-on sold nothing. The pendant needs the meaning.',
      inspo=[('JAXXON', 'Graduation-gift pendants: "guidance for his next chapter".', None)],
      ads=['120246847917810658'],
      do='Tie the pendant to a moment in a man\'s life.', dont='Film the compass as a product spin again.'),
    A('his', 'Cape off, chain on', 'Skit',
      'At the barber, the cape comes off and the chain is the first thing back on. The barber reacts.',
      'Babs and younger men. Atlanta.',
      'The cape being pulled off, the chain catching the light as he sits up.',
      'The barber asks where it is from and feels the weight.',
      ['Cape off, chain on.',
       'The barber asked. So here.',
       'Fresh cut, clean chain, Saturday.'],
      [(OPEN, 'Cape off.'),
       (MID, 'The chain in the mirror.'),
       (CLOSE, 'The barber holding it.')],
      on_screen="Men's Cuban chains.", products='10mm Miami Cuban set, 6mm Gold Cuban',
      why='"Every detail matters. How you train, how you show up, what you wear." The barbershop is where men talk about looking good.',
      inspo=[('JAXXON', '"Every detail matters" in 11 seconds.', AT + 'm1054013177246892')],
      do='Under 20 seconds, shop sound on.', dont='Add a voiceover.'),
    A('his', "Twitch, what's the only chain you wear?", 'Podcast clip',
      'Two men talking about a chain is the only format where a man admits he cares about jewelry.',
      'Babs. Men 30 to 55.',
      'Two men at a table or in a car, mics or phones, one asks the other what chain he wears.',
      '"Never comes off my neck. Sweat proof." The other one pulls his out.',
      ["What's the only chain you wear when you step out?",
       'Which one never comes off?',
       'Okay, chain talk. Go.'],
      [(OPEN, 'The question across the table.'),
       (MID, 'Both chains out, the weight.'),
       (CLOSE, 'One line each on why.')],
      on_screen='10mm Miami Cuban. 6mm Cuban. Sweat proof.', products='10mm Miami Cuban, 6mm Gold Cuban, 3mm Gold Rope',
      why='JAXXON has run a podcast clip built on this question for over four months.',
      inspo=[('JAXXON', '"Twitch, what\'s the only chain you wear when you step out?"', AT + 'm1513411913702715')],
      do='Real friends, real chains.', dont='Script it.'),
]

SPEC = dict(act_id=ACT, slug='ice-and-gold', create=True, brand=BRAND, sections=SECTIONS, angles=ANGLES)

if __name__ == '__main__':
    write(SPEC, os.path.join(HERE, 'seed_amb_ice_and_gold.sql'))
