"""Party Patch creator link, rebuilt 2026-10-06 from docs/research-2026-10-06/party-patch.md.

  LUCIDE_NODES=<path>/icon-nodes.json python migrations/seed_amb_party_patch.py
  npx wrangler d1 execute mobius-account-health --remote --file migrations/seed_amb_party_patch.sql   (ONCE)

Replaces every section and angle on the Party Patch page. Keeps the brand row (slug, live, TRYBE
link, logo, PDF) and re-points the existing tagged Meta ads onto the new angles by old title
(Get your Sunday back, Stock up for the season, The morning after doesn't have to be a plot twist,
The packet shows up too late, The sniff test).
Voice: cheeky and bar-side, second person, a friend at the bar; a woman 30 to 50 talking to her
phone mid-thought. Never the wellness clinic. Compliance: "for a better next day" / "so tomorrow
still happens", never cures / prevents / stops, never hangxiety, 21+, nobody drunk, never the
hungover morning. Prices: only what the site shows the day you post. Halloween bundle = 3 designs,
2 of each, 6 patches, price unconfirmed so never said.
Open with Cole: the Halloween bundle price, what the 400-6 / 394 C / 381 B creatives show, whether
the hot tub test is safe to film, the bartender and GLP-1 angles (left out).
"""
import os, sys
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from amb_seed_lib import write, OPEN, MID, CLOSE

ACT = 'act_1033194534145987'
HERE = os.path.dirname(os.path.abspath(__file__))

BRAND = dict(
    display_name='Party Patch',
    intro=("Party Patch is the patch you stick on before the night so tomorrow still happens. We want videos that look "
           "like your actual life: the girls, the kids, the calendar, the one drink at dinner. One rule before anything "
           "else: do something with your hands before you talk. Patch on, pile on the counter, pen on the calendar, then "
           "the first line. Pick one idea, film it your way, and submit it on TRYBE like always."),
    about=("A vitamin-infused patch you put on before drinks, for a better next day. Scent-free, zero calories, water "
           "resistant, nothing to mix. Fun designs, and right now the Halloween bundle: three designs, two of each, six "
           "patches. Prices and offers change, so only ever say what is on the site the day you post."),
    audience=("Women 30 to 50 with a full calendar. Moms, mostly. She is not trying to party harder. She wants the night "
              "out AND the 8am soccer game, the school run, the Sunday hike, the Christmas card photo. Talk to her like a "
              "friend at the bar, not like a wellness clinic."),
    accent='#1E88E5',
    avoid=[
        dict(title='Talking to camera about hangovers while putting a patch on, with a text overlay',
             why='This is most of what we get. It all looks the same and none of it stands out in the feed.'),
        dict(title='Lying in bed or on the couch looking hungover',
             why='We sell a better tomorrow, not a bad one. Show her up and doing the thing.'),
        dict(title='Shots, heavy drinking, or anyone who looks drunk',
             why='It breaks ad rules and it is not our customer. A drink in hand at dinner or a party is fine.'),
        dict(title='Reading the claims off the pack',
             why='Show the moment it helps. Nobody stops scrolling for an ingredient list.'),
        dict(title='An unboxing with no story',
             why='Unboxings only work when they are for something: the girls trip, the party tonight.'),
        dict(title='Talking to the camera while nothing happens',
             why=('The four creator videos we ran this way were the worst ads on the account, every one of them. Your hands do '
                  'something in the first second: patch on, pile on the counter, pen on the calendar. Then talk.')),
    ],
    rules=[
        'Say "for a better next day" or "so tomorrow still happens". Never say it cures, prevents or stops hangovers.',
        'Never say "hangxiety" and never mention anxiety, calm or stress. Every other brand says it; we cannot make that claim.',
        'The patch goes on BEFORE the night, on camera, where we can see it. Never show it going on the morning after.',
        'Keep the patch visible in at least one shot: arm, shoulder or hip.',
        'Everyone on screen is 21 or older. No drinking and driving, ever. Nobody looks drunk.',
        'Say "water resistant", never "waterproof". That is what the pack says.',
        'Reviews: only ones that are live on partypatch.com, read word for word, with the words on screen.',
        'Prices and offers: only say the price on the site the day you post. Never say a price for the Halloween bundle.',
        'Film vertical, sound on, and show where you are in the first two seconds.',
        "Only film people who have agreed to be in your video. Kids only with a parent's okay, and never near a drink.",
    ],
    season=dict(
        title='Halloween, then the holidays', until='Oct 31',
        line=("Halloween is now: costume parties, the mom group chat, the Halloween bundle. Film your holiday videos in "
              "October too, so they are live on Nov 1. December is our biggest month of the year, and the videos that "
              "run in December get filmed now."),
        next="Friendsgiving, holiday parties and New Year's Eve, from Nov 1",
        highlight=['10-06', '12-31'], show_chart=True, color='#7C3AED',
    ),
    guide=[
        dict(title='Your hands first, then your mouth',
             text='Patch on the shoulder, the pile on the counter, the red pen on a Saturday. Then the first line. A face saying hello gets scrolled. A hand pressing a patch on gets watched.'),
        dict(title='Say who it is for in line one',
             text='"If you drink wine and you have kids, this one is for you." The right woman stops. Everyone else scrolls, and that is fine.'),
        dict(title='Change the picture at 3 seconds',
             text='Bar at 9pm, then pancakes at 7am. Mirror, then the door. If you have been talking to the camera for five seconds without moving, cut.'),
        dict(title='Give them a number that keeps changing',
             text='Saturdays left this year: 11. The receipt total climbing. Nine girls, nine kits. If she is waiting for the next number, she stays.'),
        dict(title='Go quiet when you test it',
             text='Arm in the hot tub, timer on, say nothing. Let the camera watch it stay on, then react for real. The quiet is the proof.'),
        dict(title='The gripe goes in the middle, not the start',
             text='Open on the night or the patch. Bring in "two glasses costs me a weekend now" once they are already watching. And never open on the bad morning; we do not show it at all.'),
        dict(title='End on her, and what to do',
             text='Up at 7, soccer, pancakes, the boat, patch on the wrist. Then, in your own words: who it is for and where to get it. No "link below", no wrap-up speech.'),
        dict(title='No logo, no "hey guys", no sponsored card',
             text='The brand shows up in your hands and in the story, never as a title slide. Start like you are mid-thought with a friend: "So I counted the Saturdays I lost last year."'),
    ],
)

SECTIONS = [
    dict(key='hot', name='Hot right now', line='The five we want most this week. Start here.', icon='flame', color='#C2410C', pinned=1),
    dict(key='hall', name='Halloween', line='Costume parties, the mom group chat and the Halloween bundle: three designs, two of each. Until Oct 31.', icon='ghost', color='#7C3AED'),
    dict(key='hol', name='Holiday season', line="Friendsgiving to New Year's Eve. Film these NOW so they are live Nov 1. December is our biggest month.", icon='gift', color='#15803D'),
    dict(key='tt', name='Tomorrow is still happening', line='Her night, and the exact morning she still shows up for. Said in one breath.', icon='sunrise', color='#1D4ED8'),
    dict(key='age', name='Say your age', line='Say how old you are. Two glasses is a two-day event now, and she knows it.', icon='calendar-heart', color='#DB2777'),
    dict(key='show', name="Show it, don't say it", line='Trades, quizzes, label reads, six-second loops. Your hands are doing something before you say a word.', icon='sparkles', color='#0F766E'),
]


def A(sec, title, fmt, argument, who, visual_hook, rehook, openers, shots, on_screen=None, do=None, dont=None,
      why=None, inspo=(), products='Party Patch', hot=0, ads=(), keep_from=(), lever=None, trend=None):
    return dict(sec=sec, title=title, format=fmt, argument=argument, who=who, visual_hook=visual_hook, rehook=rehook,
                openers=list(openers), shots=list(shots), on_screen=on_screen, do=do, dont=dont, why=why,
                inspo=list(inspo), products=products, hot=hot, ads=list(ads), keep_from=list(keep_from), lever=lever, trend=trend)


ATRIA = 'https://app.tryatria.com/ad/'

ANGLES = [
    # ---------------- Halloween ----------------
    A('hall', 'Scary good night, less scary morning', 'Split screen',
      'The grown-up costume party is her night, and the pumpkin patch with the kids at 9 still happens.',
      'The mom going to an adult Halloween party with the family pumpkin patch booked for the morning.',
      'Split screen from frame one. Left: you in costume, drink in hand, 10:14 PM on screen. Right: same you at the pumpkin patch, kids running, 9:02 AM. No talking yet.',
      'At 3 seconds cut to the bathroom mirror earlier that night: the patch goes on before the costume is finished, design facing the lens.',
      ['Scary good night. Less scary morning. Same witch.',
       'Costume party tonight. Pumpkin patch at nine. Yes, with the kids.',
       'Me at ten pm versus me at nine am. Guess which one planned ahead.'],
      [(OPEN, 'The split: party left, pumpkin patch right, both clocks on screen.'),
       (MID, 'Back to the mirror: patch on, close enough to read the design, then the costume finished over it.'),
       (CLOSE, 'The pumpkin patch. You lift the biggest one like it is nothing. Pack in your coat pocket.')],
      on_screen='TONIGHT: Halloween party / TOMORROW: pumpkin patch, 9AM', products='Halloween bundle',
      why="Get 1906 launched on Oct 1 with 'Off Duty on Friday. On duty for Saturday's 7am pancakes' and every ad in the set is climbing. Two clocks on screen is that idea with a costume on.",
      inspo=[('Get 1906', 'The two scenes with the time on screen: Friday night, then the 7am morning. Steal the hard cut.', ATRIA + 'm1859426501710827')],
      do='Put both times on screen. The clock is the whole story.', dont='Show the morning from bed. She is up and lifting pumpkins.'),
    A('hall', 'Because moms deserve Halloween too', 'Group reaction',
      'The kids get Halloween every year. This is the night mom and her friends take it back, and the bundle has a design for each of them.',
      'A group of mom friends dressing up for their own Halloween night.',
      'Four hands reach into the open Halloween bundle at once. Patches come out, names up to the lens: Momster, Resting Witch Face, Here for the Boos.',
      'Each friend reads her patch name out loud and reacts. By the third name they are arguing over who gets which.',
      ["The kids had their Halloween. This one's ours.",
       'Group chat said costumes are mandatory. And patches, apparently.',
       'Six patches, three designs, four moms. Somebody is fighting over Momster.'],
      [(OPEN, 'Hands into the bundle, names to the lens, first line.'),
       (MID, 'Patches go on before anyone pours. Everyone reads her name out loud. Argue over who is Resting Witch Face.'),
       (CLOSE, 'Cheers shot with the patches on arms. End on the group laughing, not on the drinks.')],
      on_screen='Momster / Resting Witch Face / Here for the Boos', products='Halloween bundle (3 designs, 2 of each, 6 patches)',
      why="dayguard's number one ad is built on a ritual you can see: 'Koreans even cheers the sticks before their first shot.' Four patches going on at once is our ritual, and the names are the joke.",
      inspo=[('dayguard', 'The group ritual before the first drink, made visible.', ATRIA + 'm27797344126635112'),
             ('Waterboy', 'Two friends holding things up and reading them out. Steal the back-and-forth.', ATRIA + 'm1616399766694709')],
      do='Say "six patches, three designs" out loud. Let the names get the laugh.', dont="Film it alone, and don't say a bundle price. Say to check the site."),
    A('hall', 'He said he did not need one', 'Skit',
      'Couples costume night is the one night you both go out, and you both still have to parent at 7.',
      'Couples going to a costume party with kids at home.',
      'Matching costumes in the hallway mirror. She presses her patch on, then holds one out to him. He waves it off. Still no words.',
      'Hard cut to 7:05 AM: she is flipping pancakes in half her costume makeup. He walks in slow. Keep it playful, never sick.',
      ["Husband said he doesn't need one. Watch this.",
       "Matching costumes. Only one of us wore a patch. Guess who's making pancakes.",
       'We did a couples costume. We also both have a 7am wake-up call. One of us planned for it.'],
      [(OPEN, 'Mirror, costumes, her patch on, his wave-off.'),
       (MID, 'The morning: pancakes, kids, her moving fast. Him moving slow, holding a coffee, still in the hat.'),
       (CLOSE, 'He holds his hand out for a patch for next time. She hands it over with a look. Pack on the counter.')],
      on_screen="He said he didn't need one.", products='Halloween bundle',
      why="Waterboy's rising skit this month runs on one joke carried all the way through. The joke here is on him, not on drinking, and the morning stays loud and funny.",
      inspo=[('Waterboy', 'One absurd premise, played straight to the end. Steal the commitment to the bit.', ATRIA + 'm1401112791381628')],
      do='Keep it light. He is in on the joke.', dont='Make the morning look like a sick day. He is slow, not suffering.'),
    A('hall', 'Where the patch hides under the costume', 'Get ready with me',
      'People ask where it goes. Under a costume there are five good spots, and showing them is the whole video.',
      'Anyone building a costume that is more than a t-shirt: witch, cat, cowgirl, the group theme.',
      'Camera close on your hands pressing the patch onto your shoulder. Then the costume strap comes down over it. Gone.',
      'At 3 seconds, "guess where it is" and a fast spin in the finished costume. Then the reveal: strap up, patch there.',
      ['Where does the patch go under a witch costume? Here. Watch.',
       'Costume on. Patch on. You will not find it.',
       'Everyone asks where I put it. Shoulder, hip, or the one spot the dress hides.'],
      [(OPEN, 'Hands first: patch pressed on, strap over it.'),
       (MID, 'Finish the costume in fast cuts: lashes, hat, boots. Spin. "Guess where."'),
       (CLOSE, 'Strap down for the reveal, then out the door with your friends.')],
      on_screen='Shoulder. Hip. Under the strap. Pick one.', products='Halloween bundle',
      why="The Good Patch's rising ad opens on the inside of a wrist with the patch pressed on, camera close, before a word is said. The ritual is the hook; the costume is the reason to watch to the end.",
      inspo=[('The Good Patch', 'Patch pressed onto the wrist, camera close, first line after. Steal the hands-first open.', ATRIA + 'm1775730420219793'),
             ('The Good Patch', 'The six-second peel, stick, go loop. Steal the pace.', ATRIA + 'm1472651414618482')],
      do='Make the patch a real step in getting ready, not an afterthought at the end.', dont='Skip the reveal. People watch to see where it went.'),

    # ---------------- Holiday season (film in October) ----------------
    A('hol', 'The Christmas card morning', 'Split screen',
      'The holiday party is Saturday night and the family card photo is Sunday at 9, and she planned for both.',
      'Moms who booked the photographer and bought the matching pajamas.',
      'Left: sequins, 9:12 PM, a drink in hand. Right: matching pajamas, a photographer counting down, 9:04 AM. Both clocks on screen.',
      'At 3 seconds "three, two" from the photographer, then the flash. Then back to the party: the patch going on under the sequins.',
      ['Holiday party Saturday. Christmas card photos Sunday at nine. I planned for this.',
       "You can see last year's party in last year's card. Not this year.",
       'Sequins at nine pm. Matching pajamas at nine am. Same woman.'],
      [(OPEN, 'The split, both clocks.'),
       (MID, 'Patch on under the sequins in the bathroom mirror. Then the party, two quick cuts.'),
       (CLOSE, 'The card photo. Everyone smiling. Hold the real print up to the lens if you have it.')],
      on_screen='9PM / 9AM',
      why="Get 1906 names the morning plan out loud: 'tomorrow's workout, game, meeting, or morning plans are still happening.' A named morning beats a vague one, and a photographer counting down is a morning you can see.",
      inspo=[('Get 1906', 'The named morning plan. Steal the specificity.', ATRIA + 'm28648022974882496')],
      do='Use your real card shoot. Film it in November so it runs in December.', dont='Show the old "tired" card or say you looked rough. Just show this one.'),
    A('hol', 'Office party tonight, meeting at nine', 'Get ready with me',
      'The holiday party lands on a weeknight and the 9am meeting does not move.',
      'Women going to a work holiday party on a Tuesday.',
      'Your work laptop closing at 5:58 PM, then your hand pressing a patch on, then the party shoes coming out of the desk drawer.',
      'Text at 3 seconds: "Meeting at 9 tomorrow." Then the outfit swap in three cuts.',
      ['Office party tonight. Meeting at nine. Both are happening.',
       'Get ready with me for the work party. On a Tuesday. With a nine am.',
       'Holiday party outfit check, and the one thing nobody at the office will see.'],
      [(OPEN, 'Laptop shut, patch on, shoes out. No words until the patch is on.'),
       (MID, 'The outfit swap, the party: dancing with coworkers, one drink in hand, 21+ only.'),
       (CLOSE, 'Next morning on the video call, sharp, patch visible when you reach for the coffee.')],
      on_screen='PARTY: 7PM / MEETING: 9AM',
      why="ZBiotics is running 'Don't let a great night out compromise a productive morning routine' as a four-second clip. The weeknight version of that stake is a meeting, and that is her exact fear.",
      inspo=[('ZBiotics', 'The productive-morning stake stated in four seconds. Steal the brevity.', ATRIA + 'm1610793354114367')],
      do='Make the patch its own step in getting ready, right after the laptop closes.', dont='Film coworkers who did not agree to be in it.'),
    A('hol', 'The biggest Wednesday night of the year', 'Day in the life',
      "Thanksgiving Eve is the hometown reunion, and Thanksgiving morning in mom's kitchen starts early.",
      'Women home for Thanksgiving meeting everyone from high school at the one bar in town.',
      "Patch going on in the car in your parents' driveway, dome light on, the bar name on your phone screen.",
      'At 4 seconds the first hug at the bar door, someone you have not seen in ten years. Then the clock: 6:40 AM, the turkey.',
      ['Home for Thanksgiving. Everyone from high school is at the bar tonight. Mom needs me at seven.',
       "The biggest bar night of the year is a Wednesday. Patch in the car. Let's go.",
       'Thanksgiving Eve rules: patch first, then hug everyone you went to school with.'],
      [(OPEN, 'Driveway, dome light, patch on, the bar name.'),
       (MID, 'Hugs at the bar, the group photo, one drink in hand. Keep it warm, not wild.'),
       (CLOSE, 'Thanksgiving morning in the kitchen with mom, peeling something, fully present. Pack on the windowsill.')],
      on_screen='THANKSGIVING EVE / THANKSGIVING, 6:40AM',
      why="Waterboy's rising mom video opens with a real trip (Disneyland, the beach, the red-eye) and the product arrives late, as the thing that rides along. A hometown Wednesday is that story for us.",
      inspo=[('Waterboy', 'A real day told fast, product riding along, arriving once the story has earned it.', ATRIA + 'm1386099517035759'),
             ('dayguard', "'Drink Tonight. Feel Better Tomorrow.' has run 140 days. Steal the one-breath promise, keep our words.", ATRIA + 'm1720332875988351')],
      do='Film the real reunion, with everyone asked first.', dont='Shots, rounds, anyone who looks drunk. It is a hug night.'),
    A('hol', "Count the nights between now and New Year's", 'Voiceover',
      'She counted the parties on her calendar from now to January 1 and bought one patch for each of them.',
      'The planner who buys ahead, and anyone who has run out the night of the party.',
      'A wall calendar, your hand circling every night out in red marker, fast: Friendsgiving, office party, girls dinner, NYE.',
      'The count on screen climbs with each circle. At 5 seconds you tip the bundle out and lay one patch on each circle.',
      ["I counted my nights out between now and New Year's. Nine. So I bought nine.",
       'Every party on this calendar gets a patch. Every single one.',
       "Friendsgiving, two office parties, the girls' dinner, New Year's. I did the math."],
      [(OPEN, 'The circling, the count climbing.'),
       (MID, 'Patches laid on the circles, one each. Then one going on before the first of them.'),
       (CLOSE, 'Say the bundle offer exactly as the site shows it the day you post, then the pack into the purse.')],
      on_screen='Nights out until Jan 1: 9. Patches: 9.', products='Bundles',
      why="Our two best statics are a bundle message and 'before the weekend'. ZBiotics' four-second 'stocked bar cart' ad is the same idea on video: being prepared is the pitch, and a count is the rehook.",
      inspo=[('ZBiotics', "'Being prepared is the key to a better tomorrow. Ensure your bar cart is always stocked.' Steal the stock-up frame.", ATRIA + 'm28182952651327819'),
             ('Waterboy', 'A number that keeps changing holds people. Steal the count.', ATRIA + 'm1616399766694709')],
      ads=['120249211680840266', '120249488847230266'], keep_from=['Stock up for the season'],
      do='Use your real calendar and your real number.', dont='Make up a discount or a price. Only the offer that is live on the site the day you post.'),
    A('hol', "I'm the friend with the patches", 'Group reaction',
      "Every group has the one who brings the thing. At the girls' Christmas dinner she is the one with the patches in her purse.",
      "The mom friend of the mom friends, at the girls' Christmas dinner or the white elephant.",
      'Her purse opens on the restaurant table, a pack comes out, and the camera catches four faces lighting up.',
      'Handing them out, one line per friend: "you have the 6am flight, you have the toddler, you have the in-laws."',
      ["Every group has one. I'm the one with the patches.",
       "You bring the Advil. I bring these. Christmas dinner, let's go.",
       'My white elephant gift got stolen twice. It was a patch pack.'],
      [(OPEN, 'The purse, the pack, the faces.'),
       (MID, 'The handout, one reason each. Patches on arms before the first glass is lifted.'),
       (CLOSE, 'Four patches on, the cheers, the laugh. Then her, to camera: "Somebody has to be the planner."')],
      on_screen='The planner friend.',
      why="Waterboy's rising ad reads a review out loud: 'for a recent bachelorette party I included Waterboy in hangover kits I made.' The planner who brings them for everyone is a real customer, and Get 1906 sells 'control freak' as a compliment.",
      inspo=[('Waterboy', 'The named review about kits for the whole group. Steal the planner as the hero.', ATRIA + 'm1541318970835567'),
             ('Get 1906', "'Happy hour for control freaks.' Steal the proud self-description.", ATRIA + 'm1061582806703549')],
      ads=['120249488847230266'],
      do='Let the friends react for real. Ask them first.', dont='Film it alone at a table. This one needs the faces.'),
    A('hol', 'Big night, bigger tomorrow', 'Get ready with me',
      "New Year's Eve is the biggest night of the year, and January 1 is day one of whatever she promised herself.",
      "Women going out for New Year's Eve with a plan for the morning: the hike, the run, the pancakes.",
      'The sequin dress on the hanger, your hand pressing the patch on your hip before it goes over, the clock reading 7:48 PM.',
      'Text at 3 seconds: "Resolutions start at 9am." Then the glam in fast cuts.',
      ['Big night. Bigger tomorrow. My resolutions start at nine am and I mean it this time.',
       "New Year's Eve get ready with me. The patch goes on first. Then the dress.",
       "Last thing I put on before New Year's Eve is the thing that gets me to January first."],
      [(OPEN, 'Dress on the hanger, patch on, the clock.'),
       (MID, 'Lashes, hair, the dress over the patch, the door. One midnight clip, one drink, 21+ only.'),
       (CLOSE, 'January 1: the hike, the run, the pancakes with the kids. Pack on the counter.')],
      on_screen='DEC 31, 7:48PM / JAN 1, 9:00AM',
      why="ZBiotics' bachelorette ad lands on 'I wanted to be present for it all' with Pilates the next morning. January 1 is the most planned morning of the year, so the stake needs no explaining.",
      inspo=[('ZBiotics', "'We also had Pilates planned, so I wanted to be present for it all.' Steal the named next-morning plan.", ATRIA + 'm1025728377183837')],
      do='Name your real January 1 plan on screen.', dont='Show the countdown crowd drinking. One glass at midnight is plenty.'),

    # ---------------- Tomorrow is still happening ----------------
    A('tt', 'Off duty, on duty', 'Day in the life',
      'She gets one night off a week, and at 7am Saturday she is back on. The patch is how both happen.',
      'Moms with kids under 10.',
      'Text OFF DUTY over you laughing at a bar with friends, 8:14 PM on screen. Hard cut to ON DUTY, 7:02 AM, flipping pancakes with a kid on the counter. No talking yet.',
      'At 4 seconds flash back to the bathroom mirror: the patch goes on before you leave. Then back to the pancakes, louder.',
      ['Off duty Friday. On duty for seven am pancakes. You know how this ends.',
       'I get one night off a week. I am not spending Saturday on the couch.',
       "Mom's off duty. For about six hours. Then pancakes."],
      [(OPEN, 'The two-time cut, OFF DUTY then ON DUTY.'),
       (MID, 'The mirror: patch on, design to the lens, keys in hand.'),
       (CLOSE, 'Pancake flipped, kid cheering, syrup everywhere, patch visible on your wrist.')],
      on_screen='OFF DUTY 8PM / ON DUTY 7AM', hot=1,
      why="Get 1906 launched this exact mom on Oct 1 ('Off Duty on Friday. On duty for Saturday's 7am pancakes') and every ad in the set is rising. The domestic detail is what makes it land: pancakes, not 'responsibilities'.",
      inspo=[('Get 1906', "The two scenes and the creator's line 'I can get up in the morning with the kids and feel like myself'. Steal the pancakes.", ATRIA + 'm1859426501710827'),
             ('Get 1906', "'Tomorrow's workout, game, meeting, or morning plans are still happening.' Steal the named morning.", ATRIA + 'm28648022974882496')],
      keep_from=["The morning after doesn't have to be a plot twist"],
      do='Make the morning loud and real: kids, dog, syrup.', dont='Show the morning from bed. Not even for the joke.'),
    A('tt', 'I tried to hire someone for the morning', 'Skit',
      'Parents actually book sitters for the morning after a night out. She priced it, then looked at the patch.',
      'Parents of early risers, 30 to 45.',
      'You on the phone at the kitchen counter, deadly serious: "Hi. Do you do 7am soccer? Saturday? After a girls night?"',
      'The quote comes back as text on screen: Morning sitter: $120. You look down at the patch pack beside the phone. Long pause.',
      ['I called a sitter for the morning after girls night. A hundred and twenty dollars. Or.',
       "Tried to outsource my Saturday morning. Here's what that costs.",
       "There is a cheaper option than a morning babysitter. It's on my arm."],
      [(OPEN, 'The call, straight-faced.'),
       (MID, 'The quote on screen, the look at the pack, the patch going on that night before you leave.'),
       (CLOSE, 'Saturday 7am, you at soccer yourself, coffee in hand, patch on. "Kept the hundred and twenty."')],
      on_screen='Morning sitter: $120. Patch: see the site.', hot=1,
      why="Waterboy's rising 82-second skit is 'can I rent a waterboy for the day', played straight. The sitter premise is absurd and true: parents really do book morning babysitters, which is why the price comparison sells without a claim.",
      inspo=[('Waterboy', 'The rent-a-person premise, played straight to the end. Steal the deadpan.', ATRIA + 'm1401112791381628'),
             ('Scary Mommy', 'The "hangover babysitter" is a real thing parents book, and two thirds of parents plan childcare for the day after. Steal the true premise.')],
      ads=['120249211680840266'],
      do='Use real sitter rates for your city, and say the patch price from the site the day you post.', dont='Imply the kids were ever left alone.'),
    A('tt', "Your calendar doesn't care what you did last night", 'Split screen',
      'Tomorrow is already booked, so she wears the patch tonight and still shows up on the sideline.',
      'The mom whose Saturday starts on a soccer sideline at 8.',
      'Split screen. Left: 9:47 PM, margaritas with the girls, mid-laugh. Right: 8:03 AM, same you on the sideline in a camp chair, big coffee. Both times on screen before anyone talks.',
      'At 3 seconds, back to dinner: the patch goes on before the first drink arrives, close enough to read.',
      ["Your calendar doesn't care what you did last night. Mine says soccer at eight.",
       'Nine forty-seven pm, margaritas. Eight oh three am, sideline. Both me.',
       "Girls night was last night. Soccer is at eight. I'm fine, and here's why."],
      [(OPEN, 'The split, both clocks.'),
       (MID, 'Dinner: patch on, then the drink arrives. Two quick laughs with the girls.'),
       (CLOSE, 'The sideline: you cheer for your kid, loud. Pack on the chair arm.')],
      on_screen='TONIGHT: girls night / TOMORROW: 8AM soccer',
      why="Waterboy says it in one breath: 'tonight's gonna be amazing, tomorrow is gonna suck unless'. The stake is on screen in under three seconds and she fills in her own tomorrow. dayguard has run its version for 140 days.",
      inspo=[('Waterboy', 'The tonight-tomorrow line in one breath. Steal the speed.', ATRIA + 'm1541318970835567'),
             ('dayguard', "'Drink Tonight. Feel Better Tomorrow.' in its 140-day ad. Steal the two-word stakes, keep our words.", ATRIA + 'm1720332875988351')],
      do='Keep her looking good in both halves. The clock does the work.', dont='Show her tired or hurting on the sideline. The point is she is fine.'),
    A('tt', 'If you have kids, watch this', 'Talking to camera',
      'Kids wake up at six whether you went out or not. Say who this is for in the first line and let everyone else scroll.',
      'Parents, said straight to them.',
      'Text IF YOU HAVE KIDS over a kitchen at 6:45 AM: cereal already out, cartoons on, you pouring milk.',
      'At 3 seconds: "because they wake up at six whether you went out or not." Then flash to last night, the patch going on.',
      ["If you drink wine and you have kids, this one's for you.",
       'Kids do not care that you went out last night. Mine were up at six.',
       'My six am alarm is three feet tall and does not have a snooze button.'],
      [(OPEN, 'The 6:45 kitchen, the text, the milk.'),
       (MID, 'Last night: patch on in the car or the mirror, then the one drink, then home.'),
       (CLOSE, 'Back to the kitchen: cereal poured, kid fed, you awake. Patch visible on your wrist as you reach for the coffee.')],
      on_screen='IF YOU HAVE KIDS.',
      why="The Cheers founder opens his rank-4 ad with 'If you drink alcohol and you have kids and you have parents and grandparents, then you need to know about this.' Self-selection in line one is why a two-minute talking head still works for him.",
      inspo=[('The Cheers CEO', "The persona call-out in the first sentence. Steal 'if you have kids' and the straight delivery.", ATRIA + 'm1367112002210185')],
      do='Kids only with consent, or show the empty bowls and the cartoons.', dont='Show kids anywhere near a drink.'),
    A('tt', 'Stop losing Saturdays', 'Voiceover',
      'Saturday is the only day that is hers. She counted the ones she gave away last year and stopped.',
      'Women 35 to 50 whose Saturday is the only day that belongs to them.',
      'A wall calendar, a red marker crossing out Saturdays one after another, fast, no words.',
      'The pen stops at the next Saturday and draws a little patch on it instead. Then the real number of Saturdays left this year lands on screen.',
      ["I counted the Saturdays I lost last year. I'm not doing that again.",
       "Saturday is the only day that's mine. I stopped giving it away.",
       'Eleven Saturdays left this year. I want every one of them.'],
      [(OPEN, 'The crossing out, fast.'),
       (MID, 'Friday night: patch on before the drink, the girls, one laugh.'),
       (CLOSE, 'A Saturday: farmers market, soccer, the hike. Same woman, moving. Pack in the tote.')],
      on_screen='Saturdays left this year: 11.',
      why="dayguard's rank-2 ad is 'Stop Losing Your Mornings' and 'this is your precious weekend, but you're wasting it'. Wynk sells 'zero days wasted'. We take the count and leave the hungover picture out.",
      inspo=[('dayguard', "'Stop Losing Your Mornings' and 'Win-back Your Weekends'. Steal the loss, not the couch.", ATRIA + 'm1533442648531847'),
             ('Wynk Seltzer', "'Zero days wasted.' Steal the count.", ATRIA + 'm1483981077081289')],
      ads=['120246582639020266'], keep_from=['Get your Sunday back'],
      do='Use the real number of Saturdays left on the day you film.', dont='Show the lost Saturday. We never show the bad morning.'),
    A('tt', 'Happy hour for control freaks', 'Screen record',
      'She plans everything, including how she feels tomorrow. The patch lives in the planner.',
      'The planner mom with the color-coded calendar.',
      'Screen record of your phone calendar: a finger taps Friday GIRLS NIGHT, then Saturday SOCCER 8AM. Or the paper planner, same thing.',
      'At 3 seconds you pull a patch out of the planner pocket (or the phone case) and hold it to the lens.',
      ["Happy hour for control freaks. That's me. Hi.",
       'I plan everything. Including tomorrow morning.',
       "I'm the friend with the itinerary and the patches. Somebody has to be."],
      [(OPEN, 'The calendar, Friday then Saturday, the tap.'),
       (MID, 'The night, patch visible on the arm, one drink, the girls.'),
       (CLOSE, "Saturday's box gets ticked in the planner. Then the soccer field.")],
      on_screen='Planned: the night. Planned: the morning.',
      why="Get 1906's rank-4 ad is 'Happy hour for control freaks' and ZBiotics' whole September set is 'built for those who plan ahead'. Both sell a self-description the viewer is proud of. Our best static says 'before the weekend': same buyer.",
      inspo=[('Get 1906', "'Happy hour for control freaks. Any drink, same feeling, every single time.' Steal the proud label.", ATRIA + 'm1061582806703549'),
             ('ZBiotics', "'Built for those who plan ahead.' Steal the planner.", ATRIA + 'm2194257071137920')],
      ads=['120249488847230266'],
      do='Show your real calendar. Hide anything private first.', dont='Make her look stressed. Control is the joke, not the problem.'),
    A('tt', 'Day two is the whole point', 'Day in the life',
      'Night one is dinner. Day two is the boat, the hike, the winery. She is not missing day two.',
      'Women on a girls trip, 35 to 50.',
      'The trip itinerary on paper or a Notes screenshot, finger running down it: Day 1 dinner, bar. Day 2 boat, 9AM.',
      'Night footage cut hard to the 9am boat: hair up, coffee, sunglasses on your head, not your face.',
      ['Day one is dinner. Day two is the boat. I am not missing the boat.',
       'We booked a nine am hike after a tequila night. Watch this.',
       'Girls trip rule: nobody skips day two. Nobody.'],
      [(OPEN, 'The itinerary, the finger.'),
       (MID, 'Dinner: patches going on around the table, visible, before the first round.'),
       (CLOSE, 'The boat, the hike, the winery. All four of you there. Pack in the beach bag.')],
      on_screen='DAY 1: dinner. DAY 2: the boat.',
      why="ZBiotics' rising bachelorette ad is built on one line: 'we also had Pilates and a full day of activities planned, so I wanted to be present for it all.' Day two is the stake nobody else in the category is filming.",
      inspo=[('ZBiotics', "'I wanted to be present for it all.' Steal the next-day plan as the reason.", ATRIA + 'm1025728377183837')],
      do='Show the patch on night one, on camera.', dont='Film anyone looking rough on day two. Everyone made the boat.'),

    # ---------------- Say your age ----------------
    A('age', "I'm 44 and two glasses is a two-day event", 'Talking to camera',
      'Say her age out loud. What used to be a Tuesday now costs her a weekend, and she is done pretending otherwise.',
      'Women 40 to 50. The viewer who nods before you finish the sentence.',
      'Two fingers up to the lens. Then two wine glasses. Then a calendar with Saturday AND Sunday crossed out. Three cuts, two seconds.',
      'At 4 seconds: "so here\'s what I do now", and the patch goes on while you keep talking.',
      ["I'm forty-four. Two glasses of wine used to be a Tuesday. Now it's a two-day event.",
       'Where did my tolerance go? Asking for every woman at book club.',
       "Nobody told me that at forty, one drink costs a whole morning. So. Here's what I do."],
      [(OPEN, 'Fingers, glasses, calendar.'),
       (MID, 'Patch on before the drink, mid-sentence, like it is normal.'),
       (CLOSE, 'Sunday morning with the kids or the dog, pack on the counter. "Two glasses. Two days. Not anymore."')],
      on_screen='2 glasses. 2 days. Not anymore.', hot=1,
      why="The Good Patch's rising ad opens '40+ and feeling like your energy isn't what it used to be?' and Cheers built a company on 'after the age of 30, even responsible drinking makes you feel less than 100% the next day'. Nobody on our page says an age out loud yet.",
      inspo=[('The Good Patch', "The '40+' opener. Steal the age in the first line.", ATRIA + 'm1775730420219793'),
             ('The Cheers CEO', "'After the age of 30, even responsible drinking makes you feel less than 100%.' Steal the honesty about age.", ATRIA + 'm1367112002210185')],
      do='Say your real age.', dont='Say it stops anything. "For a better next day." That is the line.'),
    A('age', "I drink less now. That's exactly why.", 'Talking to camera',
      'She is not a wine mom. She drinks once a month, and that is exactly why one night costs her.',
      'The sober-curious mom who still says yes to girls night.',
      'Pouring one glass of wine and one sparkling water side by side. Your hands, the counter, no face yet.',
      'At 3 seconds: "and the one glass hits harder than it used to." Then the patch comes out of the drawer.',
      ['I drink way less than I used to. So when I do, it hits harder.',
       'Two drinks a month. Both of them cost me a morning. Not anymore.',
       "I'm not a wine mom. I'm a once-a-month mom. It still wrecks me, so."],
      [(OPEN, 'The two pours, side by side.'),
       (MID, 'Patch on. The one glass. The friends.'),
       (CLOSE, 'The morning, moving: the walk, the kids, the market. Pack visible.')],
      on_screen='Less often. Hits harder.',
      why="Get 1906's rising launch ad is a mom who 'never thought I would be the person to turn down my Friday night glass of wine'. Drinking less is the mainstream now, and the brands winning say so instead of joking about wine.",
      inspo=[('Get 1906', 'The creator who turned down the Friday glass of wine. Steal the anti-wine-mom stance.', ATRIA + 'm1859426501710827')],
      do='Keep it light and proud. She is not confessing.', dont='Lecture anyone, and never "mommy needs wine".'),
    A('age', "I'm 38 and I just read what's in these", 'Label read',
      'Flip the patch pack and the powder stick over and read the backs. Facts only, and the facts are on our side.',
      'The label reader, 35 to 50.',
      'A patch pack and a powder stick on the counter, both flipped to the back at the same time by one hand.',
      'A finger runs down the panel, stops, "wait." Then the pack facts land on screen one at a time: scent-free, zero calories, water resistant, nothing to mix.',
      ["I'm thirty-eight and I just read what's in the stuff I take after a night out.",
       'Powder stick versus patch. Read the back with me.',
       "I'm not a scientist. I can read a label. Let's go."],
      [(OPEN, 'The double flip.'),
       (MID, 'Pointing at lines on both, reading only what is printed. Pack facts on screen.'),
       (CLOSE, 'The patch goes on. "Scent-free, zero calories, nothing to mix. That one\'s mine."')],
      on_screen='Scent-free. Zero calories. Water resistant. Nothing to mix.',
      why="Waterboy's reused label ad opens 'i'm 35 years old and i just found out what's in these' and its bartender does the math on camera. Age plus 'just found out' is a curiosity gap, and words on screen give the eye a job.",
      inspo=[('Waterboy', "'I'm 35 and I just found out what's in these.' Steal the age plus the flip.", ATRIA + 'm3128643533989877'),
             ('Waterboy', "'Check the label.' Steal the finger running down the panel.", ATRIA + 'm961104253707387')],
      ads=['120243115360050266'],
      do='Read only what is printed on the Party Patch pack.', dont='Say it works better than anything. Compare facts, never results.'),
    A('age', 'I did everything right', 'Voiceover',
      'Water between drinks, dinner first, home by eleven, still rough the next day. So now she adds this.',
      'The responsible drinker who follows every rule and still loses the morning.',
      'A water glass set down next to a wine glass. Four quick cuts, four tables, same move.',
      'At 4 seconds: "and I still felt rough. So now I add this." The patch, on, mid-sentence.',
      ['Water between every drink. Dinner. Home by eleven. Still rough. So I added this.',
       'I did everything the internet said. Then I added one more thing.',
       "The water trick is not enough for me anymore. Here's the extra step."],
      [(OPEN, 'Water next to wine, four times, fast.'),
       (MID, 'Patch on before the first glass, the dinner, home early.'),
       (CLOSE, 'The morning, moving. "Water. Dinner. Early night. And this."')],
      on_screen='Water. Dinner. Early night. And this.',
      why="DrinkAid opens 'You've been told to drink water. You did. You still felt terrible.' The 'I did it right' setup is a real buyer's story. We keep the setup and leave out the mechanism.",
      inspo=[('DrinkAid', "'You've been told to drink water. You did. You still felt terrible.' Steal the setup, not the science.", ATRIA + 'm2792860367739408')],
      do='Say "for a better next day" and stop there.', dont='Explain why water was not enough. No mechanism, no claim.'),

    # ---------------- Show it, don't say it ----------------
    A('show', 'The pile vs the patch', 'Two-person trade',
      "Her friend's next-day routine is a whole pharmacy. Hers is one patch. Nobody has to claim anything.",
      'Two friends, 30 to 50, getting ready for a night out.',
      'A kitchen island covered in Pedialyte, bananas, a bottle of Advil, a powder stick, a gallon of water. One hand sets ONE patch down beside the pile.',
      'The trade starts at 2 seconds and speeds up: she names an item, you say "patch". Every time. At 8 seconds she asks what it all cost.',
      ['This is what she packs for a girls weekend. This is what I pack.',
       "Show me your morning-after routine. Okay. Here's mine.",
       'She brought a pharmacy. I brought a patch.'],
      [(OPEN, 'The pile and the patch, side by side, on the counter.'),
       (MID, 'She holds up each item and names it. You answer "patch" each time. Cuts get faster.'),
       (CLOSE, 'Both at the door, your patch on your arm, hers still packing. "What did all that cost?" Say the patch price from the site.')],
      on_screen='HER: Pedialyte. Advil. 3 bananas. ME: one patch.', hot=1,
      why="Waterboy's two rising partner ads this month are this exact trade: the pile, the one stick, and 'that must have cost a fortune / it's $2 a stick' as the ending. It is funny with the sound off and it needs no claims.",
      inspo=[('Waterboy', 'The trade and the price reveal at the end. Steal the rhythm.', ATRIA + 'm1616399766694709'),
             ('Waterboy', 'Same shape, rising since Sept 28. Steal the speed-up.', ATRIA + 'm1058963726969933')],
      keep_from=['The packet shows up too late'],
      do='Every line under two seconds. End on the price from the site the day you post.', dont='Say the patch replaces water or food. "For a better next day."'),
    A('show', 'Not a cure', 'Talking to camera',
      "Nobody's patch is magic. Say so first, then say what it is actually for. The honesty is the hook.",
      'Any woman 30 to 50, filmed anywhere but a couch.',
      'Hold the pack up to the lens and shake your head no before you say a word.',
      'At 3 seconds the "but": cut to the patch going on in the back of the Uber, then a 7am clip of you doing the thing.',
      ['This is not a hangover cure. Let me tell you what it is.',
       "I'm not going to tell you this fixes a tequila night. It doesn't. Here's what it does.",
       "Nobody's patch is magic. Here's what mine is for."],
      [(OPEN, 'Pack up, head shake, then the line.'),
       (MID, 'Patch on before the night, where we can see it. The Uber, the door, the friends.'),
       (CLOSE, 'Tomorrow morning: up and doing the thing, pack in frame. "For a better next day. That\'s it."')],
      on_screen='Not a cure. Just a better next day.', hot=1,
      why="Waterboy's rising 11-second ad is hooked on 'Waterboy is not a cure for your hangover', and its copy says 'Again, not a cure.' The contradiction in the first second breaks the ad pattern, and it is our compliance line said as a hook.",
      inspo=[('Waterboy', "'Waterboy is not a cure for your hangover.' Steal the first-second contradiction.", ATRIA + 'm2432062563971120'),
             ('The Cheers CEO', "'Plot twist: I make money telling people they SHOULDN'T drink.' Steal the honesty as a hook.", ATRIA + 'm1013483928135810')],
      do='Say "for a better next day" out loud, in your own words.', dont='List ingredients or explain how it works. Not a word of science.'),
    A('show', 'What am I?', 'Skit',
      'The patch answers yes-or-no questions until you guess it. Every answer is a pack fact and the reveal is the name.',
      'Any creator with a sense of humor and a free hand.',
      'The patch held up to the lens like a puppet. Your voice drops for it.',
      'The yes/no run, faster each time: "Do I smell? No. Do I fall off in the pool? No. Calories? No." A friend sniffs your arm and guesses wrong.',
      ['Do I smell? No. Do I fall off in the pool? No. Do I have calories? No. What am I?',
       'Twenty questions with the thing on my arm. Go.',
       'Guess what I am. You get three questions.'],
      [(OPEN, 'Puppet patch, the voice.'),
       (MID, 'The run of questions, one-word answers, cuts getting quicker. A friend sniffs your arm and guesses wrong.'),
       (CLOSE, 'It goes on your arm. "I\'m Party Patch." Then the door.')],
      on_screen='Smell? No. Pool? No. Calories? No.',
      why="Waterboy's October partner ad has the product interview itself ('Do I help with nausea? Yeah. What am I? You're Waterboy'). A yes/no run is a rhythm, the reveal is the brand name, and our old sniff test lives inside it.",
      inspo=[('Waterboy', 'The self-interview. Steal the yes/no run and the reveal.', ATRIA + 'm2202458353636113')],
      ads=['120243115360050266'], keep_from=['The sniff test'],
      do='One-word answers only. Stick to pack facts: scent-free, zero calories, water resistant.', dont='Ever answer "cure". And say water resistant, not waterproof.'),
    A('show', 'Peel. Stick. Door.', 'Six-second loop',
      'The last thing she does before she leaves takes three seconds. Five destinations, five loops, one afternoon.',
      'Anyone. Film five in one go.',
      'The front door, your hand on the handle, the other hand pressing the patch on. No face needed.',
      'The text swaps to where she is going: book club. Wedding. Bunco. Girls trip. Office party.',
      ["Three seconds at the door. That's it.",
       'Last thing before I leave. Every time.',
       'Peel. Stick. Go.'],
      [(OPEN, 'Door, handle, press.'),
       (MID, 'The press, close. Design to the lens for one beat.'),
       (CLOSE, 'Door opens, she is gone. Text with the destination, one word.')],
      on_screen='BOOK CLUB / WEDDING / BUNCO / GIRLS TRIP / OFFICE PARTY (one per loop)',
      why="The Good Patch's rank-1 ad for 80 days is a 6.8-second peel, stick, go loop. The action is the demo and it plays three times before a talking head finishes saying hello.",
      inspo=[('The Good Patch', 'The 6.8-second peel, stick, go loop at rank 1. Steal the loop.', ATRIA + 'm1472651414618482'),
             ('ZBiotics', 'A 3.9-second ad. Steal the nerve to be short.', ATRIA + 'm28182952651327819')],
      do='Film five destinations in one afternoon. Same door, different text.', dont='Add a voiceover. The loop is the point.'),
    A('show', 'Sunglasses inside', 'Trend',
      'At brunch, three friends wear sunglasses indoors and one does not. No one has to say anything.',
      'Any friend group. No talking needed.',
      'A brunch table, three pairs of sunglasses on, the camera pushes in on the one bare face.',
      "At 3 seconds she lifts her sleeve: the patch. Then she takes everyone's order.",
      ["POV: you're the only one at brunch not wearing sunglasses inside.",
       'Guess which one of us wore a patch last night.',
       'Same night. Different mornings. Pass the menu.'],
      [(OPEN, 'The table, the three pairs, the push-in.'),
       (MID, 'The sleeve, the patch, a tiny smile.'),
       (CLOSE, 'She orders for everyone. The others nod slowly.')],
      on_screen='Same night. Different mornings.',
      why="Waterboy's rising 6.5-second partner clip is one visual joke and one line. The sunglasses are the entire joke here, and the friends look fine, just quiet.",
      inspo=[('Waterboy', "A 6.5-second one-visual joke ('if I'm gonna suffer I'd at least like to be hydrated about it'). Steal the brevity.", ATRIA + 'm1759281172163994')],
      trend='Any trending brunch or "POV" sound.',
      do='Trending sound, under ten seconds, film it at a real brunch.', dont='Make the friends look sick. Sunglasses is as far as it goes.'),
    A('show', 'Reading reviews until I find one that is me', 'Screen record',
      'Scroll the Party Patch reviews on the site until one of them is her, and say so.',
      'Any creator. A phone and a face.',
      'Screen record of partypatch.com reviews scrolling, your thumb stops on one, you read it out loud.',
      'Each review gets a reaction and a "same". The third one gets a story from your own life.',
      ["Reading Party Patch reviews until I find one that's me.",
       'Reading your reviews until one of them is my exact life.',
       'Okay this review is literally me. Read it with me.'],
      [(OPEN, 'The scroll, the stop, the read.'),
       (MID, 'Three reviews, three reactions, the exact words on screen.'),
       (CLOSE, 'The pack to the lens. "Ordering the bundle." Say the offer from the site, if there is one.')],
      on_screen='The review text, exactly as it reads on the site.',
      why="Waterboy's rising ad reads a review out loud with the name: 'Cali D said for a recent bachelorette party I included Waterboy in hangover kits I made.' A review in a customer's words supplies the scene, and nobody has to make a claim.",
      inspo=[('Waterboy', "The named review read in the creator's own voice. Steal the 'same'.", ATRIA + 'm1541318970835567')],
      do='Only reviews that are live on partypatch.com, word for word, with the words on screen.', dont='Read anything that sounds medical. Skip any review that says cured, prevented or stopped.'),
    A('show', 'The hot tub test', 'Test',
      'Patches are famous for falling off wet. Film this one staying on through the hot tub on the girls trip, with a timer.',
      'Girls-trip creators with a pool or a hot tub.',
      'Patch on the arm, the arm goes into the water, a timer starts on screen. Nobody talks.',
      'Time jumps: 10 min, 40 min, 2 hours. The arm comes out each time. Still on.',
      ["Every patch I've tried falls off in the pool. Testing this one.",
       "Hot tub test. Girls trip edition. Timer's on.",
       "Water resistant, they said. Let's see."],
      [(OPEN, 'Arm in, timer on.'),
       (MID, 'The jumps, the arm out each time, a friend checking it.'),
       (CLOSE, 'Arm out, patch on, "still there." Then the night: patches on, one drink, the group.')],
      on_screen='0:00 / 0:40 / 2:00. Still on.',
      why="Built on what buyers of every patch say in reviews: residue, 'adhesive very tacky', falls off wet. Drdent's best creator ad is 20 silent seconds of the strips working, then 'look at that'. Answer the objection on camera and go quiet while you do it.",
      inspo=[('Reviews of other patches', 'The objection in their own words: residue, tacky, falls off in water. Answer it on camera, do not argue with it.'),
             ('Drdent', 'Twenty silent seconds of the product working, then a real reaction. Steal the quiet test.', ATRIA + 'm1563635778876692')],
      do='Only post it if it really stays on. If it does not, tell us and do not post.', dont='Say waterproof. The pack says water resistant.'),
    A('show', 'My old routine cost $40', 'Voiceover',
      'The drugstore run, the electrolyte sticks, the nap. Add it up, then put the patch on top of the receipt.',
      'Women who have tried everything.',
      'A CVS receipt unrolling across the counter, then the patch pack set down on top of it.',
      'The receipt lines get totaled on screen, one at a time, and the number keeps climbing.',
      ["My old next-day routine took a drugstore run and a nap. Here's the receipt.",
       'Forty dollars at CVS every time I went out. Now I spend this.',
       "Receipts from the old me. Let's add it up."],
      [(OPEN, 'The receipt unrolling, the pack on top.'),
       (MID, 'Each item from the bag beside its line on the receipt, the total climbing. Then the patch going on before a night out.'),
       (CLOSE, 'The pack price from the site, said out loud, next to the total.')],
      on_screen='THEN: $40 and a nap. NOW: the price on the site.',
      why="Waterboy's rising trade ad closes on 'my old routine required a small bank loan and a chemistry degree'. The cost of the old way sells without a single claim, and a climbing number is a rehook.",
      inspo=[('Waterboy', "'My old routine required a small bank loan.' Steal the cost-of-the-old-way frame and the climbing total.", ATRIA + 'm1058963726969933')],
      ads=['120249211680840266'],
      do='Real prices only, from a real receipt.', dont='Invent a discount. Say the price on the site the day you post.'),
]

SPEC = dict(act_id=ACT, slug='party-patch', brand=BRAND, sections=SECTIONS, angles=ANGLES)

# The worker's column caps. A string over the cap is cut by the editor later, so refuse it here.
CAPS = dict(title=120, argument=300, who=400, on_screen=200, do=400, dont=400, visual_hook=400, rehook=400, why=400)


def caps(angles):
    bad = []
    for a in angles:
        for k, n in CAPS.items():
            v = a.get(k)
            if v and len(v) > n:
                bad.append('%s: %s is %d chars (cap %d)' % (a['title'], k, len(v), n))
        for o in a['openers']:
            if len(o) > 200:
                bad.append('%s: opener is %d chars (cap 200)' % (a['title'], len(o)))
        for _, t in a['shots']:
            if len(t) > 400:
                bad.append('%s: shot is %d chars (cap 400)' % (a['title'], len(t)))
        for x in a['inspo']:
            if len(x[1]) > 300:
                bad.append('%s: inspo what is %d chars (cap 300)' % (a['title'], len(x[1])))
    if bad:
        raise SystemExit('CAP problems:\n  ' + '\n  '.join(bad))


if __name__ == '__main__':
    caps(ANGLES)
    write(SPEC, os.path.join(HERE, 'seed_amb_party_patch.sql'))
