"""One-time seed: Grunk Dolfer's creator link (Ambassadors), 2026-09-17.

Writes seed_grunk_dolfer.sql, which is run ONCE against the shared D1:
  npx wrangler d1 execute mobius-account-health --remote --file migrations/seed_grunk_dolfer.sql
Needs LUCIDE_NODES = path to lucide-static@1.46.0/icon-nodes.json.
Sources: docs/angles-grunk-dolfer.md (the site, 493 reviews, our 65 best-funded Meta ads,
competitor ads in Atria, the season shape from tw_daily) and Cole's calls on 2026-09-17
(beer in hand only, BFCM = BOGO + 30% off sitewide, crude hats are fine to film).
The link is seeded OFF (live = 0) for Cole's review.
Re-running it replaces Grunk Dolfer's sections, angles and proof, so do not run it
again once the team has edited the page.
"""
import json, os, secrets

ACT = 'act_313396960515158'
HERE = os.path.dirname(os.path.abspath(__file__))
NODES = json.load(open(os.environ['LUCIDE_NODES'], encoding='utf-8'))

def svg(name):
    return ''.join('<%s%s/>' % (t, ''.join(' %s="%s"' % (k, v) for k, v in a.items())) for t, a in NODES[name])

def q(v):
    if v is None:
        return 'NULL'
    if isinstance(v, (int, float)):
        return str(v)
    return "'" + str(v).replace("'", "''") + "'"

rid = lambda: secrets.token_hex(8)
OPEN, MID, CLOSE = 'Open · 0 to 3s', 'Middle', 'Close'

# Drawn season shape, 0-100 per ISO week (25 = a normal week). Real sales were not used:
# one Black Friday week (3.9x) flattens the line, Feb 2026 was partly a TikTok spend test,
# and wholesale is not in Shopify. See docs/angles-grunk-dolfer.md.
CUSTOM = {1: 20, 2: 20, 3: 25, 4: 26, 5: 34, 6: 36, 7: 38, 8: 32, 9: 30, 10: 30, 11: 33, 12: 32,
          13: 34, 14: 50, 15: 38, 16: 28, 17: 27, 18: 27, 19: 28, 20: 33, 21: 34, 22: 36, 23: 44,
          24: 55, 25: 42, 26: 36, 27: 34, 28: 25, 29: 24, 30: 23, 31: 24, 32: 24, 33: 23, 34: 18,
          35: 17, 36: 15, 37: 14, 38: 15, 39: 18, 40: 30, 41: 32, 42: 28, 43: 22, 44: 22, 45: 28,
          46: 32, 47: 45, 48: 100, 49: 55, 50: 65, 51: 64, 52: 55, 53: 40}

brand = dict(
    slug='grunk-dolfer', live=0, display_name='Grunk Dolfer', accent='#E05A25', logo_url=None,
    intro=("Grunk Dolfer makes loud polos for guys who golf to hang out, not to grind. Golf is a drinking sport, "
           "so we want videos that look like a real Saturday: the crew, the cart, the bad shots and the 19th hole. "
           "Pick an idea below, film it your way, and submit it on TRYBE like always."),
    about=("Loud, soft performance golf polos in prints you won't see on anyone else, plus hats, hoodies, koozies "
           "and the Den Caddy cart cooler. Relaxed dad bod fit, sizes small through 4XL, and 5XL on many prints. "
           "The mascot is Chunkman: a chubby guy holding a beer."),
    audience=("Weekend golfers, mostly guys 30 to 55, who play with the same buddies, have a beer on the cart and "
              "care more about the day than the score. Plenty have a dad bod and are proud of it. In gift season we "
              "also talk to the wives, girlfriends and kids buying for them."),
    submit_platform='TRYBE', submit_url=None, submit_label='Film this on TRYBE',
    avoid=[
        dict(title='Holding a product up to the camera in front of a wall or shelf, and nothing else happens',
             why='Most of what we get looks exactly like this. Take us to the course, the cart, the bar or the group chat instead.'),
        dict(title='A hat or accessory video that talks about polos',
             why='Talk about the thing you are showing. If it is a hat, sell the hat.'),
        dict(title='Stiff, posed shots smiling at the camera',
             why='Our posed ads lose. Real rounds, real buddies and real reactions win.'),
        dict(title="Opening on another brand's shirt",
             why='Keep the first seconds on Grunk. A plain unbranded polo is fine later in the video.'),
        dict(title='Shotgunning, chugging, or anyone who looks drunk',
             why='A beer in hand is the brand. Getting hammered on camera breaks ad rules.'),
        dict(title='Reading the product page out loud',
             why='Say one thing it does and show the rest. Nobody stops scrolling for a spec list.'),
    ],
    rules=[
        'Say what the site says: soft, 4-way stretch, moisture-wicking, breathable, wrinkle-resistant, relaxed dad bod fit.',
        'Never say UPF, sun protection, stain-proof or beer-proof about a polo. Never say HYDR18 prevents or cures hangovers.',
        'Sizes: every polo comes small through 4XL, and many prints go to 5XL. Check the product page before you say 5XL.',
        'Only mention an offer that is live on the site. The Black Friday deal (BOGO + 30% off sitewide) goes in Black Friday videos only.',
        "Don't quote a free shipping amount. \"Rated 4.9 stars\" is fine.",
        'If there is alcohol on screen, everyone is 21 or older. A beer in hand is fine. No chugging, and nobody drinks and drives, golf carts included.',
        "Show the print up close at least once and say the print's name.",
        'Film vertical, sound on, and show where you are in the first two seconds.',
        'Only film people who agreed to be in your video, on a course that allows filming.',
    ],
    season=dict(
        title='Fall golf season', until='Nov 25',
        line=("Scrambles, charity outings, guys' trips and cooler rounds. We are pushing the new fall drops "
              "(Brown Chunkman, Espresso Martini, Closet Grunk) and the Den Caddy with a free polo. "
              "Start your gift videos now so they are ready for November."),
        next='Black Friday (BOGO + 30% off sitewide) and holiday gifting, from Nov 26',
        highlight=['09-15', '11-25'], show_chart=True, color='#B45309', cap=None,
        mode='custom', custom={str(k): v for k, v in CUSTOM.items()},
    ),
    pdf=dict(
        line1='Grunk Dolfer creators,',
        line2="here's what to film.",
        intro=("Golf is a drinking sport, and our creator hub shows you how to film it: this week's hot picks, "
               "the fall drops, gift season, openers you can say word for word, and real videos that worked. "
               "It updates on its own, so check it before you shoot."),
        cta='Your creator hub',
        note='Opens right on your phone. No login, no app.',
        steps=['Open the hub and pick an idea',
               'Film it your way, starting with the opener',
               "Submit on TRYBE with the idea's name"],
    ),
    show_inspo=1,
)

SECTIONS = [
    dict(key='hot', name='Hot right now', line='What we are pushing hardest this week', icon='flame', color='#DC2626', pinned=1),
    dict(key='fall', name='Fall golf season', line='New fall drops, scrambles, guys\' trips and the Den Caddy. Until Nov 25.', icon='leaf', color='#B45309'),
    dict(key='gift', name='Gifts and Black Friday', line='Wives, kids and buddies shopping for the golfer who has everything. Black Friday is BOGO + 30% off sitewide.', icon='gift', color='#15803D'),
    dict(key='drink', name='Golf is a drinking sport', line='Our line, and nobody else in golf owns it. The round, the cart, the 19th hole.', icon='beer', color='#CA8A04'),
    dict(key='crew', name='The crew', line='Scramble teams, buddy trips, bachelor parties. Guys who buy together.', icon='users', color='#1D4ED8'),
    dict(key='fit', name='Dad bod approved', line='Real guys, real sizes. The fit that competitors get wrong.', icon='shirt', color='#7C3AED'),
    dict(key='ev', name='Always works', line='Ideas that sell any month of the year.', icon='sparkles', color='#0F766E'),
    dict(key='spring', name='Masters to Father\'s Day', line='Masters week, watch parties and Father\'s Day. Switch on in March.', icon='flag', color='#166534', enabled=0),
]

def A(sec, title, fmt, argument, who, openers, shots, on_screen=None, do=None, dont=None, lever=None,
      products='Grunk Dolfer polos', hot=0, trend=None, ads=()):
    return dict(sec=sec, title=title, format=fmt, argument=argument, who=who, openers=openers,
                shots=[dict(label=l, text=t) for l, t in shots], on_screen=on_screen, do=do, dont=dont,
                lever=lever, products=products, hot=hot, trend=trend, ads=list(ads))

ANGLES = [
    # ---------------- Fall golf season ----------------
    A('fall', 'The new drop, ranked by beers deep', 'Try-on haul',
      "The fall drop is here, and the only fair way to rank it is how many beers deep you'd be wearing each one.",
      'The collector who buys every drop, and anyone who likes a ranking.',
      ['Ranking the new Grunk drop by how many beers deep I am.',
       'New Grunk just landed. One of these is a four beer shirt.',
       'I tried on the whole fall drop so you don\'t have to.'],
      [(OPEN, 'Hold all the new pieces fanned out to camera, a beer in the other hand. Say the opener.'),
       (MID, 'Try each one on, fast cuts. Say the print name, give it a beers-deep score (1 to 5) and one reason. Big number on screen for each.'),
       (CLOSE, 'Crown the winner. Close-up on the print, then you walking out the door in it.')],
      on_screen='NEW DROP: RANKED BY BEERS DEEP',
      do='Say every print name out loud: Brown Chunkman, Espresso Martini, Closet Grunk, Bearly Sober.',
      dont='Rank them all the same. Pick a clear winner and a clear loser, that is the fun.',
      lever='Curiosity', products='Fall drops: Brown Chunkman, Espresso Martini, Closet Grunk, Bearly Sober', hot=1,
      ads=['120242005365750115']),
    A('fall', 'Closet Grunk: yes, you can wear it to dinner', 'Couple skit',
      'Closet Grunk looks like a normal shirt from across the room, so you can finally wear Grunk to dinner and win the argument.',
      'The guy whose partner always vetoes the loud polo at the restaurant.',
      ['"You are not wearing a golf shirt to dinner." Watch this.',
       'She said no golf shirts at dinner. She didn\'t say no Grunk.',
       'The one Grunk shirt my wife lets out of the house.'],
      [(OPEN, 'Partner blocks the door: "You are not wearing a golf shirt to dinner."'),
       (MID, 'He comes back in the Closet Grunk button down. She checks it from across the room: "Fine. That one is nice." Wide shot so it looks plain.'),
       (CLOSE, 'Cut to the restaurant. Slow push in to the tonal camo up close. He winks at camera.')],
      on_screen='From across the room: normal. Up close: Grunk.',
      do='Shoot the reveal wide, then close. The joke is the distance.',
      dont='Let the partner be mean. Keep it teasing.',
      lever='Humor', products='Closet Grunk button downs', hot=1),
    A('fall', 'The Den Caddy rolls up to the first tee', 'Reaction reveal',
      'Everyone else brings a bag; you bring a cold 24-can bar to the first tee, and the polo comes free with it.',
      'The guy who hosts the round, and every buddy who wishes he did.',
      ['Some guys show up with a golf bag. I showed up with this.',
       'My buddies when I rolled the Den Caddy up to the first tee.',
       'It came with a free polo. I\'m not even mad.'],
      [(OPEN, 'Film your buddies at the first tee. Roll the Den Caddy into frame. Get their real faces.'),
       (MID, 'Open it up: cans inside, cold. Hand them out. Show the free polo you are wearing.'),
       (CLOSE, 'Group cheers on the tee box, Den Caddy in the middle of the shot.')],
      on_screen='The Den Caddy. Your polo is on us.',
      do='Say it holds 20 to 24 cans and that a polo comes free with it (check the site that the free polo is still on).',
      dont='Show the caddy with nobody around. The reactions sell it.',
      lever='Status', products='Den Caddy + free polo', hot=1,
      ads=['120246364176890115']),
    A('fall', 'Espresso Martini at the turn', 'Bar POV',
      'The Espresso Martini polo is the only shirt that matches the best drink at the turn.',
      'The guy who treats the turn like happy hour.',
      ['Ordered an espresso martini at the turn. Matched my shirt.',
       'If your polo matches your drink, you are winning the round.',
       'Front nine: bad. Espresso martini at the turn: perfect.'],
      [(OPEN, 'POV at the turn: the bartender slides an espresso martini across the counter.'),
       (MID, 'Hold the drink up next to the polo. Close-up of the print, then the drink.'),
       (CLOSE, 'Cheers to camera. Walk back to the cart for the back nine.')],
      on_screen='The drink matches the shirt.',
      dont='Make it about getting drunk. One drink, a good time.',
      lever='Identity', products='Espresso Martini polo'),
    A('fall', 'Fall scramble fit check', 'On-course fit check',
      'Fall scramble season is when a loud polo and a hoodie do the talking before you even hit a shot.',
      'Guys playing fall scrambles, outings and charity tournaments.',
      ['Fall scramble fit check.',
       'Cold morning scramble. Hoodie off by hole 3.',
       'Rating my team\'s scramble fits.'],
      [(OPEN, 'Parking lot or range, cold morning. Hoodie on, show it head to toe.'),
       (MID, 'Hoodie comes off, the polo underneath. Quick close-up of each print. Your team does the same.'),
       (CLOSE, 'Team shot at the scramble sign or the first tee.')],
      on_screen='FALL SCRAMBLE FIT CHECK',
      do='Show both layers: the hoodie and the polo under it.',
      lever='Belonging', products='Polos + hoodies',
      trend='Any "fit check" or outfit-reveal sound.'),
    A('fall', 'Going as a golfer for Halloween', 'Costume skit',
      'The easiest Halloween costume is already in your closet: a loud polo, a beer and a bad swing.',
      'The guy who forgot about the Halloween party until today.',
      ["Forgot my Halloween costume. Went as a golfer.",
       'My costume this year: guy who says he\'ll only have one beer on the course.',
       'Best Halloween costume under $70.'],
      [(OPEN, 'Everyone at the party in real costumes. You walk in wearing a Grunk polo, beer in hand.'),
       (MID, 'Someone asks what you are. "Golfer." Cut to you doing a terrible practice swing in the kitchen.'),
       (CLOSE, 'Close-up of the print. "Best costume here." Ends Oct 31.')],
      on_screen='Costume: golfer. Effort: none.',
      dont='Post it after Oct 31.',
      lever='Humor', products='Chunkman polos, Grunk Dolfer polos'),

    # ---------------- Gifts and Black Friday ----------------
    A('gift', 'How long until he notices', 'Gift prank',
      'A Grunk polo is the gift that gets a real reaction, and the fun part is watching him find the joke in the print.',
      'Wives and girlfriends buying for a golfer.',
      ['I bought my husband a golf polo. Let\'s see how long it takes him to notice.',
       'He thinks it\'s a normal golf shirt.',
       'Timing how long until he sees the Chunkman.'],
      [(OPEN, 'Whisper the opener to camera while he is in the other room. Show the polo (Chunkman or Drinko prints work best).'),
       (MID, 'Hand it over. Keep the camera on his face. Timer on screen.'),
       (CLOSE, 'He spots it. Real reaction. Stop the timer, close-up of the print.')],
      on_screen='Timer: how long until he notices',
      do='Keep the camera on his face the whole time. The reaction is the ad.',
      dont='Tell him before you film.',
      lever='Curiosity', products='Chunkman or Drinko polos', hot=1),
    A('gift', 'The golfer who has everything', 'Voiceover list',
      "He already has every golf gadget; he doesn't have a shirt with a personality.",
      'Anyone buying for a dad, husband or buddy who is hard to shop for.',
      ['What do you get the golfer who has everything?',
       'He has 40 golf shirts. They are all navy.',
       '"Finally found something he didn\'t have." A real review.'],
      [(OPEN, 'Voiceover over shots of his gear: rangefinder, 6 drivers, a closet of plain polos.'),
       (MID, 'The loud Grunk polo appears in the middle of the plain ones. Close-up of the print.'),
       (CLOSE, 'Him wearing it at the course. "He wore it every Saturday since."')],
      on_screen='He has everything. Except this.',
      dont='Say anything about him you don\'t know is true. Keep it your story.',
      lever='Relief', products='Grunk Dolfer polos, gift cards', hot=1),
    A('gift', 'Black Friday haul: BOGO + 30% off', 'Unboxing',
      'Black Friday is the one week to stock up: BOGO plus 30% off sitewide.',
      'Collectors and gift buyers who wait for the deal. Black Friday week only.',
      ['Grunk Black Friday haul. BOGO plus 30% off everything.',
       'I waited all year for this sale.',
       'How many polos I got for Black Friday.'],
      [(OPEN, 'Box on the table, tape cut, beer next to it. Say the deal.'),
       (MID, 'Pull out each piece, say the print name and who it is for (you, your dad, your buddy).'),
       (CLOSE, 'Everything laid out. Say the deal once more and that it ends Cyber Monday.')],
      on_screen='BOGO + 30% OFF SITEWIDE',
      do='Say the deal exactly as it is on the site.',
      dont='Post this before Black Friday week or after Cyber Monday.',
      lever='Value', products='Everything (Black Friday)'),
    A('gift', 'Dad and lil dude', 'Matching reveal',
      'The best gift for a golf dad is a mini version of himself in the same polo.',
      'Moms buying for dad and the kids, and golf dads.',
      ['Matching polos with my kid. He hits it straighter than me.',
       'Mini me, same polo.',
       'Dad and lil dude, range day.'],
      [(OPEN, 'Dad walks into frame in a polo. The kid walks in behind him in the same print.'),
       (MID, 'Range or putting green together. Both swings side by side.'),
       (CLOSE, 'High five, close-up of both prints.')],
      on_screen='Dad and lil dude',
      do='Kids polos come in White Neon Rose, Island Boy and the Hawaiian prints. Check the site.',
      dont='Show the kid with any alcohol in the shot.',
      lever='Belonging', products='Kids polos + matching adult polos'),
    A('gift', 'The stocking stuffer drawer', 'Top-down flat lay',
      'Grunk makes stocking stuffers golfers actually use, all under $20.',
      'Gift buyers filling stockings and secret santa.',
      ['Stocking stuffers for the golfer, all under 20 bucks.',
       'Everything in this stocking is for the cart.',
       'Secret santa for the golf guy, sorted.'],
      [(OPEN, 'Top-down: an empty stocking on the table.'),
       (MID, 'Drop each item in, one per beat: magnetic koozie, ball marker, divot tool, towel. Say what each does.'),
       (CLOSE, 'Full stocking. Cut to him using the koozie on the cart.')],
      on_screen='Golf stocking stuffers under $20',
      do='Check prices on the site before you say them.',
      lever='Value', products='Koozies, ball markers, divot tools, towels'),
    A('gift', 'Christmas money, spent', 'Screen record',
      'Gift cards and Christmas cash go straight to the polo he actually wanted.',
      'Guys who got a gift card or Christmas cash. Dec 26 to Jan 5.',
      ['What I bought with my Christmas money.',
       'Got a Grunk gift card. Here\'s the damage.',
       'My wife gave me a gift card so I would stop dropping hints.'],
      [(OPEN, 'Screen record: the gift card or the Venmo from grandma.'),
       (MID, 'Scroll the site, add polos to the cart, talk through why each one.'),
       (CLOSE, 'Checkout, then cut to the box arriving.')],
      on_screen='Christmas money: spent',
      dont='Show a real card number or balance.',
      lever='Identity', products='Gift cards, polos'),

    # ---------------- Golf is a drinking sport ----------------
    A('drink', 'Rated for 19 holes', 'Real round POV',
      'Golf is a drinking sport, so the polo has to last the round and the 19th hole.',
      'The Saturday foursome that ends every round at the bar.',
      ['Most polos quit after 18. Ours are rated for 19.',
       'Hole 1 to the 19th hole in one shirt.',
       'Golf is a drinking sport. Dress like it.'],
      [(OPEN, 'First tee, beer in the cup holder, the crew in loud polos. Text: RATED FOR 19 HOLES.'),
       (MID, 'Quick real moments: a bad shot, a good one, the cart, a cheers on the green. Text beats: 4-way stretch, moisture-wicking, breathable.'),
       (CLOSE, 'The 19th hole bar, everyone still looking sharp. Cheers to camera.')],
      on_screen='MOST POLOS QUIT AFTER 18.',
      do='Use real footage from a real round. The shakier and realer, the better.',
      dont='Show chugging or anyone who looks drunk.',
      lever='Identity',
      ads=['120249439447190115', '120249439374960115']),
    A('drink', 'Rate this polo at the 19th hole', 'Bar interviews',
      "Strangers at the bar can't stop commenting on the polo, so let them score it.",
      'Anyone who wonders whether a loud polo is too much.',
      ['I asked strangers at the 19th hole to rate my polo.',
       'Walking up to golfers at the bar: rate this shirt, 1 to 10.',
       'Nobody gave it under an 8.'],
      [(OPEN, 'At the clubhouse bar, mic in hand: "Rate my polo, 1 to 10."'),
       (MID, '4 to 6 quick answers with their score on screen. Keep the funny ones.'),
       (CLOSE, 'Someone asks where you got it. Close-up of the print.')],
      on_screen='Rate this polo 1 to 10',
      do='Get permission from everyone on camera. Keep the real scores, even the low ones.',
      dont='Script the answers.',
      lever='Social proof'),
    A('drink', "The cart girl's favourite foursome", 'POV from the cart',
      'The cart girl remembers the group in the loud polos.',
      'Guys who know the beer cart is the best part of the round.',
      ['POV: you are the cart girl and this foursome rolls up.',
       'Donde esta la cart girl? Right here.',
       'The cart girl said we were her favourite group. We tipped well.'],
      [(OPEN, 'POV from the beer cart pulling up to a foursome in loud polos (or the Donde Esta La Cart Girl hat).'),
       (MID, 'The group orders, jokes, tips. Quick cuts of each polo.'),
       (CLOSE, 'Cart drives off, the group waves. Text: see you on the back nine.')],
      on_screen='POV: the cart girl\'s favourite group',
      do='Keep it friendly and respectful. The joke is the guys, not her.',
      lever='Belonging', products='Polos, Donde Esta La Cart Girl hat'),
    A('drink', 'Hole 1 vs hole 18', 'Heat check timelapse',
      'A hot day and a few beers deep, and the polo still looks like it did on the first tee.',
      'Guys who play in the heat and hate a sweaty, wrinkled shirt by the back nine.',
      ['Hole 1 vs hole 18. Same shirt, 95 degrees.',
       'Four beers and 18 holes later.',
       'Checking my polo every 6 holes.'],
      [(OPEN, 'Hole 1: show the polo, the temperature on your phone.'),
       (MID, 'Checks at hole 6, 12 and 18: collar, back, sleeves. Honest look each time.'),
       (CLOSE, 'Side by side: hole 1 and hole 18.')],
      on_screen='HOLE 1 vs HOLE 18',
      do='Only say what you see. Moisture-wicking and wrinkle-resistant are the claims.',
      dont='Say it never shows sweat or that it is stain-proof.',
      lever='Proof'),
    A('drink', 'How many beers fit in the Den Caddy', 'Count demo',
      'The Den Caddy holds 20 to 24 cans, which is enough for the whole foursome.',
      'The guy who buys the beer for the group.',
      ['How many beers fit in the Den Caddy? Let\'s count.',
       'Loading the Den Caddy for a Saturday foursome.',
       'This is the only caddy I tip in beer.'],
      [(OPEN, 'Empty Den Caddy, a pile of cans next to it.'),
       (MID, 'Load them in, counting out loud, number on screen.'),
       (CLOSE, 'Full. Roll it onto the cart. Mention the free polo if it is still on the site.')],
      on_screen='Count with me',
      do='Use standard 12 oz cans. The site says 20 to 24 fit.',
      lever='Proof', products='Den Caddy'),
    A('drink', 'The weekend golfer in the wild', 'Nature doc voiceover',
      'The weekend golfer is a rare species, and you can spot him by his polo.',
      'Anyone who loves a nature-documentary parody.',
      ['Here, in his natural habitat, the weekend golfer.',
       'Observe the male golfer. His plumage is loud.',
       'The weekend golfer approaches the beer cart.'],
      [(OPEN, 'Hushed nature-doc voice over a wide shot of your buddy on the tee.'),
       (MID, 'Narrate his habits: the practice swing, the breakfast ball, the beer cart. Zoom in on the polo: his plumage.'),
       (CLOSE, 'He hits a bad shot and celebrates anyway. "Remarkable."')],
      on_screen='The weekend golfer, in the wild',
      do='Commit to the voice. The more serious, the funnier.',
      lever='Humor'),

    # ---------------- The crew ----------------
    A('crew', "Field of 8: outfitting the guys' trip", 'Group walkout',
      'The trip photo looks legendary when the whole crew shows up in loud polos.',
      'The guy planning the guys\' trip, bachelor party or scramble team.',
      ['Welcome to the bachelor open. Field of 8.',
       'I outfitted the whole guys\' trip in Grunk.',
       'The groom gets the loudest polo. That\'s the rule.'],
      [(OPEN, 'Title card: THE FIELD. Then each guy walks out in slow motion, name and print on screen.'),
       (MID, 'The groom or trip captain last, in the loudest print.'),
       (CLOSE, 'Group photo on the first tee.')],
      on_screen='THE FIELD',
      do='Use a sports-intro sound. Say each print name.',
      lever='Belonging', trend='Any walkout or starting-lineup sound.'),
    A('crew', 'Nobody wants to draw this team', 'Arrival reaction',
      'Show up to the scramble matching and loud, and the other teams notice before you tee off.',
      'Scramble and outing teams.',
      ['Nobody at the scramble wanted to draw our team.',
       'We showed up like this and the other teams gave up.',
       'Scramble team: we can\'t putt, but look at us.'],
      [(OPEN, 'The team walks from the parking lot to the check-in table in matching or clashing Grunk.'),
       (MID, 'Reactions from other players, a team photo, a quick real shot.'),
       (CLOSE, 'The scoreboard (win or lose) and the team still looking good.')],
      on_screen='The team nobody wanted to draw',
      do='Get real reactions. Ask before filming other teams.',
      lever='Status'),
    A('crew', 'Foursome roll call', 'Trend',
      'Every guy in the group has a print that matches his personality.',
      'Buddy groups.',
      ['Foursome roll call.',
       'Every group has these four golfers.',
       'Which one is your buddy?'],
      [(OPEN, 'Roll call trend: each guy steps into frame.'),
       (MID, 'Label each one: the sandbagger, the one who loses 6 balls, the beer guy, the one who takes it too seriously. Each in a different print.'),
       (CLOSE, 'All four together. Caption asks: which one are you?')],
      on_screen='Which one are you?',
      do='Ask the question in the caption. It gets comments.',
      lever='Belonging', trend='Any roll-call or "every group has" sound.'),
    A('crew', 'The group chat picked the polos', 'Screen record',
      "The crew votes, and the loudest print wins every time.",
      'Buddy groups planning a trip or event.',
      ['Let the group chat pick our trip polos. Big mistake.',
       'Group chat vote: which Grunk for the scramble?',
       'We voted. Democracy failed.'],
      [(OPEN, 'Screen record the group chat: a poll with 3 prints.'),
       (MID, 'Replies roll in, the loudest print wins.'),
       (CLOSE, 'Cut to the whole crew wearing it on the course.')],
      on_screen='The group chat decided',
      dont='Show real names or phone numbers.',
      lever='Belonging'),
    A('crew', 'Loser buys the polos', 'Match with a payoff',
      'The best side bet is the loser buying everyone a new Grunk.',
      'Competitive buddy groups.',
      ['Loser buys everyone a new polo.',
       'Worst score today pays for the Grunk order.',
       'I lost. Here\'s what it cost me.'],
      [(OPEN, 'Set the bet on the first tee.'),
       (MID, 'Quick highlights and lowlights. Scores on screen.'),
       (CLOSE, 'The loser opens the site on his phone, mad. Cut to everyone in new polos next round.')],
      on_screen='Loser buys the polos',
      lever='Humor'),

    # ---------------- Dad bod approved ----------------
    A('fit', 'Small through 5XL on real bodies', 'Size lineup',
      'Grunk fits real golfers, from small to big guys, without clinging to the gut.',
      'Big guys burned by brands that run small and tight.',
      ['Same polo, five different guys.',
       'Grunk on every body type. Here\'s the fit.',
       'Big guys, this one\'s for you.'],
      [(OPEN, 'A lineup of guys of different sizes, same print.'),
       (MID, 'Each says his height, weight and size on screen, and one word on the fit.'),
       (CLOSE, 'Whole lineup does a swing at the same time.')],
      on_screen='Height / weight / size',
      do='Use each guy\'s real size.',
      dont='Say every print comes in 5XL. Check the product page.',
      lever='Relief'),
    A('fit', 'The full swing test', 'Slow motion',
      'The 4-way stretch lets you swing out of your shoes without the shirt fighting you.',
      'Guys whose polos pull across the shoulders on the swing.',
      ['Full swing test in a Grunk polo.',
       'Slow motion. Watch the shoulders.',
       'My swing is bad. My shirt is not the problem.'],
      [(OPEN, 'Driver, full swing, slow motion from behind.'),
       (MID, 'Same swing from the front. Point out the stretch across the back and shoulders.'),
       (CLOSE, 'The ball goes wherever it goes. You laugh.')],
      on_screen='4-WAY STRETCH',
      dont='Say it never comes untucked. Just show the swing.',
      lever='Proof'),
    A('fit', 'I fit the Chunkman description', 'Mirror talk',
      'Chunkman is proud of his dad bod, and the polo is cut for it.',
      'Guys with a beer belly who are done hiding it.',
      ['I fit the Chunkman description. So I bought the shirt.',
       'Dad bod approved. Literally, it says so.',
       'This polo was made for guys shaped like me.'],
      [(OPEN, 'Mirror, polo on, pat the belly. Say the opener.'),
       (MID, 'Point to the Chunkman logo and then yourself. Show the fit: no cling, room to move.'),
       (CLOSE, 'Walk out to the car with the clubs.')],
      on_screen='Dad bod approved',
      do='Be proud of it. Self-deprecating, never sad.',
      lever='Identity', products='Chunkman polos',
      ads=['120237891762730115']),

    # ---------------- Always works ----------------
    A('ev', 'Across the fairway, then up close', 'Print reveal',
      'From across the fairway it is a loud polo; up close there is a whole story in the print.',
      'Everyone. This is how our best ads sell.',
      ['You can\'t tell from over there. Come closer.',
       'From the tee box vs up close.',
       'Wait for the close-up.'],
      [(OPEN, 'Wide shot from 30 yards: you on the tee.'),
       (MID, 'Hard cut to a close-up of the print. Slow pan across the details.'),
       (CLOSE, 'Say the print name. Back to the wide shot, you hit.')],
      on_screen='From the tee box vs up close',
      do='Pick the loudest print you own. The print is the hero.',
      lever='Curiosity',
      ads=['120237114684920115']),
    A('ev', '"Where did you get that?" tally', 'Round counter',
      'Wear a Grunk polo for one round and count how many people ask where you got it.',
      'Anyone who wants to be the guy the group notices.',
      ['Counting how many people ask about my polo in one round.',
       'I got asked "where did you get that" this many times.',
       'Wore it once. Got stopped four times.'],
      [(OPEN, 'Parking lot: counter on screen at 0.'),
       (MID, 'Each time someone asks, the counter goes up. Keep the real moments.'),
       (CLOSE, 'Final count at the 19th hole. Close-up of the print.')],
      on_screen='"Where did you get that?" count: 0',
      do='Only count real asks. The real number is the proof.',
      lever='Social proof',
      ads=['120239652839210115']),
    A('ev', "Retire dad's polos", 'Closet purge',
      'Nothing against Dad, but the plain stripes and safe navy have to go.',
      'The guy with a closet full of boring country club polos.',
      ['Nothing against Dad. But these have to go.',
       'I retired every boring polo I own.',
       'Closet cleanout: golf edition.'],
      [(OPEN, 'Closet full of plain navy and striped polos.'),
       (MID, 'Pull them out one by one into a bag, a quick roast for each. Then hang the Grunk polos.'),
       (CLOSE, 'Closet before and after, then you in the loudest one.')],
      on_screen='Retired: every boring polo',
      do='Keep the plain polos unbranded on camera.',
      lever='Identity',
      ads=['120249603609520115']),
    A('ev', 'Show and tell: my favourite print', 'Handheld show and tell',
      'The easiest way to sell a Grunk polo is to hold it up and talk about why you love it.',
      'Anyone new to the brand.',
      ['There\'s a blue version? Yes.',
       'My favourite Grunk print, and why.',
       'Let me show you the details on this one.'],
      [(OPEN, 'Move the product at the lens in the first second (or wave the Chunkman plush in front of it). Text on screen right away.'),
       (MID, 'Talk through the print, the feel, the fit and the sizes. Close-ups.'),
       (CLOSE, 'Put it on, or show it at the course.')],
      on_screen='Put the print name on screen in the first second',
      do='Film it somewhere real: the course, the cart, your garage bar. Not a blank wall.',
      dont='Talk about polos while showing a hat.',
      lever='Proof',
      ads=['120244036055130115', '120242222297840115', '120250165745930115']),
    A('ev', 'The lucky shirt', 'Scorecard vs outfit split',
      'You might not play better in it, but plenty of guys swear they do.',
      'Superstitious golfers, which is all of them.',
      ['First time I wore it, I broke 100. Just saying.',
       'My scorecard vs my outfit.',
       'Shot 104. Won the fit.'],
      [(OPEN, 'Split screen: left the scorecard, right the full outfit.'),
       (MID, 'Tell the story of your best (or funniest) round in the shirt.'),
       (CLOSE, 'The shirt goes back in the closet on a special hanger.')],
      on_screen='Scorecard vs outfit',
      do='Tell your real story, good or bad.',
      dont='Say the shirt will make anyone play better.',
      lever='Humor'),
    A('ev', "Collector's closet tour", 'Closet tour',
      "One Grunk polo turns into a collection, and every print has a story.",
      'Collectors and Drinking Club members, and anyone who has two already.',
      ['It started with one polo.',
       'Closet tour: my Grunk collection.',
       'My wife says I have a problem. Here is the problem.'],
      [(OPEN, 'Open the closet: a wall of Grunk.'),
       (MID, 'Pull out your top 5 and say where you wore each one.'),
       (CLOSE, 'The empty hanger for the next drop.')],
      on_screen='It started with one polo',
      lever='Belonging', products='Grunk Dolfer polos, Drinking Club'),
    A('ev', "You're not wearing that to dinner", 'Couple argument',
      "A Grunk polo is too good to take off after the round, whatever your partner says.",
      'Couples, and guys who wear their golf shirt everywhere.',
      ['"You cannot wear that polo to dinner."',
       'Me leaving the course and going straight to dinner.',
       'She said change. I said no.'],
      [(OPEN, 'Partner at the door: "You cannot wear that polo to dinner."'),
       (MID, '"Why? What\'s wrong with it?" Close-up of the print. One-line comeback: "Golf is a drinking sport, and dinner has drinks."'),
       (CLOSE, 'Cut to dinner. He is wearing it. She is laughing.')],
      on_screen='"You cannot wear that to dinner"',
      do='Keep it under 15 seconds. Conflict first line.',
      lever='Humor'),

    # ---------------- Masters to Father's Day (off until March) ----------------
    A('spring', 'More muni than Masters', 'Watch party',
      "You're not getting a green jacket, but you can host the best Masters party in the loudest shirt.",
      'Party-golf fans watching the Masters with the crew.',
      ['More muni than Masters.',
       'Masters Sunday, my living room edition.',
       'The Smashters hat is better than a green jacket. Hot take.'],
      [(OPEN, 'Living room watch party, Masters on the TV (don\'t show the broadcast logo), the crew in Smashters hats and green polos.'),
       (MID, 'Putting contest on the carpet, drinks, reactions to the TV.'),
       (CLOSE, 'Someone "wins" and gets a Smashters hat instead of a jacket.')],
      on_screen='More muni than Masters',
      dont='Show the Masters logo or broadcast on screen. Say "Masters week", nothing official.',
      lever='Belonging', products='Smashters hat, Yellow ChunkMan polo, Grunk Masters Hat',
      ads=['120250256805700115']),
    A('spring', "Father's Day: the one he'll actually wear", 'Gift reveal',
      'Skip the tie. Dad will actually wear a Grunk polo every Saturday.',
      "Kids and wives shopping for Father's Day.",
      ["Father's Day gift he'll actually wear.",
       'Dad opens his Father\'s Day gift. Watch his face.',
       'Last year I got him a tie. This year I got it right.'],
      [(OPEN, 'Dad opens the gift. Camera on his face.'),
       (MID, 'He holds it up, reads the print, laughs.'),
       (CLOSE, 'Cut to him wearing it on the course that weekend.')],
      on_screen="Father's Day, done right",
      lever='Relief', products='Polos, Grunk Fathers, kids matching polos'),
]

sql = ["-- Grunk Dolfer creator link seed (see seed_grunk_dolfer.py)",
       f"DELETE FROM p_amb_proof WHERE act_id = {q(ACT)};",
       f"DELETE FROM p_amb_angle WHERE act_id = {q(ACT)};",
       f"DELETE FROM p_amb_section WHERE act_id = {q(ACT)};",
       f"DELETE FROM p_amb_brand WHERE act_id = {q(ACT)};"]
b = brand
sql.append(
    "INSERT INTO p_amb_brand (act_id, slug, live, display_name, intro, about, audience, accent, logo_url, "
    "submit_platform, submit_url, submit_label, avoid_json, rules_json, season_json, show_inspo, pdf_json) VALUES (" +
    ', '.join(q(x) for x in [ACT, b['slug'], b['live'], b['display_name'], b['intro'], b['about'], b['audience'],
                             b['accent'], b['logo_url'], b['submit_platform'], b['submit_url'], b['submit_label'],
                             json.dumps(b['avoid']), json.dumps(b['rules']), json.dumps(b['season']), b['show_inspo'],
                             json.dumps(b['pdf'])]) + ");")
sec_id = {}
for i, s in enumerate(SECTIONS):
    sid = rid(); sec_id[s['key']] = sid
    sql.append("INSERT INTO p_amb_section (id, act_id, name, line, icon, icon_svg, color, enabled, pinned, sort) VALUES (" +
               ', '.join(q(x) for x in [sid, ACT, s['name'], s['line'], s['icon'], svg(s['icon']), s['color'],
                                        s.get('enabled', 1), s.get('pinned', 0), i]) + ");")
hot_n = 0
sort_by_sec = {}
for a in ANGLES:
    aid = rid()
    sort_by_sec[a['sec']] = sort_by_sec.get(a['sec'], 0) + 1
    if a['hot']:
        hot_n += 1
    sql.append("INSERT INTO p_amb_angle (id, act_id, section_id, hot, hot_sort, sort, status, title, argument, who, products, "
               "format, lever, openers_json, shots_json, on_screen, do_text, dont_text, trend) VALUES (" +
               ', '.join(q(x) for x in [aid, ACT, sec_id[a['sec']], a['hot'], hot_n if a['hot'] else 0, sort_by_sec[a['sec']],
                                        'live', a['title'], a['argument'], a['who'], a['products'], a['format'], a['lever'],
                                        json.dumps(a['openers']), json.dumps(a['shots']), a['on_screen'], a['do'], a['dont'],
                                        a['trend']]) + ");")
    for k, ad in enumerate(a['ads']):
        sql.append("INSERT INTO p_amb_proof (id, act_id, angle_id, kind, ad_id, shown, sort) VALUES (" +
                   ', '.join(q(x) for x in [rid(), ACT, aid, 'meta', ad, 1, k + 1]) + ");")

open(os.path.join(HERE, 'seed_grunk_dolfer.sql'), 'w', encoding='utf-8').write('\n'.join(sql) + '\n')
print(len(ANGLES), 'angles,', len(SECTIONS), 'sections,', sum(len(a['ads']) for a in ANGLES), 'tagged ads')
