"""One-time seed: Party Patch's creator link (Ambassadors), 2026-09-16.

Writes seed_party_patch.sql, which is run ONCE against the shared D1:
  npx wrangler d1 execute mobius-account-health --remote --file migrations/seed_party_patch.sql
Sources: Chris's two Sept-Dec emails (Tonight / Tomorrow, the testing matrix, the
social calendar), Party Patch's best Meta ads since May 2026, and the Mobius angle
framework (an angle is the reason to buy; openers and shots are how it is filmed).
Re-running it replaces Party Patch's sections, angles and proof, so do not run it
again once the team has edited the page.
"""
import json, os, secrets

ACT = 'act_1033194534145987'
HERE = os.path.dirname(os.path.abspath(__file__))
NODES = json.load(open(os.environ['LUCIDE_NODES'], encoding='utf-8'))

def svg(name):
    return ''.join('<%s%s/>' % (t, ''.join(' %s="%s"' % (k, v) for k, v in a.items())) for t, a in NODES[name])

def q(v):
    if v is None:
        return 'NULL'
    if isinstance(v, (int, float)):
        return str(v)
    return "'" + str(v).replace("'", "''") + "'"

rid = lambda: secrets.token_hex(8)
OPEN, MID, CLOSE = 'Open · 0 to 3s', 'Middle', 'Close'

brand = dict(
    slug='party-patch', live=0, display_name='Party Patch', accent='#1E88E5', logo_url=None,
    intro=("Party Patch is the patch she puts on before a night out so tomorrow still happens. "
           "We need videos that look like her real life: busy, social, funny and a little chaotic. "
           "Pick an angle below, film it your way, and submit it on TRYBE like always."),
    about=("A vitamin-infused patch you stick on before drinks, for a better day after a night out. "
           "Scent-free, zero calories and water resistant. It comes in fun designs, including the new "
           "Halloween bundle: three designs, six patches."),
    audience=("Moms and women 30 to 50 with a packed calendar. She is not trying to party harder. "
              "She wants to enjoy tonight and still show up tomorrow: soccer at 8, school drop-off, work, "
              "the pumpkin patch with the kids."),
    submit_platform='TRYBE', submit_url=None, submit_label='Film this on TRYBE',
    avoid=[
        dict(title='Talking to camera about hangovers while putting a patch on, with a text overlay',
             why='This is most of what we get. It all looks the same and none of it stands out in the feed.'),
        dict(title='Lying in bed or on the couch looking hungover',
             why='We sell a better tomorrow, not a bad one. Show her up and doing things.'),
        dict(title='Shots, heavy drinking, or anyone who looks drunk',
             why='It breaks ad rules and it is not our customer. A drink in hand at dinner or a party is fine.'),
        dict(title='Reading the claims off the pack',
             why='Show the moment it helps. Nobody stops scrolling for an ingredient list.'),
        dict(title='An unboxing with no story',
             why='Unboxings only work when they are for something: the girls trip, the party tonight.'),
    ],
    rules=[
        "Say \"for a better next day\" or \"so tomorrow still happens\". Never say it cures, prevents or stops hangovers.",
        'Show the patch going on before the night starts, where we can see it.',
        'Keep the patch visible in at least one shot: arm, shoulder or hip.',
        'Everyone on screen is 21 or older. No drinking and driving, ever.',
        'Film vertical, sound on, and show where you are in the first two seconds.',
        'Only film people who have agreed to be in your video.',
    ],
    season=dict(
        title='Halloween party season', until='Oct 31',
        line=("Adult Halloween parties, couples costume nights and girls' Halloween are the big moments this month, "
              "and the new Halloween bundle is what we are pushing. Film it this week so it can run all month."),
        next="Friendsgiving, Thanksgiving Eve and holiday parties, from Nov 1",
        highlight=['10-01', '10-31'], show_chart=True,
    ),
    show_inspo=1,
)

SECTIONS = [
    dict(key='hot', name='Hot right now', line='What we are pushing hardest this week', icon='flame', color='#C2410C', pinned=1),
    dict(key='hall', name='Halloween', line='Parties, costumes and the new Halloween bundle. Until Oct 31.', icon='ghost', color='#7C3AED'),
    dict(key='tt', name='Tonight / Tomorrow', line='The big idea: her night out, and the busy morning she still shows up for.', icon='sunrise', color='#1D4ED8'),
    dict(key='cal', name="Mom's social calendar", line='Game days, book club, bunco, weddings, girls trips. Every event she says yes to.', icon='calendar-heart', color='#DB2777'),
    dict(key='hol', name='Holiday season', line='Friendsgiving to New Year\'s Eve. Switch on mid October so videos are ready for November.', icon='gift', color='#15803D', enabled=0),
    dict(key='ev', name='Always works', line='Ideas that sell any month of the year.', icon='leaf', color='#0F766E'),
]

def A(sec, title, fmt, argument, who, openers, shots, on_screen=None, do=None, dont=None, lever=None,
      products='Party Patch', hot=0, trend=None, ads=()):
    return dict(sec=sec, title=title, format=fmt, argument=argument, who=who, openers=openers,
                shots=[dict(label=l, text=t) for l, t in shots], on_screen=on_screen, do=do, dont=dont,
                lever=lever, products=products, hot=hot, trend=trend, ads=list(ads))

ANGLES = [
    # ---------------- Halloween ----------------
    A('hall', 'Scary good night, less scary morning', 'Split screen',
      "The adult Halloween party is mom's night, and the pumpkin patch with the kids still happens in the morning.",
      'The mom going to an adult costume party who has the family pumpkin patch booked for 9am.',
      ['Scary good night. Less scary morning.',
       'Adult Halloween party tonight. Pumpkin patch with the kids at 9.',
       'Me at 10pm vs me at 9am. Same witch.'],
      [(OPEN, 'Split screen. Left: you in costume at the party, drink in hand, 10:14 PM on screen. Right: the same you at a pumpkin patch the next morning, kids running around, 9:02 AM.'),
       (MID, 'Cut to getting ready: the patch goes on before the costume is finished. Close-up so the design reads.'),
       (CLOSE, 'Back at the pumpkin patch. You lift the biggest pumpkin like it is nothing, patch pack in your pocket or bag.')],
      on_screen='TONIGHT: Halloween party / TOMORROW: pumpkin patch with the kids',
      do='Put both times on screen. The clock is the story.',
      dont='Show the morning in bed. She is up and doing it.',
      lever='Relief', products='Halloween bundle', hot=1),
    A('hall', 'Because moms deserve Halloween too', 'Group reaction',
      'The kids get Halloween every year. This is the night mom and her friends take it back.',
      'A group of mom friends dressing up for their own Halloween night.',
      ['Because moms deserve Halloween too.',
       "The kids had their Halloween. This one's ours.",
       'The mom group chat said costumes are mandatory.'],
      [(OPEN, "Friends in costume arriving at the door. One line to camera: the kids had theirs, this one's ours."),
       (MID, 'Someone opens the Halloween bundle. Everyone picks a design (Momster, Resting Witch Face, Here for the Boos) and sticks it on. React to the names.'),
       (CLOSE, 'Cheers shot with the patches visible. End on the group laughing.')],
      do='Have everyone read their patch name out loud. The designs are funny, use that.',
      dont='Film it alone. This one needs the group.',
      lever='Belonging', products='Halloween bundle', hot=1),
    A('hall', 'One bundle covers the whole group', 'Unboxing with a purpose',
      "One Halloween bundle covers girls' Halloween night: three designs, six patches.",
      "The friend who plans the girls' Halloween night and likes bringing something for everyone.",
      ['Six patches, three designs, one very good girls night.',
       'I bought one Halloween bundle and covered the whole group.',
       'Party favors for the moms, not the kids.'],
      [(OPEN, 'Bundle in hand at the pregame, friends around you getting ready.'),
       (MID, 'Hand them out one by one and say why each friend gets that design. Keep it quick and teasing.'),
       (CLOSE, 'Everyone patched up, one group shot on the way out.')],
      on_screen='3 designs. 6 patches. 1 girls night.',
      do='Say "six patches, three designs" out loud.',
      dont='Unbox it alone on a table with no one around.',
      lever='Belonging', products='Halloween bundle', hot=1),
    A('hall', 'Which patch are you?', 'Trend',
      'Each Halloween design is a personality, and picking yours is half the fun.',
      'Anyone who loves a "which one are you" moment with her friends.',
      ["Tell me you're a Momster without telling me you're a Momster.",
       'Which one are you: Momster, Resting Witch Face or Here for the Boos?',
       'I let my friends pick my Halloween patch and I am offended.'],
      [(OPEN, 'Hold up the three designs to camera and ask which one you are.'),
       (MID, 'Friends or your partner vote. Quick cuts of each reaction.'),
       (CLOSE, 'Stick on the one they picked, act offended, then own it.')],
      on_screen='Which one are you?',
      do='Ask the same question in your caption. It gets comments.',
      lever='Curiosity', products='Halloween bundle',
      trend='Any "which one are you" or pointing trend sound.'),
    A('hall', 'He said he did not need one', 'Skit',
      'Couples costume night is the one night you both go out, and you both still have to parent tomorrow.',
      'Couples going to a costume party with kids at home.',
      ["We did a couples costume. We also both have a 7am wake-up call.",
       "Husband said he doesn't need one. Watch.",
       'Matching costumes. Only one of us wore a patch.'],
      [(OPEN, 'Couple in matching costumes. She sticks her patch on and offers him one. He waves it off.'),
       (MID, 'Cut to the morning: she is up making pancakes for the kids. He is moving a lot slower. Keep it playful.'),
       (CLOSE, 'He holds his hand out for a patch for next time. She hands it over with a look.')],
      on_screen="He said he didn't need one.",
      do='Keep it light. The joke is on him, not on drinking.',
      dont='Make the morning look like a sick day.',
      lever='Humour', products='Halloween bundle'),
    A('hall', 'Get ready with me: Halloween party', 'Get ready with me',
      'The patch is part of getting ready, like the lashes and the costume.',
      'The mom going to her first adult Halloween party in years.',
      ['Get ready with me for my first adult Halloween party in five years.',
       'Costume, lashes, patch. In that order.',
       'Mom by day. Witch by night.'],
      [(OPEN, 'Mirror, half in costume. Say where you are going tonight.'),
       (MID, 'Makeup and costume in fast cuts. The patch goes on as its own step, close-up on the design.'),
       (CLOSE, 'Full costume reveal with the patch visible on your arm or shoulder, then walk out.')],
      do='Make the patch a real step in the routine, not an afterthought.',
      lever='Identity', products='Halloween bundle',
      trend='Any trending get ready with me or transformation sound.'),

    # ---------------- Tonight / Tomorrow ----------------
    A('tt', "Your calendar doesn't care what you did last night", 'Split screen',
      'Tomorrow is already booked, so she wears a patch tonight and still shows up.',
      "The mom of school-age kids whose Saturday starts on a soccer sideline.",
      ["Your calendar doesn't care what you did last night.",
       '9:47 PM: margaritas with the girls. 8:03 AM: soccer sideline.',
       "Girls night was last night. Soccer is at 8. I'm fine."],
      [(OPEN, 'Split screen. Left: 9:47 PM, you and your friends laughing over drinks at dinner. Right: 8:03 AM, the same you on the sideline in sunglasses with a big coffee cup.'),
       (MID, 'Quick cut back to dinner: the patch goes on before the first drink. Close-up.'),
       (CLOSE, 'Sideline: you cheer for your kid. Patch pack in your bag or on the chair.')],
      on_screen='TONIGHT: girls night / TOMORROW: 8AM soccer',
      do='Put the times on screen, and keep her looking good in both halves.',
      dont='Show her tired or hurting in the morning. The point is she is fine.',
      lever='Relief', hot=1),
    A('tt', 'Game day, next day', 'Split screen',
      'A tailgate is an all-day event, and Sunday still shows up.',
      'Women 30 to 45 who tailgate college or NFL games and have a full morning after.',
      ['Game day. Next day.',
       'Tailgate Saturday. Pickleball at 8 on Sunday.',
       'Sunday Funday. Monday still happens.'],
      [(OPEN, 'Tailgate: jersey, friends, cooler. The patch is on your arm and in frame.'),
       (MID, 'Hard cut to the next morning: pickleball court, church, or your desk on Monday. Same person, energy up.'),
       (CLOSE, 'Hold up the patch pack where you are.')],
      on_screen='GAME DAY. NEXT DAY.',
      do='Wear team colours. Game day content travels.',
      dont='Show shotgunning or drinking games.',
      lever='Relief', hot=1),
    A('tt', 'Rosé tonight, rally tomorrow', 'Day in the life',
      'League night drinks and an 8am match can both happen.',
      'The pickleball or tennis league player who never skips the social after.',
      ['Rosé tonight. Rally tomorrow.',
       "Wine with the league tonight. Match at 8. Let's see.",
       'My pickleball team is 50 percent pickleball and 50 percent rosé.'],
      [(OPEN, 'Wine with your league friends. The patch goes on.'),
       (MID, 'Next morning: the court, first serve.'),
       (CLOSE, 'Win a point, celebrate, patch visible on your arm.')],
      lever='Relief'),
    A('tt', "She's got stuff to do", 'Voiceover montage',
      'Her week is full, so a big night cannot cost her a day.',
      'The busy woman whose Friday night and Saturday morning are both booked.',
      ['She has dinner at 8. And soccer at 8.',
       'Cocktails Friday. Pickleball Saturday. She has stuff to do.',
       'Friendsgiving tonight. Thanksgiving tomorrow. She has things to do.'],
      [(OPEN, 'Fast montage, one line per shot: dinner, soccer, cocktails, pickleball, school run.'),
       (MID, 'Every "tonight" shot shows the patch going on.'),
       (CLOSE, 'End on her walking fast with a coffee: she has stuff to do.')],
      on_screen="She's got stuff to do.",
      do='Keep the cuts fast, one second a shot.',
      dont='Swear in the on-screen text. The edgier line is fine out loud if it fits your audience.',
      lever='Identity', trend='A fast-cut beat or a trending "that girl" routine sound.'),
    A('tt', "Because the babysitter wasn't cheap", 'Skit',
      'Date night is rare, so it has to count, and tomorrow still starts at 7.',
      'Parents on a rare night out.',
      ["Because the babysitter wasn't cheap.",
       'We finally got a sitter. We are making it count.',
       'Date night tonight. 7am spin tomorrow.'],
      [(OPEN, 'Paying the babysitter at the door, wide-eyed at the total.'),
       (MID, 'At dinner: both of you put a patch on. Cheers.'),
       (CLOSE, 'Morning: spin class or the kids jumping on the bed, and you are up for it.')],
      on_screen='We are making this date night count.',
      lever='Humour'),
    A('tt', 'Wedding tonight, brunch tomorrow', 'Get ready with me',
      'Fall wedding season means dancing until midnight and a brunch at 10.',
      'Bridesmaids and guests at fall weddings.',
      ['Wedding tonight. Brunch tomorrow.',
       'Bridesmaid duties: dress, hair, patch.',
       'Dancing until midnight. Brunch at 10. Here is how.'],
      [(OPEN, 'Getting ready in the wedding outfit. The patch goes on your shoulder or hip under the dress.'),
       (MID, 'Dance floor clips.'),
       (CLOSE, 'Next morning at brunch, fresh, laughing with the group.')],
      do='Show where the patch hides under a dress. People ask.',
      lever='Relief'),

    # ---------------- Mom's social calendar ----------------
    A('cal', "Let me show you my October", 'Screen record',
      'From September to December her calendar is relentless, and every event is a night out.',
      'The mom who said yes to everything this fall.',
      ['Let me show you my October.',
       'This is the calendar of a mom who said yes to everything.',
       'Every square on this calendar is a night out. Every next morning is booked.'],
      [(OPEN, 'Screen record your real calendar (hide anything private) and scroll through a packed month.'),
       (MID, 'Tap into events: bunco, book club, a wedding, a tailgate, a Halloween party. Quick clip of each.'),
       (CLOSE, 'Hold up the patch pack: this is how I get through it.')],
      on_screen='My October, a thread',
      lever='Relatability', hot=0),
    A('cal', 'Book club is just wine club', 'Skit',
      'Book club is a wine night, everybody knows it, and school drop-off is at 7:45.',
      'Book club moms.',
      ['Book club: ten minutes on the book, two hours on the wine.',
       'Nobody finished the book. Everybody brought wine.',
       'We read the room, not the book.'],
      [(OPEN, 'Book club table, books closed, wine poured.'),
       (MID, 'One friend hands out patches: we know how this goes.'),
       (CLOSE, 'Next morning: school drop-off, waving, fine.')],
      lever='Humour'),
    A('cal', 'Bunco got a little competitive', 'Group reaction',
      'Neighborhood game nights get loud, and the carpool still leaves at 7:30.',
      'Neighborhood bunco and game night groups.',
      ['Bunco got a little competitive.',
       'Neighborhood bunco night. The stakes are high.',
       'We came for bunco. We stayed for the wine.'],
      [(OPEN, 'Dice rolling, someone yelling bunco.'),
       (MID, 'Patches going on around the table between rounds.'),
       (CLOSE, 'Morning carpool line, waving at the same friends.')],
      lever='Belonging'),
    A('cal', 'Girls trip insurance', 'What is in my bag',
      'The patch is the one thing on the packing list that protects every day of the trip.',
      'Women planning a girls weekend or a bachelorette.',
      ['Girls trip packing list. The most important thing is at the end.',
       'Girls trip insurance.',
       'I packed one for every night of the trip.'],
      [(OPEN, 'Packing montage: outfits, sunscreen, shoes.'),
       (MID, 'Last item: count out a patch for each night.'),
       (CLOSE, 'At the destination, the group puts them on before night one.')],
      on_screen='Girls trip insurance',
      lever='Loss'),
    A('cal', 'Encore tonight, real life tomorrow', 'Day in the life',
      'Forty and at a concert singing every word, with a school run at 7:45.',
      'Girlfriends 35 to 50 at a concert.',
      ['Encore tonight. Early morning tomorrow.',
       'Forty, front row, every word. School run at 7:45.',
       'We are too old for this and we are doing it anyway.'],
      [(OPEN, 'Singing at the concert with your friends.'),
       (MID, 'Flash back to the car before the show: patches on.'),
       (CLOSE, 'Morning routine, still humming the song, kids out the door.')],
      trend='Use the artist\'s song only if the platform allows it; otherwise a trending sound.',
      lever='Identity'),
    A('cal', 'What time is your alarm tomorrow?', 'Street interview',
      'Everyone at a party has something tomorrow.',
      'Women at tailgates, wine festivals and Oktoberfest.',
      ['What do you have tomorrow morning?',
       'Asking moms at a wine festival what time their alarm is set for.',
       'Oktoberfest question: what is your plan for tomorrow?'],
      [(OPEN, 'Mic in hand at a tailgate, wine festival or Oktoberfest. Ask women what they have tomorrow.'),
       (MID, 'Rapid answers: soccer at 8, work, church, pickleball.'),
       (CLOSE, 'Hand each one a patch: then you will want this.')],
      do='Get a yes from everyone before you film them.',
      lever='Social proof'),

    # ---------------- Holiday season (switched on mid October) ----------------
    A('hol', 'Friendsgiving without the next-day regret', 'Group reaction',
      'Friendsgiving is tonight and Thanksgiving prep is tomorrow, so the patch is at every place setting.',
      'The friend hosting or going to Friendsgiving.',
      ['Friendsgiving tonight. Thanksgiving prep tomorrow.',
       'The Friendsgiving table is set. There is a patch at every seat.',
       'Hosting tip: put a patch on every place card.'],
      [(OPEN, 'A beautiful table, wine poured, friends arriving.'),
       (MID, 'Close-up: a patch on every place card. Friends find theirs.'),
       (CLOSE, 'Next morning: turkey prep, still smiling.')],
      lever='Belonging', products='Party Patch'),
    A('hol', 'The biggest Wednesday night of the year', 'Skit',
      'Thanksgiving Eve is the hometown reunion, and Thanksgiving still starts early.',
      'Women home for Thanksgiving meeting old friends.',
      ['The biggest Wednesday night of the year.',
       'Home for Thanksgiving. Meeting everyone from high school at the bar.',
       'Thanksgiving Eve rules: patch first.'],
      [(OPEN, 'Walking into the hometown bar, hugging old friends.'),
       (MID, 'Patches on in the car or at the table.'),
       (CLOSE, 'Thanksgiving morning in the kitchen with mom, helping, fine.')],
      lever='Belonging'),
    A('hol', 'Wine at 9, shopping at 7', 'Split screen',
      'Thanksgiving wine and Black Friday doorbusters are twelve hours apart.',
      'Black Friday shoppers.',
      ['Wine at 9. Shopping at 7.',
       'Black Friday plan: Thanksgiving wine, then 6am doorbusters.',
       'Shopping at 7AM? Patch at 7PM.'],
      [(OPEN, 'Split screen: wine at the Thanksgiving table / a cart at 6am.'),
       (MID, 'The patch goes on at the table.'),
       (CLOSE, 'Arms full of bags, patch visible.')],
      on_screen='WINE AT 9. SHOPPING AT 7.',
      lever='Relief'),
    A('hol', 'Office party tonight, office tomorrow', 'Get ready with me',
      'The holiday party is on a weeknight, and work is at 9.',
      'Women going to a work holiday party.',
      ['Office party tonight. Office tomorrow.',
       'Get ready with me for the work holiday party. Meeting at 9am tomorrow.',
       'Holiday party outfit check, and the thing nobody sees.'],
      [(OPEN, 'Getting ready in a party outfit. The patch goes on.'),
       (MID, 'Party clips: dancing with coworkers.'),
       (CLOSE, 'Next morning at the desk or on a video call, sharp.')],
      lever='Relief'),
    A('hol', 'The group chat actually made it out', 'Group reaction',
      'The girls Christmas dinner finally happened, and a patch pack is the gift everyone uses.',
      "Friends at a girls' Christmas dinner or gift exchange.",
      ['The group chat actually made it out.',
       'My white elephant gift was the one everyone fought over.',
       'Girls Christmas dinner. Everyone gets a patch.'],
      [(OPEN, 'Friends at dinner in holiday outfits.'),
       (MID, 'Gift exchange: someone opens a Party Patch pack and it gets stolen twice.'),
       (CLOSE, 'Everyone patched up for the rest of the night.')],
      lever='Belonging'),
    A('hol', 'The stocking stuffer she will actually use', 'Voiceover',
      'Most stocking stuffers end up in a drawer. This one gets used at the next party.',
      'People shopping for their best friend, sister or wife.',
      ['Stocking stuffer ideas for the friend who has everything.',
       "The only stocking stuffer that didn't end up in a drawer.",
       'Gift for the mom who never says no to a night out.'],
      [(OPEN, 'Stuffing a stocking, the pack goes in last.'),
       (MID, 'Christmas morning: she opens it and laughs.'),
       (CLOSE, 'New Year\'s Eve: she is wearing it.')],
      lever='Gifting'),
    A('hol', 'Big night, bigger tomorrow', 'Get ready with me',
      "New Year's Eve is the biggest night, and January 1st is day one of her plans.",
      "Women going out for New Year's Eve.",
      ['Big night. Bigger tomorrow.',
       'New Year\'s Eve get ready with me. My resolutions start at 9am.',
       'The last thing I put on for New Year\'s Eve.'],
      [(OPEN, 'Glam getting ready.'),
       (MID, 'The patch goes on as the final step.'),
       (CLOSE, 'Midnight clip, then a January 1st walk or workout.')],
      lever='Relief'),

    # ---------------- Always works ----------------
    A('ev', 'The sniff test', 'Test',
      'The new patch is scent-free, so nothing gives it away.',
      'Anyone who tried a patch before and did not like the smell.',
      ['The new Party Patch has zero smell. My friends did not believe me.',
       'Sniff test: which arm has the patch?',
       'Scent-free. Stress-free. Party on.'],
      [(OPEN, 'A friend closes her eyes and sniffs both of your arms.'),
       (MID, 'She guesses wrong.'),
       (CLOSE, 'Reveal the patch: scent-free now.')],
      do='Make the guess real. A wrong guess sells it.',
      lever='Proof', ads=['120243115360050266', '120243115386000266']),
    A('ev', "The morning after doesn't have to be a plot twist", 'Day in the life',
      'Her healthy routine and her fun nights can both stay.',
      'The woman with a real routine (skincare, journaling, the gym) who still says yes to pizza with friends.',
      ["The morning after doesn't have to be a plot twist.",
       'My 6am routine, the morning after girls night.',
       'You should not have to pick between your routine and your friends.'],
      [(OPEN, 'Wellness morning routine: journal, skincare, gym bag.'),
       (MID, 'Flashback: last night, pizza and laughing with friends, the patch going on.'),
       (CLOSE, 'Back to the routine without skipping a step.')],
      lever='Identity', ads=['120238642174850266']),
    A('ev', 'Get your Sunday back', 'Day in the life',
      'A big Saturday should not cost her Sunday.',
      'The weekend social who wants her Sunday for family, errands and the farmers market.',
      ['A big Saturday should not cost you your Sunday.',
       'Saturday night vs my Sunday. Both happened.',
       'Sunday plans: farmers market, park, meal prep. Saturday plans: everything else.'],
      [(OPEN, 'Saturday night out with friends, the patch goes on.'),
       (MID, 'Sunday morning: farmers market, park with the kids, coffee.'),
       (CLOSE, 'Sunday evening meal prep, patch pack on the counter.')],
      dont='Say it stops hangovers. Say she got her Sunday back.',
      lever='Loss', ads=['120246582639020266', '120246582743940266']),
    A('ev', 'Stock up for the season', 'Voiceover',
      'One bundle covers every night out on the calendar, and the offer makes it worth it.',
      'Returning customers and the planner who buys ahead.',
      ['I counted my nights out between now and New Year\'s. I need the bundle.',
       'Every party on my calendar, covered.',
       'The bundle math actually makes sense.'],
      [(OPEN, 'Calendar with every night out circled.'),
       (MID, 'Bundle unboxed, one patch per circled night.'),
       (CLOSE, 'Say the current offer from the site, word for word.')],
      dont='Make up a discount. Only say the offer that is live on the site.',
      lever='Value', products='Bundles', ads=['120249211680840266']),
    A('ev', 'Ten second how-to', 'Demo',
      'It is so easy it is part of getting dressed, and it stays on.',
      'First-time buyers who have never used a patch.',
      ['How to Party Patch in ten seconds.',
       'Clean skin, peel, press, go.',
       'Pool day test: did it stay on?'],
      [(OPEN, 'Peel the patch.'),
       (MID, 'Press it on your arm and hold for a few seconds.'),
       (CLOSE, 'It stays put through a pool day or a sweaty dance floor (it is water resistant).')],
      lever='Proof'),
    A('ev', 'Patch check', 'Trend',
      'The patch is part of the outfit, and everyone wears it their own way.',
      'Groups at a party, wedding or girls trip.',
      ['Patch check.',
       'Where did everyone put their patch tonight?',
       'Rating my friends\' patch placement.'],
      [(OPEN, "At the party, go around the group: patch check."),
       (MID, 'Each person shows theirs: arm, shoulder, ankle, hip.'),
       (CLOSE, 'Best spot wins. Crown them.')],
      lever='Belonging', trend='Any "rating my friends" or roll-call trend.'),
    A('ev', 'The group chat the morning after', 'Screen record',
      "Her friends' texts the next morning tell the whole story.",
      'Friend groups with a busy group chat.',
      ['The group chat the morning after girls night.',
       "'How is everyone alive' 'soccer at 8 lol'",
       'Everyone asked how I was fine this morning.'],
      [(OPEN, 'Screen record the group chat: how is everyone alive?'),
       (MID, 'You reply with a selfie from the soccer field, fresh.'),
       (CLOSE, 'Next text: the patch. I told you. Cut to the pack.')],
      do='Use real-looking texts. No real names or numbers on screen.',
      lever='Social proof'),
]

sql = ["-- Party Patch creator link seed (see seed_party_patch.py)",
       f"DELETE FROM p_amb_proof WHERE act_id = {q(ACT)};",
       f"DELETE FROM p_amb_angle WHERE act_id = {q(ACT)};",
       f"DELETE FROM p_amb_section WHERE act_id = {q(ACT)};",
       f"DELETE FROM p_amb_brand WHERE act_id = {q(ACT)};"]
b = brand
sql.append(
    "INSERT INTO p_amb_brand (act_id, slug, live, display_name, intro, about, audience, accent, logo_url, "
    "submit_platform, submit_url, submit_label, avoid_json, rules_json, season_json, show_inspo) VALUES (" +
    ', '.join(q(x) for x in [ACT, b['slug'], b['live'], b['display_name'], b['intro'], b['about'], b['audience'],
                             b['accent'], b['logo_url'], b['submit_platform'], b['submit_url'], b['submit_label'],
                             json.dumps(b['avoid']), json.dumps(b['rules']), json.dumps(b['season']), b['show_inspo']]) + ");")
sec_id = {}
for i, s in enumerate(SECTIONS):
    sid = rid(); sec_id[s['key']] = sid
    sql.append("INSERT INTO p_amb_section (id, act_id, name, line, icon, icon_svg, color, enabled, pinned, sort) VALUES (" +
               ', '.join(q(x) for x in [sid, ACT, s['name'], s['line'], s['icon'], svg(s['icon']), s['color'],
                                        s.get('enabled', 1), s.get('pinned', 0), i]) + ");")
hot_n = 0
sort_by_sec = {}
for a in ANGLES:
    aid = rid()
    sort_by_sec[a['sec']] = sort_by_sec.get(a['sec'], 0) + 1
    if a['hot']:
        hot_n += 1
    sql.append("INSERT INTO p_amb_angle (id, act_id, section_id, hot, hot_sort, sort, status, title, argument, who, products, "
               "format, lever, openers_json, shots_json, on_screen, do_text, dont_text, trend) VALUES (" +
               ', '.join(q(x) for x in [aid, ACT, sec_id[a['sec']], a['hot'], hot_n if a['hot'] else 0, sort_by_sec[a['sec']],
                                        'live', a['title'], a['argument'], a['who'], a['products'], a['format'], a['lever'],
                                        json.dumps(a['openers']), json.dumps(a['shots']), a['on_screen'], a['do'], a['dont'],
                                        a['trend']]) + ");")
    for k, ad in enumerate(a['ads']):
        sql.append("INSERT INTO p_amb_proof (id, act_id, angle_id, kind, ad_id, shown, sort) VALUES (" +
                   ', '.join(q(x) for x in [rid(), ACT, aid, 'meta', ad, 1, k + 1]) + ");")

open(os.path.join(HERE, 'seed_party_patch.sql'), 'w', encoding='utf-8').write('\n'.join(sql) + '\n')
print(len(ANGLES), 'angles,', len(SECTIONS), 'sections,', sum(len(a['ads']) for a in ANGLES), 'tagged ads')
