"""Grunk Dolfer creator link, rebuilt 2026-10-06 from docs/research-2026-10-06/grunk-dolfer.md.

  LUCIDE_NODES=<path>/icon-nodes.json python migrations/seed_amb_grunk_dolfer.py
  npx wrangler d1 execute mobius-account-health --remote --file migrations/seed_amb_grunk_dolfer.sql   (ONCE)

Replaces every section and angle on the Grunk Dolfer page. Keeps the brand row (slug, live, TRYBE
link, logo, PDF, accent) and re-points the existing tagged Meta ads onto the new angles by old title.
Voice: crude but self-censoring, self-deprecating about the dad bod, parody-driven; Golf is a Drinking
Sport, Chunkman, Grunk Nation. Openers sound like a 15-handicap talking to his phone in the cart, or
his wife filming him.
Cole's rules (2026-09-17 and 2026-10-06): beer in hand only, never chugging or anyone drunk, never a
cart driven with a beer; Black Friday = "BOGO + 30% off sitewide" said only in Black Friday videos
(film by Nov 10, post Nov 26 to 30); Tittees and cart girl hats are fine; push the fall drops, the
Chunkman hats back in stock, the Den Caddy + free polo (confirm the free polo is live before filming)
and early gifting; never the HYDR18 hangover claim; polo claims only as the site states them; no UPF;
"relaxed, dad bod approved fit", never "athletic" or "slimming"; never name a competitor on screen;
any woman on screen is in on the joke and consent is shown.
The September "Masters to Father's Day" section (More muni than Masters, Father's Day gift reveal)
is dropped here: re-add it in March. Its one tagged ad (Tyson's Masters hat) moves to the hats angle.
"""
import os, sys
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from amb_seed_lib import write, OPEN, MID, CLOSE

ACT = 'act_313396960515158'
HERE = os.path.dirname(os.path.abspath(__file__))

# Drawn season shape from the September seed (0-100 per ISO week, 25 = a normal week). Real sales
# were not used: one Black Friday week flattens the line, Feb 2026 was partly a TikTok spend test,
# and wholesale is not in Shopify.
CUSTOM = {1: 20, 2: 20, 3: 25, 4: 26, 5: 34, 6: 36, 7: 38, 8: 32, 9: 30, 10: 30, 11: 33, 12: 32,
          13: 34, 14: 50, 15: 38, 16: 28, 17: 27, 18: 27, 19: 28, 20: 33, 21: 34, 22: 36, 23: 44,
          24: 55, 25: 42, 26: 36, 27: 34, 28: 25, 29: 24, 30: 23, 31: 24, 32: 24, 33: 23, 34: 18,
          35: 17, 36: 15, 37: 14, 38: 15, 39: 18, 40: 30, 41: 32, 42: 28, 43: 22, 44: 22, 45: 28,
          46: 32, 47: 45, 48: 100, 49: 55, 50: 65, 51: 64, 52: 55, 53: 40}

CONSENT = 'Everyone agreed to be in this video'

BRAND = dict(
    display_name='Grunk Dolfer',
    intro=("Grunk Dolfer makes loud polos for guys who golf to hang out, not to grind. Golf is a drinking sport, so we "
           "want videos that look like a real Saturday: the crew, the cart, a beer in hand, the bad shots and the 19th hole. "
           "Your hands do something in the first second, film the group, and let the print do the joke. "
           "Pick one idea, do the first second the way it says, and submit it on TRYBE like always."),
    about=("Loud, soft performance golf polos in prints you won't see on anyone else, plus hats, hoodies, button-downs, "
           "koozies and the Den Caddy cooler bag. Relaxed, dad bod approved fit, small through 4XL on every polo and 5XL "
           "on many. The mascot is Chunkman, a chubby guy proudly holding a beer. New this fall: Brown Chunkman, Espresso "
           "Martini, Bearly Sober and the Closet Grunk button-downs. The Chunkman hats are back in stock."),
    audience=("Weekend golfers, mostly guys 30 to 55, who play with the same three buddies, have a beer on the cart and care "
              "more about the day than the score. Plenty have a dad bod and own it. From late October we also talk to the "
              "wives, girlfriends and kids buying for the golfer who has everything, and to the guy ordering eight for the trip."),
    accent='#E05A25',
    avoid=[
        dict(title='Holding the polo up at the shop wall and talking',
             why='Every creator submission that lost looked exactly like this. Take it to the range, the cart, the bar or the kitchen table instead.'),
        dict(title='A hat video that talks about polos',
             why='Talk about the thing you are showing. If it is a hat, sell the hat. Our only creator win so far was a hat video that did.'),
        dict(title='Stiff, posed shots smiling at the camera',
             why='Our posed ads lose. Real rounds, real buddies and real reactions win.'),
        dict(title="Opening on another brand's shirt",
             why='Keep the first second on Grunk. A plain unbranded polo is fine later, as the before.'),
        dict(title='Acting drunk or shouting at the lens',
             why='A beer in hand is the brand. Performing drunk is the try-hard tell, and it breaks ad rules. Say what golfers actually say.'),
        dict(title='Reading the product page out loud',
             why='Say one thing it does and show the rest. Nobody stops scrolling for a spec list.'),
        dict(title='Meme wrappers: fake tweets, fake reviews, search bars',
             why='Ours all lost. One real-sounding text from a real-sounding person is the only version worth testing.'),
    ],
    rules=[
        'Say what the site says about a polo: soft, moisture-wicking, 4-way stretch, breathable, wrinkle-resistant. The fit is "relaxed, dad bod approved". Never "athletic", never "slimming".',
        'Do not say UPF or sun protection about a polo. It is not confirmed. Never say stain-proof or beer-proof. Never say HYDR18 prevents or cures hangovers.',
        'Sizes: every polo comes small through 4XL, and many prints go to 5XL. Check the product page before you say 5XL.',
        'Beer in hand only. Nobody chugs, nobody looks drunk, and nobody drives a cart with a beer. Everyone with a drink on screen is 21 or older.',
        'Black Friday is BOGO + 30% off sitewide, said only in Black Friday videos (film by Nov 10, post Nov 26 to 30). Any other day: "check the site for the current deal".',
        'The Den Caddy comes with a free polo. Confirm the free polo is live on the site before filming.',
        'Any video with a woman in it: she is in on the joke, she has the power in the clip, and consent is on screen ("Everyone agreed to be in this video").',
        'Never name a competitor on screen. A plain unbranded polo as the before is fine.',
        "Show the print up close at least once and say the print's name. Tittees and cart girl hats are fine to film.",
        'Film vertical, sound on. Only film people who agreed to be in your video, on a course that allows filming.',
    ],
    season=dict(
        title='Fall drops, then gift season', until='Nov 25',
        line=("The new drop is live from Oct 7 and the Chunkman hats are back in stock. Film your gift videos NOW so they are "
              "live by Nov 1. Black Friday week is the biggest week we have."),
        next='Black Friday: BOGO + 30% off sitewide, Nov 26 to 30',
        highlight=['10-06', '11-25'], show_chart=True, color='#B45309', cap=None,
        mode='custom', custom={str(k): v for k, v in CUSTOM.items()},
    ),
    guide=[
        dict(title='Your hands do something in the first second', text='Tearing the mailer, pulling the hat on, cans going into the cooler, buttons in the mirror. Then you can talk. Faces alone get scrolled. The best gift ad in golf opens on a bag being ripped open.'),
        dict(title='The print does the joke', text='You do not have to be funny. The burgers on the Brown Chunkman and the chubby guy with the beer are the joke. Get the print filling the frame and say what you would actually say: "there it is".'),
        dict(title='Say who it is for in the first line', text='"Big guys, this one\'s for you." "Girls, he wants this one." "Scramble team\'s here." The right person leans in and the wrong one leaves, and that is fine.'),
        dict(title='Change the picture at 3 seconds', text='Kitchen to range. Mailer to his face. Parking lot to the first tee. If you have been talking to the camera for 8 seconds without moving, cut.'),
        dict(title='Give them a count that climbs', text='Cans into the Den Caddy, holes in the match, polos out of the Black Friday box, seconds until he notices. If the viewer is waiting for one number, they stay.'),
        dict(title='Film the group', text='Four guys walking in from the parking lot is a top ad for another golf brand right now. The questions your buddies ask on camera are better than any line we write. Beer in hand, nobody drunk.'),
        dict(title='Let the wife film you', text='The number one ad in our category for 192 days is a woman with a phone timing how long until her husband notices the print. She is in on it, she runs the clip, and "everyone agreed to be in this video" is on screen.'),
        dict(title='End on the shirt being worn', text='On the tee, at the bar, walking out the door with the clubs. Say who it is for and what to do in your own words. No "link below", no wrap-up speech.'),
    ],
)

SECTIONS = [
    dict(key='hot', name='Hot right now', line='The ideas we want most this week. Start here.', icon='flame', color='#DC2626', pinned=1),
    dict(key='fall', name='Fall drops and hats', line='Brown Chunkman, Espresso Martini, Bearly Sober, Closet Grunk, the Chunkman hats back in stock and the Den Caddy. Until Nov 25.', icon='leaf', color='#B45309'),
    dict(key='gift', name="Gift him the one he'll actually wear", line='Film these now so they are live from Oct 20. Wives, kids and buddies buying for the golfer who has everything. Live to Dec 18.', icon='gift', color='#15803D'),
    dict(key='drink', name='Golf is a drinking sport', line='Our line, and nobody else in golf has taken it. Beer in hand, the cart, the 19th hole.', icon='beer', color='#1D4ED8'),
    dict(key='fit', name='Dad bod approved', line='Small through 5XL, relaxed, dad bod approved. The one argument nobody else in golf can film.', icon='shirt', color='#7C3AED'),
    dict(key='crew', name='The crew', line="Foursomes, scrambles, guys' trips. Guys who buy together.", icon='users', color='#0F766E'),
]


def A(sec, title, fmt, argument, who, visual_hook, rehook, openers, shots, on_screen=None, do=None, dont=None,
      why=None, inspo=(), products='Grunk Dolfer polos', hot=0, ads=(), keep_from=(), lever=None, trend=None):
    return dict(sec=sec, title=title, format=fmt, argument=argument, who=who, visual_hook=visual_hook, rehook=rehook,
                openers=list(openers), shots=list(shots), on_screen=on_screen, do=do, dont=dont, why=why,
                inspo=list(inspo), products=products, hot=hot, ads=list(ads), keep_from=list(keep_from), lever=lever, trend=trend)


ANGLES = [
    # ---------------- Hot #1 lives in the gift lane; listed first so it leads the Hot row ----------------
    A('gift', 'How long until he notices the Chunkman', 'Gift prank',
      'She gives him the Brown Chunkman and times how long before he spots the burgers and hot dogs in the print. The viewer knows before he does, so they wait.',
      'Couples. Wives and girlfriends buying for a golfer. Film it now so it is live by Nov 1.',
      'Him at the kitchen table or his desk, head down, tearing open the Grunk mailer. Her voice over it, phone in her hand.',
      '"Here, got you something." at 4 seconds. Then the slow noticing at 12 to 18 seconds: "nice polo", then "wait a second".',
      ["I just bought my husband a golf polo and I'm not telling him what's on it.",
       'Okay, he thinks this is a normal brown polo.',
       "Let's see how long it takes him to find the hot dogs."],
      [(OPEN, 'Her setup line to camera, the mailer in her hand or already on the table in front of him.'),
       (MID, 'Hand it over. Stay on his face while he reads the print. Let him say whatever he actually says.'),
       (CLOSE, 'The print filling the frame while he laughs. "There it is." Text: ' + CONSENT + '.')],
      on_screen='How long until he notices. Then: there it is.', hot=1, products='Brown Chunkman, any Chunkman or Drinko polo',
      why="Bogey Bros' number one ad for 192 days is a wife filming her husband find the joke in a print, and Grunk has never filmed it.",
      inspo=[('Bogey Bros', '"Let\'s see how long it takes him to realize it." Steal the timing: nice, nice, wait a second.', 'https://app.tryatria.com/ad/m1859794814679897'),
             ('Bad Birdie', 'Her hand resting on the polo on the bed, her voice over it. Steal the tactile open.', 'https://app.tryatria.com/ad/m1548498556597153')],
      do='Film his real reaction once. Let him say what he actually says. She is in on the joke and consent is on screen.',
      dont='Tell him beforehand. Script his line. Hold the polo up to the lens.'),

    # ---------------- Fall drops and hats ----------------
    A('fall', 'Unbox it, then take it to the range', 'Unboxing',
      'Open the fall drop on the kitchen counter, then cut to the range in it the same night. One cut fixes the video we keep getting: a polo held up at a wall.',
      'Any creator with a range nearby. The weekend golfer who buys the new drop the day it lands.',
      'Hands only, tearing the Grunk mailer open on the kitchen counter, or the box sitting on a range mat under the lights. No face yet.',
      'The cut to the range at 5 seconds: same shirt, now on you, first swing. Then the print and the Chunkman logo up close at the bay.',
      ["Fall drop came in. We're going straight to the range.",
       "Didn't even make it inside. Opening this in the car.",
       "New Grunk, new range session. Let's go."],
      [(OPEN, 'The box opening, hands only. Pull the polo out so the print fills the frame. Say the opener.'),
       (MID, 'Hard cut to the range or the first tee. Polo on, one swing, the ball goes wherever it goes.'),
       (CLOSE, 'Close-up of the print and the Chunkman at the bay. Say the print name. Walk to the next ball.')],
      on_screen='Taking the new Grunk straight to the range', hot=1, products='The fall drop: Brown Chunkman, Espresso Martini, Bearly Sober, Closet Grunk',
      why="Bad Birdie's two newest rising ads are a box opened in a kitchen and a box opened on a range mat at night, and the location change at 5 seconds is what keeps people.",
      inspo=[('Bad Birdie', 'Box opened on a range mat at night, "taking my new items to the range". Steal the cut from box to bay.', 'https://app.tryatria.com/ad/m2116152639293586'),
             ('Bad Birdie', 'Kitchen first look of a new drop, box under the arm. Steal the first-look energy, then leave the kitchen.', 'https://app.tryatria.com/ad/m937514819007024')],
      ads=['120242222297840115'], keep_from=['The new drop, ranked by beers deep'],
      do='Show the shirt moving: a swing, a walk, the cart. Say the print name once.',
      dont='Read the product description. Stay in one room. Hold the polo up at a wall.'),
    A('fall', 'Chunkman hats are back', 'Hat reveal',
      'The Chunkman hats are back in stock, and the one creator video that worked for us was a hat video. Pull it on, show the inside, wear it somewhere real.',
      'Any creator. Works for women creators too. The guy who already owns four Grunk hats.',
      'Both hands pulling the hat on, your face half hidden by the brim, then you look up at the lens.',
      'Flip the hat to show the inside: the rope, the patch, the lining that says GOLF IS A DRINKING SPORT on the Tittees hat.',
      ['They restocked the Chunkman hat. I grabbed two.',
       'This is the hat the cart girl asked about.',
       'Rope hat, flag patch, and it says golf is a drinking sport on the inside. Sold.'],
      [(OPEN, 'The hat going on, both hands, look up. Say the opener.'),
       (MID, 'Macro of the embroidery, the rope, the lining. Name the hat.'),
       (CLOSE, 'Hat on at the course, the bar or the cart. Someone asks about it.')],
      on_screen='Back in stock. Then the hat name.', hot=1, products='Chunkman hats (back in stock), Tittees hat, Donde Esta La Cart Girl hat, rope hats',
      why="Our only creator win so far was Rudy's Navy Open Hat video, and Bad Birdie's cap-pulled-on opener runs on the same first second.",
      inspo=[('Bad Birdie', 'A cap pulled on with both hands, then "Ladies, tap". The first second is the hands.', 'https://app.tryatria.com/ad/m1394607206130813')],
      ads=['120250469342960115'], keep_from=['More muni than Masters'],
      do='Name the hat. Show it on a head, never on a table. Tittees and cart girl hats are fine to film.',
      dont='Talk about polos in a hat video. If it is a hat, sell the hat.'),
    A('fall', 'The Den Caddy rolls up to the first tee', 'Reaction',
      'Everyone else brings a bag. You roll a cooler bag up to the first tee, the group reacts, and the free polo comes out of it.',
      'A foursome. The guy who hosts the round and buys the beer.',
      'The Den Caddy coming into frame on the cart or over your shoulder, the group turning to look. Daylight, a real tee box.',
      'Unzipping the cooler, cans inside, then a buddy pulls the free polo out and holds it up.',
      ['Nobody knew I was bringing this.',
       'Showed up with the Den Caddy and the guys lost it.',
       "It's a bag, it's a cooler, and it came with a free polo."],
      [(OPEN, 'The arrival, wide. The group turns. Get their real faces.'),
       (MID, 'Open it: cans, cold. Hand a few out. The free polo comes out and a buddy holds it up.'),
       (CLOSE, 'Cheers on the tee box, beer in hand, the caddy in the middle of the shot.')],
      on_screen='Den Caddy + free polo (confirm the free polo is live before filming)', hot=1, products='Den Caddy + free polo',
      why='Our own 326 series, the Den Caddy on a misty fairway with the free polo, is a proven offer, and the dark poster version of the same offer lost, so daylight and a group is the shape.',
      inspo=[('Bogey Bros', 'Two guys in matching polos in a cart, one driving, filmed from the passenger seat. Steal the two-guys framing for the arrival.', 'https://app.tryatria.com/ad/m1228261266174271')],
      ads=['120246364301250115'], keep_from=['The Den Caddy rolls up to the first tee'],
      do="Daylight, a real course, the group's faces. Beer in hand only. Confirm the free polo is live on the site before filming.",
      dont='Chug. Stack a dozen cans. Drive the cart with a beer in hand. Film the caddy with nobody around.'),
    A('fall', 'Espresso Martini at the turn', 'On-course POV',
      'The polo is called Espresso Martini, so you order the drink. The shirt and the glass in one shot at the halfway house.',
      'Any creator. The guy who treats the turn like happy hour.',
      'A martini glass sliding into frame across the bar top, the print behind it. No face yet.',
      'Pull back: the polo matches the drink. One sip, then the whole fit at the bar.',
      ["The polo's called Espresso Martini so this was mandatory.",
       'Nine holes down, one of these, nine to go.',
       "If the shirt's named after a drink, you order the drink."],
      [(OPEN, 'The glass slides in, the print behind it. Say the opener.'),
       (MID, 'Hold the drink next to the print. Close-up of the print, then the drink.'),
       (CLOSE, 'Cheers to camera, one sip, walk back to the cart for the back nine.')],
      on_screen='Espresso Martini. The polo and the drink.', products='Espresso Martini polo',
      why="Breezy Golf built a whole brand on the drink that belongs to the group, and Bogey Bros' cart shot shows two guys at the turn is enough of a scene.",
      inspo=[('Bogey Bros', 'Two guys in the cart, one line, no spec list. Steal the framing for the halfway house.', 'https://app.tryatria.com/ad/m1228261266174271'),
             ('Breezy Golf', 'The Transfusion: a drink that belongs to the crew. Make the Espresso Martini yours.')],
      do='One drink, casual. Say the print name.',
      dont='Anyone looking drunk. HYDR18 or hangover talk. A second round on camera.'),
    A('fall', 'Closet Grunk: the respectable one', 'Skit',
      'The Closet Grunk button-down looks like a normal shirt from across the room. She approves, then she finds the Grunk label.',
      'Couples. The guy whose partner vetoes the loud polo at dinner.',
      'Him doing up the buttons in the bathroom mirror, profile to camera, the tonal camo reading as plain.',
      'Her line at 5 seconds: "Finally." Then she gets close and finds the Grunk logo on the collar or the label.',
      ["Finally, a shirt I can take him to my parents' in.",
       "He says it's a Grunk shirt. It looks like a normal shirt. Suspicious.",
       'Dress code says collared shirt. This is a collared shirt. Technically.'],
      [(OPEN, 'The buttons, in the mirror, profile. Her voice off camera.'),
       (MID, 'She nods from across the room. Then she walks over and turns the collar or finds the label. The Grunk logo up close.'),
       (CLOSE, 'The two of them out the door. He winks. Text: ' + CONSENT + '.')],
      on_screen='The respectable side of Grunk Dolfer', products='Closet Grunk button-downs',
      why="Bogey Bros' rank-6 ad is a guy doing up a print polo in a bathroom with 'are you letting your man wear this to dinner' over it, and it has run since March.",
      inspo=[('Bogey Bros', 'Doing up the buttons in the bathroom, "Are you letting your man wear this polo to dinner?". Steal the mirror open and her question.', 'https://app.tryatria.com/ad/m1447288833790481'),
             ('Bogey Bros', '"Clean patterns that\'ll pass a dress code." The range from respectable to loud as the pitch.', 'https://app.tryatria.com/ad/m1231852459066930')],
      do='Keep her genuinely pleased. The joke is that it is a Grunk shirt. She is in on it and consent is on screen.',
      dont='Overexplain the camo. Let her be mean. Hold the shirt up to the lens.'),
    A('fall', 'Fall scramble fit check', 'Fit check',
      'Head to toe walking off the first tee at a scramble or charity outing. Shoes up to the print, then the team steps in.',
      'Any creator playing an outing this fall. Scramble teams.',
      'Camera on your shoes on the tee box, tilting up the whole way to the print. Beer in the cup holder behind you.',
      'A teammate steps into frame in a different print at 4 seconds. Then the other two.',
      ["Scramble fit check. Let's go.",
       'Charity outing. 27 holes. One loud polo.',
       "Rate the fit, don't rate the swing."],
      [(OPEN, 'The tilt, shoes to print. Say the opener.'),
       (MID, 'The print up close, name it. Teammates step in one at a time.'),
       (CLOSE, 'The four of you at the scramble sign or the first tee. Hoodie on if it is cold, polo under it.')],
      on_screen='Fit check. Then the print name.', products='Polos and hoodies',
      why="Fit checks are the biggest format in golf TikTok right now, and Bad Birdie's 'play 2 holes with me' proves an invitation on the tee holds people.",
      inspo=[('Bad Birdie', 'A creator on the tee with a driver, "Play 2 holes with me". Steal the invitation, not the line.', 'https://app.tryatria.com/ad/m1623760625766692')],
      keep_from=['Across the fairway, then up close'],
      do='Name the print. Show the group. Show both layers if you are wearing a hoodie.',
      dont='Pose like a catalogue. Skip the print close-up.'),
    A('fall', 'Going as a golfer for Halloween', 'Skit',
      'Every guy at the party is Happy Gilmore. You go as a Grunk: a loud polo, a beer in hand and a terrible practice swing. Late October only.',
      'Any creator with a party to go to. Film by Oct 24.',
      'A hockey jersey held up in one hand, The Gilmore polo in the other. Pick the polo.',
      'The swap: jersey down, polo on, then you walk into a kitchen full of real costumes.',
      ['Every guy at this party is Happy Gilmore. Be the one in the polo.',
       'Golf costume. Zero effort. One shirt.',
       'My wife said go as a golfer. This is a golfer.'],
      [(OPEN, 'The two options held up. Say the opener. Choose the polo.'),
       (MID, 'Walk into the party. Someone asks what you are. "Golfer." A terrible practice swing in the kitchen, beer in the other hand.'),
       (CLOSE, 'Close-up of the print. "Best costume here." Posted by Oct 31.')],
      on_screen='Halloween, solved', products='The Gilmore polo, Chunkman polos',
      why="Every 2026 costume guide names the Happy Gilmore outfit as the default golf costume, so the room will already have three of them, and Grunk's own Happy Gee line is the punchline.",
      inspo=[('Chubbies', 'Low-production pranks over glossy photography. A costume bit filmed on a phone at a real party.')],
      do='Film by Oct 24. Post before Oct 31. Beer in hand, casual.',
      dont='Use any film or Netflix imagery. Post it after Oct 31. Act drunk at the party.'),

    # ---------------- Gift him the one he'll actually wear ----------------
    A('gift', 'The golfer who has everything', 'Voiceover',
      'She flicks through twelve navy polos in his closet and lands on the one thing he does not own: a polo with a chubby guy holding a beer on it.',
      'Wives, girlfriends, daughters and sons buying for the golfer who is hard to shop for.',
      'A closet rail of navy and grey polos, her hand flicking through them fast. Her voice, no face yet.',
      'The Grunk print appears at the end of the rail at 5 seconds. She pulls it out and holds it against the plain ones.',
      ['He has every golf thing. He does not have this.',
       "Twelve navy polos. Twelve. Here's number thirteen.",
       "Finally found something he didn't have."],
      [(OPEN, 'The rail, the flick, the opener over it.'),
       (MID, 'The Grunk print comes out. Hold it against the navy ones. The print up close.'),
       (CLOSE, 'Him wearing it on a Saturday. "He has not taken it off."')],
      on_screen="The one he'll actually wear", products='Chunkman polos, any loud print, gift cards',
      why="Bad Birdie's rank-5 ad is her voice over his polos, and our own review card 'My old polos never left the closet again' is one of our best stills.",
      inspo=[('Bad Birdie', '"He\'s golfing all the time, he might as well be best dressed." Her voice, his polos, a hand on the fabric.', 'https://app.tryatria.com/ad/m1548498556597153')],
      ads=['120249603609520115'], keep_from=["Retire dad's polos"],
      do='A real closet. "Finally found something he didn\'t have" is a real Grunk review, say it as is.',
      dont='Any price or offer outside Black Friday week. Say anything about him you do not know is true.'),
    A('gift', 'Would you let your man wear this?', 'Reaction',
      'One question to women, with the loudest print as the answer. Ten seconds.',
      'Women creators, or a couple. The partner who gets asked.',
      'Macro of the collar and the placket, the print too close to read, then a pull back to the whole thing.',
      'His face at 4 seconds: a shrug, a grin, nothing scripted.',
      ['Would you let your man wear this to dinner?',
       'Be honest, is this a yes or a no?',
       'Girls, he wants this one. Verdict?'],
      [(OPEN, 'The macro, the question.'),
       (MID, 'Pull back to the full print on him. His shrug.'),
       (CLOSE, 'Her verdict, one word. Text: ' + CONSENT + '.')],
      on_screen='Would you let him?', products='Drinko, Chunkman, Vegas Leopard, any loud print',
      why="Bogey Bros runs two ads on exactly this question ('would you let your man wear this polo?') and both sit in their top ten.",
      inspo=[('Bogey Bros', 'Macro of the collar and placket, "DON\'T LET HIM WEAR THIS TO YOUR PARENT\'S HOUSE". Steal the macro open.', 'https://app.tryatria.com/ad/m1754504355696010'),
             ('Bogey Bros', '"Are you letting your man wear this polo to dinner?" as the whole ad.', 'https://app.tryatria.com/ad/m1447288833790481')],
      do='Ask the question straight. She is in on the joke and consent is on screen.',
      dont='Answer it yourself. Run past 12 seconds.'),
    A('gift', 'The text from his girlfriend', 'Screen record',
      'One phone notification on a black screen, then the shirt in the exact place he was told not to wear it. Eight seconds.',
      'Any creator with a partner who texts like this.',
      "A black screen with one iMessage from Babe: DO NOT wear the beer shirt to my mom's.",
      "The cut at 3 seconds to him in the shirt at her mom's table. Her face.",
      ["DO NOT wear the beer shirt to my mom's.",
       'You are not wearing that to the rehearsal dinner.',
       'Please tell me you packed a normal polo.'],
      [(OPEN, 'The text on black. Nothing else. Three seconds.'),
       (MID, 'Him in the shirt at the exact place. Beer in hand if it fits the room.'),
       (CLOSE, 'Her face. Text: ' + CONSENT + '.')],
      on_screen='The text itself', products='Any loud print',
      why="Bogey Bros' rank-7 ad is a single text on black for ten seconds, but our own fake tweet and iMessage ads lost, so the line has to sound like a real person and the shirt has to land within 3 seconds.",
      inspo=[('Bogey Bros', 'A black screen, one text from "Babe", then the shirt. Ten seconds, rank 7.', 'https://app.tryatria.com/ad/m2115617322635468')],
      do='One message, a real-sounding line, the shirt within 3 seconds. Treat it as a test.',
      dont='A fake tweet, a fake review, a search bar. More than one message.'),
    A('gift', 'Dad and lil dude', 'Walkout',
      'Matching Chunkman polos on dad and the kid. The two shirts laid side by side first, then the kid walks out in his.',
      'Dads who golf with their kid. Moms buying for both.',
      'Two polos laid side by side on the bed, one tiny. Same print.',
      'The kid walking out of the bedroom in it at 4 seconds, then dad behind him in the big one.',
      ['He wanted to match dad. Done.',
       'Kid size, dad size, same shirt.',
       'My son loves his kid sized shirts. He looks just like his dad on the golf course.'],
      [(OPEN, 'The pair laid out. Say the opener.'),
       (MID, 'The walkout, kid first, dad second. Both prints up close.'),
       (CLOSE, 'The two of them on the putting green. A high five.')],
      on_screen='Matching dad and lil dudes', products='Kids polos + the matching adult print',
      why="Waggle's gift reviews are full of parents buying one for every boy in the house, and nobody in loud golf is filming the matching walkout.",
      inspo=[('Waggle', 'Hat gift reviews: "I got one for all these boys". The gift is the matching, not the product.')],
      do='Consent for the kid. No face if the parent prefers. Check which kids prints are on the site before you film.',
      dont="Beer anywhere in the kid's shot."),
    A('gift', 'Black Friday haul: BOGO + 30% off', 'Unboxing',
      'The order that arrives after the deal, dumped out on the bed and counted. Film by Nov 10, post Nov 26 to 30 only.',
      'The collector. The gift buyer who covered three people and kept two.',
      'The box tipped out onto the bed, five polos sliding out at once.',
      'Counting them out loud, one at a time, a number on screen for each. Then the one you keep.',
      ['Buy one get one and 30% off sitewide. So, yeah.',
       'This is what BOGO plus 30 looks like.',
       'Gifts for three people and two for me.'],
      [(OPEN, 'The dump. Say the deal.'),
       (MID, 'The count, print names as you go, who each one is for.'),
       (CLOSE, 'The one you keep, on. Say the deal once more and that it ends Cyber Monday.')],
      on_screen='BOGO + 30% off sitewide (Black Friday videos only)', products='Everything (Black Friday)',
      why="Bad Birdie's unboxings are their rising shape this fall, and Black Friday week is the biggest week we have.",
      inspo=[('Bad Birdie', 'A box opened on camera with the reveal as the rehook. Steal the shape, add the count.', 'https://app.tryatria.com/ad/m937514819007024')],
      do='Say the deal exactly as it is on the site. Film by Nov 10. Post Nov 26 to 30.',
      dont='Say the offer before Black Friday week or after Cyber Monday.'),
    A('gift', 'The stocking stuffer drawer', 'Flat lay',
      'Koozies, ball markers and hats, placed on the table one by one, fast. Nothing that needs a size.',
      'Gift buyers filling stockings and secret santa.',
      'Hands placing items on a table one per beat: koozie, marker, hat, the Tittees hat.',
      'The hat flipped to show the lining that says GOLF IS A DRINKING SPORT. Then the drawer closing.',
      ['Stocking stuffers for the guy who golfs. Under forty bucks, all of it.',
       'Koozie, marker, hat. Done by Tuesday.',
       'He will not return any of this.'],
      [(OPEN, 'The placing, fast, hands only.'),
       (MID, 'Each item picked up for a second: what it does. The lining flip.'),
       (CLOSE, 'The drawer or the stocking closing. Cut to him using the koozie on the cart.')],
      on_screen='Item names and prices from the site: koozies $9.95, ball markers $11.95, hats $39.95', products='Koozies, ball markers, hats, divot tools, towels',
      why='Golf Course Prints has run gift ads for golfers since Oct 1, and small items with one job each is the shape the hat and koozie reviews already describe.',
      inspo=[('Golf Course Prints', '"Personalized Gifts For ANY Golfer", live from Oct 1. The gift lane starts in October.', 'https://app.tryatria.com/ad/m1989979582389347')],
      do='Real prices from the site on the day. Tittees and cart girl hats are fine.',
      dont='Anything that needs a size. Guess a price.'),
    A('gift', 'Christmas money, spent', 'Screen record',
      'Dec 26, the gift card goes on the new drop in eleven minutes. Screen record plus your face.',
      'The collector who got a gift card. Dec 26 to Jan 5 only.',
      'A Grunk gift card held up in front of the phone, the site already open behind it.',
      'The cart total climbing as you add polos, then the checkout tap.',
      ['Got a Grunk gift card. It lasted eleven minutes.',
       'Christmas money. Gone. Worth it.',
       'The in-laws asked what I wanted. This.'],
      [(OPEN, 'The card to camera. Say the opener.'),
       (MID, 'Screen record: scroll, add to cart, one line on why each print.'),
       (CLOSE, 'Checkout. Then the box arriving, as a follow-up.')],
      on_screen='Dec 26', products='Gift cards, polos',
      why='Our own December runs strong to Dec 31 on gift cards and Christmas money, and Hismile proved a promise of something shown later ("you\'ll see the box arrive") holds people to the end.',
      inspo=[('Hismile', 'Promise something you will show later and say when, then show it. Here the promise is the box landing.', 'https://app.tryatria.com/ad/m1406603948018630')],
      do='Film Dec 26 to Jan 5. Hide the card number and balance.',
      dont='Show a real card number. Post it before Christmas.'),

    # ---------------- Golf is a drinking sport ----------------
    A('drink', 'Rated for 19 holes', 'On-course POV',
      'Hole 1 to the bar in one shirt, beer in hand at the turn and the end. Our best on-course footage says it in five words: most polos quit after 18.',
      'Any creator with a real round to film. The Saturday group that ends at the bar.',
      'The first tee shot filmed from behind, the print filling the bottom of the frame, beer in the cup holder.',
      'A cut to the halfway house at 5 seconds, can in hand. Then the bar at the end, still looking sharp.',
      ["Most polos quit after 18. This one's rated for 19.",
       'One shirt, 18 holes, then the bar. Watch.',
       "We'll see how it looks at the 19th."],
      [(OPEN, 'The tee shot from behind. Say the opener.'),
       (MID, 'Real moments: a bad shot, a good one, the cart, the turn with a beer in hand. Text beats: 4-way stretch, moisture-wicking, breathable.'),
       (CLOSE, 'The 19th hole. Everyone still looking good. Cheers to camera.')],
      on_screen='Rated for 19 holes',
      why='Our own 337 C, real on-course footage of two guys drinking under MOST POLOS QUIT AFTER 18, is one of the cheapest sales we have ever bought.',
      inspo=[('Bogey Bros', 'Two guys in a cart, one line, no spec list. Steal the two-guys framing for the turn.', 'https://app.tryatria.com/ad/m1228261266174271')],
      ads=['120249439447190115'], keep_from=['Rated for 19 holes'],
      do='Real footage from a real round. Beer in hand, casual. The shakier the better.',
      dont='Chug, shotgun, or drive the cart with a beer. Anyone looking drunk.'),
    A('drink', "The cart girl's favourite foursome", 'On-course POV',
      'The cart girl pulls up to four guys in Grunk and rates the shirts. She has the power in the clip and she is laughing with them.',
      'A woman creator who works a cart or plays, and a foursome who agreed to be filmed.',
      'Filmed from the cart as it rolls up, four loud polos coming into frame one by one.',
      'Her verdict on each shirt, fast, four in eight seconds. The Tittees hat gets a nod.',
      ['Pulled up to this group and had to film it.',
       'Okay, which one of you picked the shirts.',
       'Four for four. Finally.'],
      [(OPEN, 'The roll-up from the cart. The four shirts.'),
       (MID, 'Her ratings, one line each. The guys answer back. Beer in hand, nobody drunk.'),
       (CLOSE, 'She drives off. Text on screen: ' + CONSENT + '.')],
      on_screen=CONSENT, products='Polos, Donde Esta La Cart Girl hat, Tittees hat',
      why="Cart girl POVs are the biggest driver in golf TikTok (Shay Patino, Cass Holland), and Good Good's August ad showed what happens when the woman is the butt of the joke instead of in on it.",
      inspo=[('Cass Holland', 'Cart attendant videos captioned "And then I drove away" and "Everyone agreed to be in this video". She runs the clip.'),
             ('Pins and Aces', 'The old winner: "wearing our polos may cause compliments from the cart girl". The compliment is the pitch.')],
      do='She is in on the joke and laughing with them. Consent on screen. Beer in hand only.',
      dont='Anything that reads as hitting on her. Drunk golfers. Anyone driving the cart with a beer.'),
    A('drink', 'Rate this polo at the 19th hole', 'Street interview',
      'Walk the bar after the round and ask strangers to rate the print 1 to 10. Keep the low scores, they are the rehook.',
      'An outgoing creator. Anyone wondering if a loud polo is too much.',
      "A stranger's face reacting before the camera shows the shirt.",
      'Someone gives it a four at 5 seconds. The next person gives it a ten and asks where you got it.',
      ['Rate the shirt, one to ten, go.',
       'Asking the 19th hole what they think of the Drinko.',
       'Someone gave it a four. Watch what happens next.'],
      [(OPEN, 'The first face, then the shirt. Say the opener.'),
       (MID, 'Four to six answers, scores on screen. Keep the funny ones and the low one.'),
       (CLOSE, 'The best quote. Someone asks where you got it. Print up close.')],
      on_screen='The scores',
      why='Nobody in loud golf is doing bar interviews, and "where did you get that" is what our reviews say happens every round, so let strangers say it on camera.',
      inspo=[('Waggle', 'Review quote cards: "Cart girls couldn\'t stop complimenting". Get the quote live instead of on a card.')],
      keep_from=['"Where did you get that?" tally'],
      do='Consent from everyone filmed. Keep the real scores, even the low ones.',
      dont='Script the answers. Film anyone who looks drunk.'),
    A('drink', 'Hole 1 vs hole 18', 'Side by side',
      'The shirt at the start and at the end of a hot round, same pose, same angle. Sweat and all. Only say what the clip shows.',
      'Any creator in a warm state. Guys who hate a sweaty, wrinkled shirt by the back nine.',
      'A split screen: hole 1 on the left, hole 18 on the right, same pose, the temperature on screen.',
      'The pull back at 4 seconds: the hole 18 side is live, you are standing there, the shirt still looks like a shirt.',
      ['Hole one. Hole eighteen. Same shirt.',
       'Ninety-five degrees, four hours, moisture-wicking or whatever. See for yourself.',
       'Best shirt I own to beat the heat.'],
      [(OPEN, 'The two stills side by side. Say the opener.'),
       (MID, 'Honest checks: collar, back, sleeves. Beer in hand at the turn if there was one.'),
       (CLOSE, 'Walk off the 18th green in it. Same shirt, same guy.')],
      on_screen='1 / 18',
      why="A before-and-after is the oldest proof shape there is, and 'best shirt I own to beat the heat' is a real Grunk review, so the claim is already in a customer's words. Drdent's silent test is the model.",
      inspo=[('Drdent', 'Go quiet and let the camera watch the thing work, then react for real. Twenty silent seconds, then "look at that".', 'https://app.tryatria.com/ad/m1563635778876692')],
      do='Be honest. The shirt can look worn. Say the site claims only: moisture-wicking, breathable, 4-way stretch.',
      dont='UPF, sun protection, stain-proof, beer-proof. Say it never shows sweat.'),
    A('drink', 'How many beers fit in the Den Caddy', 'Count demo',
      'Fill the cooler on camera, one can per beat, and count. The number on screen climbs and the free polo comes out at the end.',
      'Any creator with the Den Caddy. The guy who buys the beer for the group.',
      'Cans going into the cooler pocket one at a time, a hand and ice, the count starting at 1 on screen.',
      'The number keeps climbing. Then the free polo pulled from the main compartment at the end.',
      ["How many fit? Let's find out.",
       "It's a golf bag with a cooler in it. Counting.",
       "The guys asked. Here's the answer."],
      [(OPEN, 'The empty cooler, the pile of cans, the first one in.'),
       (MID, 'Loading, counting out loud, the number on screen each time.'),
       (CLOSE, 'The last can, the total, the free polo out of the main pocket. Roll it onto the cart.')],
      on_screen='The running count. Den Caddy + free polo (confirm the free polo is live before filming)', products='Den Caddy + free polo',
      why="Waterboy's best ad is a number said five times before the reveal, and our own 326 series proved the Den Caddy offer sells when it is shown plainly.",
      inspo=[('Waterboy', '"This has 3,100 milligrams" five times, then the reveal. A number that keeps changing holds people.', 'https://app.tryatria.com/ad/m1616399766694709')],
      ads=['120246364301250115'],
      do='Ice, real cans, an honest count. Confirm the free polo is live before filming.',
      dont='Drink any of them on camera in this one. Say a number you did not count.'),
    A('drink', 'The weekend golfer in the wild', 'Voiceover',
      'A nature-documentary whisper over a guy in a Chunkman polo looking for his ball in the trees with a beer. Two or three lines, then he finds the wrong ball.',
      'A creator with a buddy to narrate. Anyone who loves the parody.',
      'A long lens on a guy in the trees, the print visible through the branches, beer in his hand.',
      '"Here we see" at 3 seconds. Then he finds a ball. It is not his.',
      ['Here we observe the weekend grunk in his natural habitat.',
       'Note the plumage. Loud, so the group can find him.',
       'He has not seen a fairway since the third.'],
      [(OPEN, 'The trees, the long lens, the whisper.'),
       (MID, 'He searches. He finds a ball. Holds it up. Wrong brand. Keeps it anyway.'),
       (CLOSE, 'The walk back to the cart, beer still in hand. "Remarkable."')],
      on_screen='The weekend grunk', products='Chunkman polos',
      why="Bob Does Sports earned 'Bobby Fairways' by hitting zero fairways in 36 holes, and FrontPorchDad built 900K followers saying things golfers actually say. Say those, not catchphrases.",
      inspo=[('Bob Does Sports', 'The nickname earned on camera, not written. Let the bit come from a real bad round.'),
             ('FrontPorchDad', '"Stuff I hear people say a lot." The narration should be what your group already says about this guy.')],
      do='Whisper it. Commit to the voice. Two or three lines is plenty.',
      dont='Overwrite it. Act drunk. Borrow a catchphrase.'),

    # ---------------- Dad bod approved ----------------
    A('fit', 'Small through 5XL on real bodies', 'Fit check',
      'Five guys, five sizes, one print, shoulder to shoulder. The camera walks the line and the 5XL guy turns. Nobody else in golf can film this honestly.',
      'A crew of five. The big guy who has been burned by brands that stop at 3XL and run small.',
      'Five men shoulder to shoulder, the same loud print on all of them, the camera tracking left to right from the small guy.',
      'The 5XL guy turns sideways at 5 seconds and the shirt still sits right over the belly.',
      ["Small through five X. Same shirt. Nobody's squeezed into it.",
       'Every other brand stops at three X and runs small. We asked the big guys.',
       'I fit the chunk man description, so why not.'],
      [(OPEN, 'The track down the line. Say the opener.'),
       (MID, 'The turn. The biggest guy swings. Tucked and untucked both shown.'),
       (CLOSE, 'The five of them walk to the first tee. Sizes over each man.')],
      on_screen='S / M / L / XL / 5XL over each man', hot=1, products='Any polo that goes to 5XL (check the product page)',
      why="Our own Tiktok #25 ('small through five', 'dad bod approved') is one of our best videos, and every competitor's reviews say their polos run small.",
      inspo=[('Bad Birdie', 'The cinematic swing profile, no words. Steal the slow-mo swing for the biggest guy.', 'https://app.tryatria.com/ad/m2238178400364685')],
      ads=['120244036055130115'],
      do='Real sizes, real bodies. Say "relaxed, dad bod approved fit". Check 5XL is on that print before you film.',
      dont='Name a competitor on screen. Say "slimming" or "athletic". Say every print comes in 5XL.'),
    A('fit', 'The full swing test', 'Fit check',
      'A full swing in slow motion in the relaxed cut. Nothing rides up, nothing pulls across the back. Claim only what the clip shows.',
      'Any creator with a driver and a phone that does slow motion.',
      'The top of the backswing frozen, the print stretched across your back, filmed from behind.',
      'The follow-through at real speed, shirt still down. Then the same swing from the front.',
      ['Full send. Shirt stays put.',
       'Four-way stretch, allegedly. Testing.',
       'Watch the hem.'],
      [(OPEN, 'The frozen backswing from behind. Say the opener.'),
       (MID, 'Impact and finish, slow, from behind and then from the front.'),
       (CLOSE, 'The ball goes wherever it goes. You laugh. The hem is still down.')],
      on_screen='Stays tucked (only if it does)',
      why="Bad Birdie's rising ad is a cinematic swing with no words at all, and the swing is the one moment where fit either works or it does not.",
      inspo=[('Bad Birdie', 'Swing follow-through in profile against blue sky, music only. Steal the shot, add the hem.', 'https://app.tryatria.com/ad/m2238178400364685')],
      do='Tuck it, swing hard. Say the site claim: 4-way stretch.',
      dont='Claim anything the clip does not show. Say it never comes untucked.'),
    A('fit', 'I fit the Chunkman description', 'Fit check',
      'A guy with a belly talks to the mirror about why he stopped hiding it. The shirt is cut for him and it says so on the chest.',
      'The Weekend Grunk. Guys with a beer belly who are done hiding it.',
      'Belly first, filling the frame in the mirror, then the camera tilts up to your face.',
      'You turn sideways at 4 seconds and the shirt hangs clean. Then you point at the Chunkman and at yourself.',
      ['Hides my beer belly. Gets compliments every round.',
       "I'm the guy on the shirt. Might as well wear the shirt.",
       'Great fit for a dude with a beer belly.'],
      [(OPEN, 'The tilt, belly to face. Say the opener.'),
       (MID, 'The side. The point: Chunkman, then you. Room to move.'),
       (CLOSE, 'Out the door with the clubs. Beer in the cooler.')],
      on_screen='Dad bod approved', products='Chunkman polos',
      why='Our own 284-1 callouts ("hides my beer belly", "gets compliments every round") outsold almost everything, and "great fit for a dude with a beer belly" is a real review.',
      inspo=[('Bogey Bros', 'The forced deadpan review: he side-eyes the lens and says one word. Steal the deadpan.', 'https://app.tryatria.com/ad/m919515360698444')],
      ads=['120237891762730115'], keep_from=['I fit the Chunkman description'],
      do='Deadpan. Proud. Say "relaxed, dad bod approved fit".',
      dont='Self-pity. "Slimming" or "athletic". Sad music.'),
    A('fit', 'Not for try-hards', 'Voiceover',
      'Three reasons you should never buy Grunk Dolfer: you take golf seriously, you cannot take a joke, you own a swing trainer. A negative hook in a feed full of "you need this".',
      'Any creator. The fun guy in the group self-selects.',
      'Polos hanging on a garage rail, the camera panning along them, text: 3 reasons you should NEVER buy Grunk Dolfer.',
      'Reason one lands at 3 seconds with a print pulled off the rail. Two more, one print each.',
      ['Three reasons you should never buy this shirt.',
       "If you shoot 78 and sulk, this isn't for you.",
       'Hardos, keep scrolling.'],
      [(OPEN, 'The rail, the pan, the title on screen.'),
       (MID, 'Three reasons, one print each, short.'),
       (CLOSE, 'The Chunkman up close. "Everyone else, this way."')],
      on_screen='The three reasons',
      why="Bogey Bros' '3 reasons why you should NEVER buy' ad sits in their top 15 on nothing but a garage rail and a reverse list.",
      inspo=[('Bogey Bros', '"3 reasons why you should NEVER buy bogey bros": polos on a garage rail, "not for golf hardos, try-hards". Steal the frame and the reverse list.', 'https://app.tryatria.com/ad/m2108429963090261')],
      do='Short reasons. Keep it under 20 seconds.',
      dont='More than three. Name a competitor.'),

    # ---------------- The crew ----------------
    A('crew', 'Nobody wants to draw this team', 'Walkout',
      'A scramble team walks in from the parking lot in four prints and the other teams look up. Banter between you, not to the camera.',
      'A foursome. The Crew Captain who organises the scramble team.',
      'Four guys walking toward the camera from the parking lot, four prints, bags on shoulders, not looking at the lens.',
      'One subtitled line from one of them at 3 seconds. Then a cut to another team staring.',
      ['Who invited these guys.',
       "Scramble team's here. Nobody's winning long drive but we're winning this.",
       "We can't putt. Look at us though."],
      [(OPEN, 'The walk, wide. Film it twice, use the second take.'),
       (MID, 'The stare from the next team. A quick real shot. A beer at the turn, in hand.'),
       (CLOSE, 'The team photo in the prints at the first tee.')],
      on_screen='One subtitle line of banter',
      why="birddogs' number one ad right now is four guys walking a fairway with one subtitled line, and the foursome is the gap nobody in loud golf has filled.",
      inspo=[('birddogs', 'Four guys walking down a fairway laughing, one subtitled line, "who invited the camera guy". Steal the walk and the subtitle, not the line.', 'https://app.tryatria.com/ad/m1138217752221924')],
      do="Film the walk twice. Say what your group actually says. Get the other team's okay before you film them.",
      dont='Look at the camera. Pose. Act drunk.'),
    A('crew', 'The group chat picked the polos', 'Screen record',
      'Screen-record the chat arguing for three days over which prints to order for the trip, then cut to the four shirts on the hotel bed.',
      'The Crew Captain planning the trip.',
      'A group chat scrolling fast, polo screenshots flying in, names hidden.',
      'The cut at 5 seconds to the four shirts laid out on a hotel bed. Then the group in them.',
      ['The chat has been going for three days about shirts.',
       'Democracy picked the Drinko.',
       'Eight guys, one vote, no winners.'],
      [(OPEN, 'The chat scroll. Say the opener.'),
       (MID, 'The bed with the shirts laid out. The best line of the chat on screen.'),
       (CLOSE, 'The group wearing them at the first tee of the trip.')],
      on_screen="The chat's best line",
      why="Our biggest single orders are crews buying together, and Bogey Bros pitches its bundle straight at the group, so a real group chat is the most honest screen record there is.",
      inspo=[('Bogey Bros', 'Bundle tiers aimed at groups and the "Field of 8". The crew is the buyer.')],
      do='A real chat with the names hidden.',
      dont='A fake chat. Show real names or numbers.'),
    A('crew', 'Loser buys the polos', 'On-course POV',
      'A two-man match, the loser buys the winner a polo. A count of holes on screen, the putt that decides it, the handover at the bar.',
      'Two competitive buddies.',
      'Two guys shaking hands on the first tee. "Loser buys."',
      'The hole count on screen climbing. The swing or putt that decides it.',
      ["Loser buys the other guy a Grunk polo. Let's go.",
       'Three holes, one shirt on the line.',
       "He's never beaten me. Today he gets a polo."],
      [(OPEN, 'The handshake, the bet. Say the opener.'),
       (MID, 'The count. Highlights and lowlights. The deciding putt.'),
       (CLOSE, 'The handover at the bar, beer in hand. The loser puts it on.')],
      on_screen='The score',
      why="Good Good Golf's whole channel is stakes in the title, and a bet gives the viewer one thing to wait for.",
      inspo=[('Good Good Golf', 'Stakes in the title ("Winner gets $1,000"), a count, a decider. Steal the structure at 25 seconds.')],
      do='A real bet. Cut to the decider.',
      dont='Run long. Chug at the bar.'),
    A('crew', "Field of 8: outfitting the guys' trip", 'Walkout',
      'Eight guys, eight prints, stepping off the shuttle on the first morning of the trip. The slow pan down the line names every print.',
      "The Crew Captain. Bachelor parties and guys' trips.",
      'Eight prints in a row stepping off a resort shuttle or out of a hotel elevator.',
      'The slow pan down the line at 4 seconds, each print named on screen.',
      ["Eight guys. Eight shirts. One scramble nobody's ready for.",
       'Bachelor party uniform, sorted.',
       "Scottsdale doesn't know what's coming."],
      [(OPEN, 'The step-off, wide. Say the opener.'),
       (MID, 'The pan, print names on screen, one line of banter.'),
       (CLOSE, 'The tee box, all eight, beer in hand for the ones who want one.')],
      on_screen='Print names, one per man',
      why="Bogey Bros sells its bundle as a 'Field of 8' for bachelor parties, and our own biggest orders are crews buying eight at once.",
      inspo=[('Bogey Bros', 'The group bundle pitched as a "Field of 8" for bachelor parties and groomsmen. Steal the lineup.'),
             ('birddogs', 'The foursome walk with banter. Make it eight.', 'https://app.tryatria.com/ad/m1138217752221924')],
      do='Shoot it on the first morning.',
      dont='Show the night before. Anyone looking drunk.'),
]

SPEC = dict(act_id=ACT, slug='grunk-dolfer', brand=BRAND, sections=SECTIONS, angles=ANGLES)

if __name__ == '__main__':
    write(SPEC, os.path.join(HERE, 'seed_amb_grunk_dolfer.sql'))
