/* Bundles scripts/render_report.py into src/reportpy.js (the Strategist's PDF renderer, run in Anthropic's code
   sandbox by stratmake.js). Run after editing the .py:  node scripts/build_reportpy.mjs  (from account-health/worker)
   Check the script locally first: python scripts/render_report.py <spec.json> out.pdf  (needs reportlab + matplotlib) */
import { readFileSync, writeFileSync } from 'node:fs';
const py = readFileSync(new URL('./render_report.py', import.meta.url), 'utf8').replace(/\r\n/g, '\n');
if (/`|\$\{/.test(py)) throw new Error('render_report.py must not contain a backtick or a dollar-brace');
writeFileSync(new URL('../src/reportpy.js', import.meta.url),
  '/* GENERATED by scripts/build_reportpy.mjs from scripts/render_report.py. Do not edit here. */\nexport const REPORT_PY = String.raw`' + py + '`;\n');
console.log('src/reportpy.js written,', py.length, 'chars');
