# Bundles docs/strategist-brain/knowledge/*.md into src/knowledge.js so the Strategist can read them
# (view `knowledge`). Run after editing any knowledge file, then deploy: python scripts/build_knowledge.py
import io, os, json, re
HERE = os.path.dirname(os.path.abspath(__file__))
SRC = os.path.normpath(os.path.join(HERE, '..', '..', '..', 'docs', 'strategist-brain', 'knowledge'))
OUT = os.path.join(HERE, '..', 'src', 'knowledge.js')
docs, index = {}, []
for f in sorted(os.listdir(SRC)) if os.path.isdir(SRC) else []:
    if not f.endswith('.md'): continue
    key = f[:-3]
    text = io.open(os.path.join(SRC, f), encoding='utf-8').read().replace('—', ', ')
    docs[key] = text
    title = next((l.lstrip('# ').strip() for l in text.splitlines() if l.startswith('#')), key)
    index.append({'topic': key, 'title': title, 'lines': text.count('\n') + 1})
js = '/* GENERATED by scripts/build_knowledge.py from docs/strategist-brain/knowledge. Do not edit by hand. */\n'
js += 'export const KNOWLEDGE = ' + json.dumps(docs, ensure_ascii=False) + ';\n'
js += 'export const KNOWLEDGE_INDEX = ' + json.dumps(index, ensure_ascii=False) + ';\n'
io.open(OUT, 'w', encoding='utf-8', newline='\n').write(js)
print('knowledge.js:', ', '.join(f"{i['topic']} ({i['lines']} lines)" for i in index) or 'empty')
