/**
 * Builds src/routes.js: every /api route the two Locus workers answer (account-health and profit), with its
 * method and the comment above it, so the Strategist's locus_api tool can find "the route the screen uses"
 * the way a person finds the button. Generated, so it never drifts: run it after adding routes, then deploy.
 *
 *   node scripts/build_routes.mjs
 */
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..', '..', '..');
const SOURCES = [
  { worker: 'ah', dir: path.join(root, 'account-health', 'worker', 'src') },
  { worker: 'profit', dir: path.join(root, 'profit', 'worker', 'src') },
];
/* Never offered: auth, secrets, webhooks, cron triggers, public pages, and the Strategist's own door. */
const SKIP = /^\/api\/(login|logout|me|auth|password|session|token|secret|oauth|webhook|asana-webhook|slack|cron|tick|ask$|ask\/(apply|progress|stop)|admin-token|keys?)\b/;

const out = new Map();
for (const src of SOURCES) {
  for (const f of fs.readdirSync(src.dir).filter(x => x.endsWith('.js') && x !== 'routes.js' && x !== 'knowledge.js')) {
    const lines = fs.readFileSync(path.join(src.dir, f), 'utf8').split('\n');
    lines.forEach((line, i) => {
      const re = /path(?:\s*===\s*|\.startsWith\()\s*['`](\/api\/[^'`$]+)['`]/g;
      let m;
      while ((m = re.exec(line))) {
        const p = m[1].replace(/\/$/, '');
        if (SKIP.test(p)) continue;
        const method = (line.match(/method\s*===\s*'(GET|POST|PUT|DELETE|PATCH)'/) || [])[1] || (/startsWith/.test(m[0]) ? 'ANY' : 'GET');
        /* The nearest comment above (up to 4 lines) says what it is for. */
        let note = '';
        for (let k = i - 1; k >= Math.max(0, i - 4) && !note; k--) {
          const c = lines[k].trim();
          if (/^(\/\*|\*|\/\/)/.test(c)) note = c.replace(/^(\/\*+|\*\/?|\/\/)\s*/, '').replace(/\*\/$/, '').trim();
          else if (c && !/^}/.test(c)) break;
        }
        const tail = line.slice(m.index + m[0].length, m.index + m[0].length + 120).match(/\/\/\s*(.+)$/);
        if (!note && tail) note = tail[1].trim();
        const key = `${src.worker} ${method} ${p}`;
        /* The handler's first lines: what it reads from the body and the query, so a call can be shaped right. */
        const code = lines.slice(i, i + 18).join('\n').replace(/\r/g, '').replace(/[ \t]+/g, ' ').slice(0, 1100);
        if (!out.has(key)) out.set(key, { w: src.worker, m: method, p, n: note.slice(0, 140), f, c: code });
      }
    });
  }
}
/* Where a Locus screen calls the route: the exact body the screen sends is the best example there is. */
const FRONT = [path.join(root, 'profit'), path.join(root, 'ask')];
const front = [];
for (const dir of FRONT) for (const f of fs.readdirSync(dir).filter(x => /\.(js|html)$/.test(x))) front.push([f, fs.readFileSync(path.join(dir, f), 'utf8').split('\n')]);
for (const r of out.values()) {
  const esc = r.p.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
  const re = new RegExp(`['\`]${esc}(['\`?/]|\\$\\{)`);
  for (const [f, lines] of front) {
    const i = lines.findIndex(l => re.test(l) && (r.m === 'GET' || r.m === 'ANY' || l.includes(r.m) || (lines[lines.indexOf(l) + 1] || '').includes(r.m)));
    if (i >= 0) { r.s = `${f}: ${lines.slice(i, i + 3).join(' ').replace(/\s+/g, ' ').trim().slice(0, 400)}`; break; }
  }
}
const list = [...out.values()].sort((a, b) => a.p.localeCompare(b.p) || a.m.localeCompare(b.m));
const body = `/* GENERATED by scripts/build_routes.mjs on ${new Date().toISOString().slice(0, 10)}. Do not edit by hand.
   Every /api route the Locus workers answer: w = worker (ah = account-health, profit = the profit worker),
   m = method (ANY = a prefix route that takes several), p = path, n = what it is for, f = file. */
export const ROUTES = ${JSON.stringify(list)};
`;
fs.writeFileSync(path.join(root, 'account-health', 'worker', 'src', 'routes.js'), body);
console.log(`${list.length} routes (${list.filter(r => r.w === 'ah').length} account-health, ${list.filter(r => r.w === 'profit').length} profit)`);
